### ISSUE TITLE
Explore lazy loading results in the experiment tracking view

### ISSUE THREAD

**Issue by Huongg** [kedro-org/kedro-viz#1005]
## Description
Related to #932 

Sometimes when the data is loading, or when the internet speed is not quite good, our viz page can look quite jumpy (with the animation), and it's hard to tell if something went wrong or just because the internet is bad and the content is still loading 😄. For example with the plot graphs, it can take quite a bit of time for it to load. 

To improve users we can create some simple lazy loading for the page while the data is still loading

## Possible Implementation
I've used [react-content-loader](https://www.npmjs.com/package/react-content-loader). The package is very small and very easy to implement. You can simply create a loader component for each main component (section). 

It's a mix of different shapes using svg, something as simple as the below

```
const MyLoader = () => (
  <ContentLoader viewBox="0 0 380 70">
    {/* Only SVG shapes */}    
    <rect x="0" y="0" rx="5" ry="5" width="70" height="70" />
    <rect x="80" y="17" rx="4" ry="4" width="300" height="13" />
    <rect x="80" y="40" rx="3" ry="3" width="250" height="10" />
  </ContentLoader>
)
```

## Possible Alternatives
I haven't used any other tool yet so open to more suggestions from the team

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
Development can go ahead and prototype something without needing initial designs, and then we can polish as a group.

**Comment by comym** [comment]
Hey @Huongg 
Looking good!

The alignment isn't perfect but looks alright to me. We can go this way. Much better than before.

However now I'm noticing that the header background and the content are now jumping - moving up and down, every time the loading bars come up and every time they go away. See below.

![Image](https://user-images.githubusercontent.com/55446576/188651659-48eab63a-c82d-4caa-b6b0-69269a524292.gif)

![Image](https://user-images.githubusercontent.com/55446576/188652073-d2dd1ca7-c226-4377-aab4-91fd2ba397f7.gif)

We should not have this movement at any time. The layout should not move around.

I guess we'll be ready after fixing that.
