### ISSUE TITLE
Metrics datasets do not show plots on pipeline visualisation

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-viz#1016]
## Description
I tried to click on the `R2 Score Linear Regression` dataset to view the metrics plot and saw this: 

![Screenshot 2022-08-16 at 13 20 16](https://user-images.githubusercontent.com/43755008/184878251-c6b28150-63b8-4c4a-a6e2-64d2d947a8bd.png)

## Context
I can't view the metrics plot for any of the metrics datasets.

**Comment by tynandebold** [comment]
We saw that, too. Fixing it here: #1014. Thank you for flagging!

**Comment by tynandebold** [comment]
Fixed with #1014
