### ISSUE TITLE
Kedro-viz setup.py requires test_requirements.txt, but it's not packaged in pypi 

### ISSUE THREAD

**Issue by cshaley** [kedro-org/kedro-viz#1028]
## Description
Kedro-viz setup.py requires test_requirements.txt, but it's not packaged in pypi

## Context
I am trying to package kedro-viz and kedro-airflow for conda-forge so that I can conda install them.  Conda-forge runs setup.py as part of the build process.  Kedro-viz directly references test_requirements.txt in setup.py, but test_requirements.txt is not packaged in the build for pypi, so running setup.py fails.

## Steps to Reproduce
1. Download kedro-viz via pypi.
2. unzip it and run python setup.py.  

## Expected Result
Setup.py succeeds.

## Actual Result
Setup.py fails because test_requirements.txt is missing.

```
 FileNotFoundError: [Errno 2] No such file or directory: 'test_requirements.txt'
```

See kedro-airflow [Issue 53](https://github.com/kedro-org/kedro-plugins/issues/53).  

Deprecation references:

https://github.com/pypa/setuptools/issues/1684
https://github.com/pytest-dev/pytest/issues/5534

**Comment by tynandebold** [comment]
Fixed with #1029
