### ISSUE TITLE
Richer search for experiment tracking

### ISSUE THREAD

**Issue by antoinebon** [kedro-org/kedro-viz#1039]
## Description
In Kedro-Viz experiment tracking, I would like to be able to search in my experiments based on a value of a variable that I am tracking, but it seems that the search is currently only going thru the experiment metadata

## Context
In order to track how a particular dataset is generated, I generate a run hash that is a hash of all the hyper-parameters that have an impact on the data generating process, which I then track via kedro viz experiment tracking. Since my datasets grow incrementally in time, I would like to be able to filter all the runs that have a particular hash, so that I can browse the history of the runs

## Checklist

- [ ] Extend experiment tracking search functionality to support searching in tracked variables (via the web app interface)
- [ ] Support matching on various data types (string, numeric, list, dict)

**Comment by tynandebold** [comment]
Thanks a lot for this request, @antoinebon! This is something we've been discussing within the team and hope to implement in the near future. We'll keep you updated here with any developments as we build this out.

**Comment by NeroOkwa** [comment]
Thanks a lot for this @antoinebon , we are currently doing user testing for a new Kedro Experiment Tracking feature. Would you be interested in participating? If yes, kindly provide an email address.

**Comment by antoinebon** [comment]
Hi @NeroOkwa , yes I could help with testing. Here is my email: antoine.bon@gmail.com

**Comment by tynandebold** [comment]
We'll reopen this ticket if we look at this again downstream.
