### ISSUE TITLE
Release 5.1.0 is missing static web files

### ISSUE THREAD

**Issue by Tomcat-Engineering** [kedro-org/kedro-viz#1055]
## Description

Running `kedro viz` results in an error:

```
 ...lib/python3.10/site-packages/kedro_viz/html/static' does not exist
```

If you download the wheel from [pypi](https://pypi.org/project/kedro-viz/#files) and unzip it, there is no `html` folder.

## Context

Trying to run on a new install.

## Steps to Reproduce

1. `pip install kedro-viz`
2. kedro viz

**Comment by tynandebold** [comment]
Thanks for the quick report, @Tomcat-Engineering. We saw it too and have fixed it. Please install `v5.1.1`, which is on PyPI now: https://pypi.org/project/kedro-viz/
