### ISSUE TITLE
Upgrade fastapi to >=0.73.0

### ISSUE THREAD

**Issue by jmholzer** [kedro-org/kedro-viz#1088]
## Description
We should upgrade the fastapi dependency of kedro viz to 0.73.0 or higher, preferably to the latest stable release. 

## Context
As noted in #1087, upgrading fastapi is a necessary step on the path to the best solution for #749.

## Possible Implementation
After the new requirement is specified, tests will have to be updated and a few manual end-to-end tests should be done to confirm things work as before.

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
Sounds great. We already have a dependabot PR open to upgrade this package in #1070. The specified version there isn't what you've outlined, though let's use that PR to fix this issue.

**Comment by AntonyMilneQB** [comment]
We've had FastAPI pinned to <0.67 for a long time: https://github.com/kedro-org/kedro-viz/pull/516/commits/dc11446f808c3eb8a89ab0d8827900e9013338f6. Looking at the tests that break when this restriction is lifted I think it should be reasonably easy to upgrade.

Let's make a separate issue for it, but @rashidakanchwala also noticed that version 0.67 enables [dataclasses to be used directly as responses](https://fastapi.tiangolo.com/advanced/dataclasses/). This might help to remove some (probably not all) of the REST response layer that translate from dataclasses to pydantic. We could also consider changing the flowchart model dataclasses to pydantic models - I'm trying to find out from @limdauto why this wasn't always the case.

**Comment by AntonyMilneQB** [comment]
Closed in #1086 - thanks @rashidakanchwala.
