### ISSUE TITLE
Give `MemoryDataSet` as dataset type

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro-viz#1093]
> **Note**. Good starter task for anyone wanting to get more familiar with kedro-viz!

Along similar lines to https://github.com/kedro-org/kedro-viz/issues/962...

Currently if you have a `MemoryDataSet` then kedro-viz will just give "Dataset type: -". Really this should be a `MemoryDataSet`.
![image](https://user-images.githubusercontent.com/49395058/191799120-10dba126-d227-4072-97d6-cb3de1310191.png)

It would be worth checking how other dataset types from `kedro.io` render in kedro-viz currently, e.g. `PartitionedDataSet`. I'm not sure why we're not showing `MemoryDataSet` currently so it might be a problem for other "core" dataset types also.

**Comment by deepyaman** [comment]
Upon further investigation, if a `MemoryDataSet` is explicitly defined in the catalog, then the dataset name will flicker on the metadata panel under Dataset Type before being replaced by a "-", only when you first click on the metadata panel. Similarly, modifying https://github.com/kedro-org/kedro-viz/blob/v5.1.1/package/kedro_viz/data_access/repositories/catalog.py#L59 to `dataset_obj = MemoryDataSet()` causes the flicker regardless of whether or not the `MemoryDataSet` is explicitly defined in the catalog.

> It would be worth checking how other dataset types from `kedro.io` render in kedro-viz currently, e.g. `PartitionedDataSet`. I'm not sure why we're not showing `MemoryDataSet` currently so it might be a problem for other "core" dataset types also.

This is not happening; `PartitionedDataSet`, etc. render fine.

**Comment by AntonyMilneQB** [comment]
Thanks for picking this up @deepyaman! Just an idea: maybe this is a consequence of the change in https://github.com/kedro-org/kedro-viz/pull/1015? I think it's unlikely but worth checking.

**Comment by deepyaman** [comment]
> Thanks for picking this up @deepyaman! Just an idea: maybe this is a consequence of the `shortenDatasetType` change in #1015? I think it's unlikely but worth checking.

I don't think it's a consequence of that, but it is where I ended up making a change (not sure if that's right, and we should instead make sure `undefined` doesn't get passed to the function).

**Comment by AntonyMilneQB** [comment]
If possible, I think we should make sure that `undefined` doesn't get passed to the function instead. Why would `MemoryDataSet` behave differently from `PartitionedDataSet`? I understand there might be a slight complication for cases where the dataset is not explicitly defined in the catalog, but from what you say it's still passing `undefined` even when explicitly specified? 🤔 Is the `self.dataset_type` logic in `DataNode` not working correctly?

If it's not possible to get to the bottom of this then fixing on the frontend side is better than how it is now, since the result to the end user would be the same, but I don't think it's the right solution. The frontend should just be blindly processing the dataset type as it does now, without doing anything different for a `MemoryDataSet`.
