### ISSUE TITLE
kedro viz --load-file does not show additional information

### ISSUE THREAD

**Issue by haijames** [kedro-org/kedro-viz#1101]
## Description
additional information only show when you run `kedro viz`, but when you save the visualization as a json file and then visualize it with `kedro viz --load-file`, the additional information disappear

When using `kedro viz`
![image](https://user-images.githubusercontent.com/45039771/192721988-1506566b-c70c-499c-be6d-1e189bb1ea50.png)

When using `kedro viz --load-file`
![image](https://user-images.githubusercontent.com/45039771/192721301-e66bfda9-452f-406d-9a79-f1879ff62ecd.png)

## Context
I tried to visualize my json file by using `kedro viz --load-file` and it doesn't show the parameter, so I cloned your demo-project and test it out with the `kedro viz --save-file`  and `kedro viz --load-file` and saw it have the same issue as I have in my project

## Steps to Reproduce

1. [First Step] Clone kedro-viz, pip install kedro-viz, kedro 0.18.1 and cd demo-project
2.  [Second Step] pip install --no-cache-dir --upgrade -r ./src/docker_requirements.txt
3.  [and so on...]  run `kedro run` `kedro viz --save-file a.json` and then `kedro viz --load-file`

## Expected Result
Information should be shown

## Actual Result
Information should be shown

## Your Environment

Web browser system and version: Chrome
Operating system and version: Windows 10 pro 21H2

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by tynandebold** [comment]
Thanks for the bug report, @haijames! This is a known issue and we're researching a way to better enable this behavior.

Just curious: are you saving the JSON because you want to be able to share your Kedro-Viz with others?

**Comment by tynandebold** [comment]
There's related work in #1263 for this, but we'll close it now as it isn't a priority.
