### ISSUE TITLE
Capitalize types in param docs

### ISSUE THREAD

**Issue by deepyaman** [kedro-org/kedro-viz#1108]
There's a mix of `Array`, `Boolean`, `boolean`, `string`, etc. in the JavaScript param docs that should be standardized. Capitalization looks like the right way to go:

"It should probably be capitalized everywhere: https://developer.mozilla.org/en-US/docs/Glossary/Boolean"

_Originally posted by @tynandebold in https://github.com/kedro-org/kedro-viz/pull/1104#discussion_r983265191_

**Comment by nikotome** [comment]
Good day! Can I work in this issue? Thanks

**Comment by tynandebold** [comment]
Yes, please do!
