### ISSUE TITLE
Create URL parameters for each element/section in kedro-viz

### ISSUE THREAD

**Issue by Huongg** [kedro-org/kedro-viz#1117]
## Description
Parameters are placeholders in the URL that begin with a colon. 

## Context
With this feature, every time user clicks on a node in the flowchart, or a run in the experiment tracking, it will reflect on the URL, for example:
`https://demo.kedro.org/experiment-tracking/run-id`
or
`https://demo.kedro.org/flowchart/selected:modular_pipeline_id` (we would need to think and agree on the path for workflow as its more complicated than the experiment tracking

Once we have this URL parameter, we can do other things such as store the path in local storage so when the user re-enters the URL, it will open where it was left before, or it can also be helpful for this idea[ here ](https://github.com/kedro-org/kedro-viz/issues/1116)

## Possible Implementation
This can be achieved using React router (which we already have in our kedro-viz). Since there will be a lot of different paths, maybe best if we can have `routes.config` in which we define different path like this

```
export const routes = {
  flowchart: {
      main: '/flowchart',
      selectedModularPipeline: '/flowchart/selected:modular_pipeline_id',
      focusedModularPipeline: '/flowchart/focused:modular_pipeline_id',
      selectedDataset: '/flowchart/selected:dataset_id',
    },
   experimentTracking: {
   .....
   }
}
```

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
I'm not sure we'd want to include `/flowchart` actually, as I think that would constitute a breaking change.
