### ISSUE TITLE
Investigate incorrect rendering of dataset node seen on a project with nested modular pipelines

### ISSUE THREAD

**Issue by jmholzer** [kedro-org/kedro-viz#1123]
## Description
After applying the fix (#1119) for [#1036](https://github.com/kedro-org/kedro-viz/issues/1036), another minor error in rendering is seen in the project used to replicate the bug.

On initial loading of the project, the data node 'Preprocessed Data' is visible, although it should be included in the 

<img width="533" alt="Screenshot 2022-10-05 at 19 44 12" src="https://user-images.githubusercontent.com/37243923/194142337-c201782f-e6fd-4282-ab2d-666b9349389c.png">

After expanding the 'Sub Pipeline' modular pipeline once, the data node is rendered correctly once it is collapsed.
<img width="288" alt="Screenshot 2022-10-05 at 20 10 14" src="https://user-images.githubusercontent.com/37243923/194143367-d0cc6462-388c-481b-991e-68526b83f06d.png">

I discussed this with @tynandebold, though we couldn't conclude if this is due to a bug in the tree generation code on the backend, or a bug in the rendering code on the frontend.

It could be an error on the backend because the generated tree includes the errant node as a child of both the default pipeline (`__root__`) and in the modular pipeline `sub_pipeline`. 

It could be an error on the frontend because the node is rendered correctly after one expansion / collapse of the modular pipeline.

This should be discussed in a tech design session.

In the case that it is an error on the backend, completing ticket #1122 will be a helpful first step in diagnosing the cause.
 
## Context
The bug is minor and has only been seen in this case, but could have deeper implications for the correctness of the code that causes it.

## Steps to Reproduce

1. Create a local project with the code given in #1119.
2. Run Viz.
3. Expand and collapse the 'Sub Pipeline' modular pipeline.

## Expected Result
The pipeline shown in the second image above should render first time.

## Actual Result
The pipeline shown in the first image above is rendered.

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: 103.0.5060.114
* Operating system and version:  macOS 12.6
* NodeJS version used (if relevant):  16.17.0
* Kedro version used (if relevant): 0.18.3
* Python version used (if relevant): 3.7

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by DrDaDe** [comment]
As author of #1036, I can reproduce the observation that the initial view is incorrect but becomes correct when expanding and recollapsing.


As has been suspected in this ticket, the yet to be identified reason for this minor bug might cause further bugs. 

Indeed, in my actual working project I still observe problems with sub-pipeline nodes not properly connected in kedro-viz (but properly used in kedro run) and these connections are _still missing_ if the corresponding pipelines are expanded and re-collapsed. Unfortunately, this project has a far too big and intertwined pipeline structure to boil it down to a minimal working example - I will attempt to construct one.

In any event, I am still interested in finding a proper solution to this bug because even with recent release 5.2.0, I cannot use sub-pipelines in my project.

**Comment by DrDaDe** [comment]
Update: I have checked and I believe all my problems that still remain are a combination of this issue (which disappears if the overall pipeline is collapsed and re-expaned) and another issue of disconnected nodes which has already been identified by other users e.g. in #1105 .

I provided a minimal working example there and I hope that this will help to find a simple solution to this.

**Comment by tynandebold** [comment]
Thanks a ton for that example, @DrDaDe. Your contributions have been so helpful.

We're aiming to take a larger look at modular pipelines soon, and we hope to fix this issue within the scope of that work.

**Comment by noklam** [comment]
Link this thread which came up recently. 
https://www.linen.dev/s/kedro/t/12969378/hi-all-i-get-this-weird-bug-with-kedro-viz-i-have-this-set-o
