### ISSUE TITLE
Polish and finish exp. tracking metric plots prototype

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#1130]
Highest level: prepare final assets for engineering.

@Mackay031 to add a list of must-have and nice-to-have functionalities for the plots.

**Comment by comym** [comment]
As shown in the meeting this morning, we've published the latest in the Design OUT Figma file.

Single mode:

https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=1931%3A58898

Comparison mode:

https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=1932%3A101707

**Comment by comym** [comment]
What we're working on now is to include and republish the same with:

- How do the new selection indicators work on comparison mode when in the Overview tab?
- We're writing text descriptions of the interactions.
- We're preparing a moving image example of the hover interaction showing the delayed tooltip behaviour.

**Comment by comym** [comment]
An example of the Overview page in comparison mode was added.

![Image](https://user-images.githubusercontent.com/55446576/198356653-62a03910-8151-4f96-a5d7-e22d822b961b.jpg)

**Comment by comym** [comment]
@Mackay031 is putting a little prototype example of the hover interaction and tooltip delay.
For reference.

https://www.figma.com/proto/K8WJMMTkvFHn6OZYg7Ypfz/Kedro-Design%3A-IN?page-id=5744%3A27639&node-id=5743%3A29183&viewport=661%2C973%2C0.81&scaling=min-zoom&starting-point-node-id=5743%3A28963

**Comment by comym** [comment]
Hi,

Just to let you know the Design OUT Figma board is now updated with the text description of each step in the journey.

Please let me know if you have any questions. @rashidakanchwala @tynandebold 

Thanks



![Image](https://user-images.githubusercontent.com/55446576/199294105-9fc02045-2dab-4f21-8360-b06847643ae5.jpg)


![Image](https://user-images.githubusercontent.com/55446576/199294177-4f88ce91-d131-4202-afe3-46d90d5d3522.jpg)
