### ISSUE TITLE
Check if Plotly can cater to all must-have features for Exp. Tracking Metric Plots. 

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1137]
## Description

This is a ticket to test if all the must-have features required by design for Metrics Plot and Parellel Coordinates can be done via plotly. 

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
We're not going to use Plotly to build this feature, so I'll close this issue.
