### ISSUE TITLE
Finish the parallel coordinates metrics plot

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#1146]
Things still to do (some taken from comments in #1152):

**Must complete:**

- [x] When runs are selected, the runs list card needs to show the same shapes as the lines on the metrics chart (diamond, circle, triangle).
- [x] Highlighted run lines should always appear on top of everything else.
- [x] When hovering over a run line, the plot highlights some random values across different metrics and positions. This should not happen. Only the related values to the on-hover run should show. 
- [x] Very long metric axis labels aren't displaying nicely. We need to break them to two lines or cap them at a character limit.
- [x] Limit the number of runs when viewing metrics plots so we don't impact performance too much.

**Nice to complete:**

- [ ] Overlapping metric value labels. No known solution for this at this time. Perhaps better highlighting on hover.
- [x] When hovering over a metric name, the current build only highlights the axis line and some values. This is right but this is also only one of the changes that should occur in this interaction. What we're missing here is to knock back (decrease in contrast) all the other metric columns that are not being highlighted, so that the highlighted one can pop to the front. Also in this state, we knock back many of the other lines and labels. Basically eliminating all the unnecessary noise at that point. See the design for reference.
    - Note: we may forgo this for the initial release.

**Comment by NeroOkwa** [comment]
Signed-off-by: Nero [nero_okwa@mckinsey.com](mailto:nero_okwa@mckinsey.com)

Hello, I have tested both the ‘Must complete’ and ‘Nice to complete’ features and they perform as required and solve the user’s pain point of providing an overview to see and compare how metrics perform over time across different runs.

Below are brief observations:

- In single run view: It isn’t clear what the bookmark runs (in runs list) use case is vs clicking to select the run
- In comparison view: It is very clear that you bookmark a run - which moves to the top as reference, and select 1-2 other runs for comparison.
- In comparison view: The different colours and shapes of each run across different metrics is very helpful for comparison
