### ISSUE TITLE
Experiment Tracking - allow users to prettify the metrics values on Overview tab

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-viz#1167]
## Context
This feature request is an output from the experiment tracking User Testing Synthesis [#1627](https://github.com/kedro-org/kedro/issues/1627#top)

User wishes to be able to prettify the metrics values to X decimal points (instead of having a long decimal number). This would help with comparison in plots. 

This would be applicable to both metric plots and overview metrics. 

We should explore different ways we can avoid customisation. e.g. prettify the values anyway and show the actual value on hover as tooltip. 

## Supporting quotes
“One is if possible to allow the user to choose how they want metrics to be displayed in terms of like formats, like do they want it to be a percentage? Do they want it to have a lot of digits? Just a few digits ? always defaulting to a decimal of five digits can be pretty overwhelming”

**Comment by tynandebold** [comment]
Closing for now. We'll reopen this ticket if we look at this again downstream.
