### ISSUE TITLE
Experiment Tracking - Time Series Plots - Build zoom functionalities

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-viz#1168]
## Context
This feature request is an output from the experiment tracking User Testing Synthesis [#1627](https://github.com/kedro-org/kedro/issues/1627#top). User wishes to be able to perform 3 different zoom functionalities for further investigations in plots. 

This is important for focusing a part of the plot across the screen, and using the shift scroll functionality to quickly move to the end of the plot.

## Supporting quotes
“Ability to zoom in and out in the graphs to show more of a specific period." 

“If this goes on and on to the right or to the left, I would expect to be able to shift scroll to go to the right, and to the left. So basically the three scroll functionalities, the normal scroll, the control, and the shift.”

**Comment by tynandebold** [comment]
Implemented via #1191
