### ISSUE TITLE
Design Time Series and Parallel Coordinates light theme version

### ISSUE THREAD

**Issue by comym** [kedro-org/kedro-viz#1173]
We need to output a light theme version for the time series and parallel coordinates plots.
Revisit colours and contrast ratios.

**Comment by comym** [comment]
I've just [exported the light theme references ](https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=2342%3A102635&t=zR1Cyj7hWUc0nSEv-1)for all "right side of the screen" experiment track tabs.



![Image](https://user-images.githubusercontent.com/55446576/203803809-55580a9a-beb1-476f-ad87-c0070f71fbd9.png)



Please have look when you have time @tynandebold 

I'm happy to go over it tomorrow during the demo session if we have any time.

Please note that for the time series plots I'm only showing one metric plot as an example only. They all should follow the same style and behavior. All the other stacked metric plots are blurred. That means this is a layout example for styling purposes only. 

Here you have examples of:

- Single and comparison modes for both time series and parallel coordinates- various states
- Extra bits like Overview comparison mode header and examples of the run list selected cards.

Note we went full-on white in the background for allowing us to have more contrast between the elements.

Temporarily the flowchart section will end up having a different background - slightly darker - however we'll be reworking the whole light theme and aligning everything.

Also, the challenges we're facing on the dark theme will be the same on the light version. Readability, contrasts, overlapping, etc. We'll cover all that as we go.

For now, we believe this to be a good reference for styling.

Many thanks

**Comment by tynandebold** [comment]
I think it looks great and is approved from my side 🎉 no comments or suggestions after just going through the designs. If anything comes up while implementing I'll be sure to ping you.
