### ISSUE TITLE
Finish and hand off designs for blog.kedro.org

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#1177]

**Comment by Mackay031** [comment]
<img width="963" alt="Screenshot 2022-12-19 at 15 24 08" src="https://user-images.githubusercontent.com/102358798/208460128-e32c8108-51ba-4d12-adde-d7081589f671.png">

Hi, here is the link to the blog designs. in the Flow section we have the 'Primary flow', 'Mobile' and 'Primary Flow on wider screens' flows. https://www.figma.com/file/e2FveRnPmCidpGnuyTWbGj/Kedro-Blog-Ideas?node-id=8%3A51336&t=6SadiLrDk92oNd4f-1

Ignore the prototype section. The prototypes are a bit glitchy so I have create one in After Effects. Here is the link: https://mckinsey.box.com/s/sttypdkgoy26o0r4qzj5bm6u1ir1blv5. I am thinking we could add page load animations to create a bit of interest. I have added some little 'hover response' on the images. Obviously a nice to have, but with such a simple Blog design, I think it would be nice to have the subtle micro animations/movement to add to the design. WDYT? We can discuss.

**Comment by tynandebold** [comment]
Looks great. I think this will work well. No real questions from me at this time!
