### ISSUE TITLE
Long load/auto-reload time for bigger projects

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-viz#1183]
## Context
This feature request is an output from the Kedro-Viz adoption synthesis [#987](https://github.com/kedro-org/kedro-viz/issues/987)

When doing bigger kedro projects, user wish to have a quicker load/auto-reload time of Kedro-viz to be able to easily present the data to stakeholders from Kedro-Viz. 

## Supporting quotes
- “I would want to pull it up and it, and I don't know if this has been resolved since then, but it would take quite a substantial amount of time, to be able to pull up and the auto reload didn't always work as quickly or as responsibly as if you wanted to see something in real time... It felt slow, like we were waiting a little too much”. 
- “The startup times on bigger projects can be, sometimes when you're in a meeting and you want to  bring it up quickly, it takes some time to load, but nothing critical”
   - “The subjective perception is is that for projects with multiple pipelines and multiple modular pipelines, it feels longer than for smaller, like for space light for example”.

**Comment by tynandebold** [comment]
The startup time was improved in #1196. 

@NeroOkwa can we please go back to these users and get them to test out their project where they saw this issue with the newest version of Viz?

**Comment by tynandebold** [comment]
Closing as we did improve the startup time.
