### ISSUE TITLE
Add delta (number & percentage) to the overview metrics tab for metric comparison

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1184]
## Description

Additional to the up and down arrows (that show if metric value is low or high compared to selected metric), also show delta (number & percentage) so the users can see how much high/low the value is. 

<img width="922" alt="Screenshot 2022-11-28 at 10 40 26" src="https://user-images.githubusercontent.com/37628668/204258889-3937713a-e707-405c-8d34-071297373f10.png">

## Context
Provide users with more information to help them compare their metrics 

## Possible Implementation
Add a delta percentage value next to the arrows. 

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by Mackay031** [comment]
Hey @rashidakanchwala , was just thinking about this one. 

I played with a couple of iterations. Firstly just looking at percentages:

- **(1.2)** I made the percentage the same colour as the arrow to allow for easier scanability. I feel keeping them the same colour groups them better
- **(1.3)** Then I thought, would it be better to include the Delta symbol to be more explicit as to what we are looking at
- **(1.4)** Then I felt it was a lot of info to read (all in the same blue), so what if we used to shades of blue to keep important number/arrow highlighted

All the same for numbers/percentages as above

What do you think? @rashidakanchwala @comym 

![Show delta values in percentages](https://user-images.githubusercontent.com/102358798/218533754-48561505-4182-4fa9-bbcc-80bdeddaa370.png)

ps, did this quickly so used the same values and didnt show any negative deltas.

**Comment by Mackay031** [comment]
Hi Rashida. I have discussed with @comym and we think ver2.2 is the best option. Less clutter and easier to read. We have both number and percentage.

**Comment by rashidakanchwala** [comment]
Cool, we are going with 2.2 then.
