### ISSUE TITLE
Make Kedro-Viz work with `kedro-datasets`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-viz#1205]
## Description
From Kedro `0.18.4` we’re using datasets from `kedro-datasets` and so the import paths are different. `kedro_datasets.plotly.PlotlyDataSet` instead of `kedro.extras.datasets.plotly.plotly_dataset.PlotlyDataSet` etc. If a user is using Kedro `0.18.4` with `kedro-datasets` viz doesn't detect plot datasets correctly, experiment tracking doesn't work and other things where paths have been hard-coded in viz. 

## Context
We need to make Kedro viz support `kedro-datasets` and keep it compatible with using datasets from Kedro itself at least for the 5.x series. Perhaps in 6.0 we’d want to remove compatibility with datasets inside kedro

**Comment by tynandebold** [comment]
This ticket will focus on fixing this specific issue in a way that isn't too generic.
