### ISSUE TITLE
Build Kedro Blog with contentful

### ISSUE THREAD

**Issue by Huongg** [kedro-org/kedro-viz#1212]
## Description
Build a kedro blog section on the kedro website with the latest design from [here](https://www.figma.com/file/e2FveRnPmCidpGnuyTWbGj/Kedro-Blog-Ideas?node-id=8%3A51336&t=SGLetVjEIc976mnk-0)

## Possible Implementation
Tech stack:
Contentful for CMS. More discussion can be found [here](https://github.com/kedro-org/kedro-website/issues/61)
React/Next.js for the FE

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
Closing and creating a more detailed ticket [here](https://github.com/kedro-org/kedro-website/issues).
