### ISSUE TITLE
Investigate how to store all experiment tracking data in SQLite for Kedro-Viz 

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-viz#1221]
This is an outcome ticket from the Technical Design session of [Allow users to write experiments to a remote server kedro-org/kedro-viz#1218](https://github.com/kedro-org/kedro-viz/issues/1218)

## Description
This is concerned with storing all experiment tracking data (shared data storage) in `SQLite` in other to make sharing of experimental runs easier, and faster filtering of runs https://github.com/kedro-org/kedro-viz/issues/1039.

**Comment by tynandebold** [comment]
Closing this as we now have direction, as seen in https://github.com/kedro-org/kedro-viz/issues/1295.
