### ISSUE TITLE
Fix run suggestion in metadata panel to include namespace

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro-viz#1225]
## Description
The metadata panel will suggest a run command when a node in the pipeline is suggested. However, if the node is within a namespace, this suggestion will not work.

Important note: The formatting of the command is also inconsistent with other Kedro resources. As a result of https://github.com/kedro-org/kedro/issues/2014 command suggestions should now follow the format `kedro <command> --<flag>=value1,value2`.

## Steps to Reproduce

1. Run `kedro run` on a new spaceflights project
2. Run `kedro viz`
3. Open metadata panel
<img width="401" alt="Screenshot 2023-01-19 at 16 03 10" src="https://user-images.githubusercontent.com/90615669/213492918-652385e8-82f3-4058-bbda-239c6f93a07a.png">

4. Run the suggestion under "Run Command:"

## Expected Result
The pipeline should run until the specified node.

## Actual Result
The pipeline throws an error.

```
ValueError: Pipeline does not contain nodes named ['split_data_node']. Did you mean: 
['data_science.active_modelling_pipeline.split_data_node', 
'data_science.candidate_modelling_pipeline.split_data_node']?
```

## Your Environment
Kedro version: 0.18.4
Kedro Viz version: 5.2.0

**Comment by tynandebold** [comment]
Triage assessment: looks like we need to update `package/kedro_viz/models/flowchart.py`.
