### ISSUE TITLE
KedroCliError raised on launching Viz with certain datasets.

### ISSUE THREAD

**Issue by jmholzer** [kedro-org/kedro-viz#1226]
## Description
Running Viz can cause an error on launch when certain datasets are included in the pipeline:

```
kedro.framework.cli.utils.KedroCliError: not enough values to unpack (expected 3, got 1)
Run with --verbose to see the full exception
Error: not enough values to unpack (expected 3, got 1)
```

An initial investigation shows that it's either (or both) _get_dataset_type (flowchart.py) or get_dataset_type (experiment_tracking.py ) that could be causing the issue.

## Context

This stops users launching Viz and is high priority.

**Comment by tynandebold** [comment]
Thank you for looking into this. Let me know if I can help in any way.
