### ISSUE TITLE
PyPI sdists are not self-contained

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-viz#1267]
## Description
As per title. The reason is that `package.json` and `README.md` are not included in the sdist.

## Context
I was trying to add kedro-viz to conda-forge, picking up on https://github.com/conda-forge/staged-recipes/pull/21441.

## Steps to Reproduce

```
$ pip install "kedro-viz==5.3.0" --no-binary :all:
Collecting kedro-viz==5.3.0
  Downloading kedro-viz-5.3.0.tar.gz (5.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 81.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-w73ekeu9/kedro-viz_74c1ed35d82c47aa8afa50b9d1762ce6/setup.py", line 20, in <module>
          with open(path.join(here, path.pardir, "package.json")) as data:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-w73ekeu9/kedro-viz_74c1ed35d82c47aa8afa50b9d1762ce6/../package.json'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the '/tmp/kedro-viz-5.3.0/.venv/bin/python3 -m pip install --upgrade pip' command.
```

## Expected Result
Installing from a PyPI sdist should work.

## Actual Result
Trying to install from a PyPI sdist gave an immediate error.

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Operating system and version: macOS Ventura and Linux

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by astrojuanlu** [comment]
Essentially a continuation of gh-1028.

**Comment by astrojuanlu** [comment]
This also means that installing a development version from GitHub doesn't work:

```
pip install "kedro-viz @ git+https://github.com/kedro-org/kedro-viz@test-s3-on-exp#subdirectory=package"
```

this will properly install the Python files, but not perform a `make build` and hence not create the `static` HTML directory.

**Comment by astrojuanlu** [comment]
Recommendations from the Python Packaging forum https://discuss.python.org/t/best-practices-for-packaging-python-javascript-projects/27047?u=astrojuanlu

- Bundle the JS files in the sdist (this issue). Examples: Bokeh, Jupyter
- Adopt a more sophisticated build backend (either Hatch or a custom subclass of Flit) that allows git installations. Examples: hatch-jupyter-builder

The former can be done without the latter, I'd say (although it would be nice to do both).

**Comment by astrojuanlu** [comment]
Given that the workflow is designed with NodeJS 16 in mind, which is a bit old, it would be easier (both on the kedro-viz side and downstream) to go for the first option and bundle the JS files with the sdist.

**Comment by rxm7706** [comment]
This open issue here, could be the master to address all pypi distribution related fixes needed.

Linking Relevant comments & threads. 
https://github.com/conda-forge/staged-recipes/pull/21441#issuecomment-1681325333
https://github.com/conda-forge/staged-recipes/pull/21441#issuecomment-1675912454
Solution for conda packaging. 
https://github.com/conda-forge/staged-recipes/pull/21441
