### ISSUE TITLE
Download to SVG broken 

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-viz#1290]
## Description
I downloaded a pipeline using the SVG option from the demo and found this: 

![Screenshot 2023-03-21 at 13 57 19](https://user-images.githubusercontent.com/43755008/226628919-b14436da-6559-4764-a9d8-400bbe228200.png)

**Comment by tynandebold** [comment]
How did you open this SVG?

It works fine for me: 

![image](https://user-images.githubusercontent.com/16869061/226639215-b9fdf2b7-786b-4376-8031-4d3a41ef7625.png)

**Comment by yetudada** [comment]
Ah, that's weird. I brought it into Microsoft Powerpoint and SVGs normally work there.

**Comment by tynandebold** [comment]
Could you check your downloaded file with this tool please? https://svg.enshrined.co.uk/

You can paste the SVG code, click `Sanitize`, and then see what comes out.

It worked fine for my downloaded SVG file.

**Comment by tynandebold** [comment]
Going to close this, as @rashidakanchwala confirmed she downloaded and previewed the SVG without issue.
