### ISSUE TITLE
Improve search wording for Demo of Kedro-Viz on Google Search

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-viz#1292]
## Description
I googled Kedro-Viz and saw the following for the demo of Kedro-Viz. I'm wondering if it could be changed to indicate that this is the demo site for Kedro-Viz. 

![Screenshot 2023-03-22 at 10 15 00](https://user-images.githubusercontent.com/43755008/226872902-8eb6f806-0c33-4dea-9e53-81d761505530.png)

**Comment by tynandebold** [comment]
Confirming this change was successful:

<img width="889" alt="image" src="https://github.com/kedro-org/kedro-viz/assets/16869061/e986cbcb-07bf-4136-a97a-55477f72aa95">
