### ISSUE TITLE
Select Metrics for Visualization in Parallel Coordinates

### ISSUE THREAD

**Issue by azachar** [kedro-org/kedro-viz#1294]
## Description
Currently, in Kedro, all metrics are displayed in parallel coordinates, which can make the visualization cluttered and difficult to interpret. This feature request is aimed at allowing users to select which metrics to display in the visualization, making it easier to focus on the most relevant metrics and gain deeper insights into the data.

## Context
As a Kedro user, I work with complex datasets and often need to visualize high-dimensional data using parallel coordinates. However, when there are many metrics, the visualization becomes difficult to interpret. With this feature, I could select the most relevant metrics to display and create clearer, more informative visualizations. Additionally, this feature would benefit other Kedro users who work with complex data and need to create clear and informative visualizations.

**Comment by tynandebold** [comment]
Thank you for raising this, @azachar!

If you wouldn't mind, could you please post a screenshot of what your parallel coordinates view looks like? I'm curious to see how difficult to interpret the visualization is. This information will also aid our design team by providing valuable user context to the problem.

(Loosely related to #1166)

**Comment by azachar** [comment]
Yes, I did ;)
