### ISSUE TITLE
Delete unwanted Experiment Tracking runs

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#1298]
## Description

Users have asked for the ability to delete runs in experiment tracking.

Evidence:

- https://kedro-org.slack.com/archives/C03RKP2LW64/p1676975171634649
- https://kedro-org.slack.com/archives/C03RKP2LW64/p1674035483567479
- https://quantumblack.slack.com/archives/C7JTFSFUY/p1654053467465859

## Context

People will be able to declutter their experiment tracking view.

## Implementation

Note Antony's comment below.

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by AntonyMilneQB** [comment]
Note that according to collaborative experiment tracking view, the way to delete a run won't actually be to delete the row from the database. It will appear like that to the user, but actually clicking the delete button will actually do is add a new row to the database with some `deleted` flag set to True, and then we'll filter those rows out.

**Comment by tynandebold** [comment]
Yes indeed, we're aware, and the same was discussed in backlog grooming earlier this week. Thank you for writing it here. It'll be a useful reminder when this is implemented.

**Comment by tynandebold** [comment]
We'll reopen this ticket if we look at this again downstream.
