### ISSUE TITLE
Show unpretty input/output names in node details

### ISSUE THREAD

**Issue by drtorchwood** [kedro-org/kedro-viz#1312]
This is just an improvement idea for the details that are shown when a node is selected. 

At the moment, independent of the "Pretty names" option, the input and output nodes are always shown with a prettified name. This is inconvenient if I want to copy the name of a dataset from kedro-viz into the code - especially if the dataset is far away in the graph and I cannot click on it easily. 
I would propose that the option "Pretty names" also effect the details given in a node. 
![image](https://user-images.githubusercontent.com/57524623/229748736-8432233e-39ac-46d8-9c18-19e10286ade2.png)
In this example, the real names of the datasets are "stage3_out" and "data_last_year" but only the pretty names are shown.

**Comment by tynandebold** [comment]
Thanks for this suggestion, @drtorchwood. I agree with you. We'll work on it and let you know when it's been released.

**Comment by tynandebold** [comment]
This isn't as easy as I thought it would be. This data comes from the `api/nodes/:nodeId` endpoint, so we'll need some way to discern if the user has `Pretty name` on or off. It's not clear to me how we'll know that unless we pass it to the endpoint.

**Comment by tynandebold** [comment]
@drtorchwood we just merged a PR for this change and it'll be out shortly! Thank you for the suggestion.
