### ISSUE TITLE
Figure out a way for users to expand the code block to contents

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-viz#1321]
## Description
Users have to scroll to see the full code block and it's sometimes not obvious (on Mac) that you need to do this. We should think of a way to make it easy to see the entire code block. 

<img width="1438" alt="Screenshot 2023-04-18 at 15 20 48" src="https://user-images.githubusercontent.com/43755008/232807301-fcd3f100-3343-4401-8b35-f5815e677ebc.png">

**Comment by tynandebold** [comment]
Quick win: the code block should expand to fill the entire width of the flowchart, up to the utility bar.

**Comment by tynandebold** [comment]
Like this: 

![image](https://github.com/kedro-org/kedro-viz/assets/16869061/04a8435a-f152-408e-a0f7-86b5e65179a9)
