### ISSUE TITLE
Rebrand: Create GitHub assets

### ISSUE THREAD

**Issue by Mackay031** [kedro-org/kedro-viz#1336]
## Kedro
Usage: https://github.com/kedro-org/kedro#readme

- [x] Messaging: update messaging on what Kedro is on README.md
- [ ] Messaging: update slogan on "About" section of page
- [x] Icon: update https://raw.githubusercontent.com/kedro-org/kedro/develop/static/img/kedro_banner.png
- [x] Image: update Kedro-Viz in computer https://github.com/kedro-org/kedro-viz/blob/main/.github/img/banner.png

## Social preview image

- [x] Create image 
Requirements: Images should be at least 640×320px (1280×640px for best display).
Template: https://github.com/kedro-org/kedro/settings/og-template

## Icon on Jupyter kernel:

- [x] Update  32 icon 
https://github.com/kedro-org/kedro/blob/main/kedro/ipython/logo-32x32.png
- [x] Update  64 icon 
https://github.com/kedro-org/kedro/blob/main/kedro/ipython/logo-64x64.png

PR: https://github.com/kedro-org/kedro/pull/2651/files

## Awesome-Kedro
Usage: https://github.com/kedro-org/awesome-kedro

- [x] Update icon 
https://github.com/kedro-org/awesome-kedro/blob/master/kedro_icon_no-type_whitebg.svg
- [x] Create Social Preview image
Requirements: Images should be at least 640×320px (1280×640px for best display).
Template: https://github.com/kedro-org/kedro/settings/og-template

## Kedro-viz
- [x] Update image of Kedro-Viz in computer
https://github.com/kedro-org/kedro-viz/blob/main/.github/img/banner.png
- [x] Create Social Preview image
Requirements: Images should be at least 640×320px (1280×640px for best display).
Template: https://github.com/kedro-org/kedro/settings/og-template

## GitHub account image
- [x] Create image 
https://github.com/organizations/kedro-org/settings/profile

**Comment by yetudada** [comment]
![repository-open-graph-template (2)](https://github.com/kedro-org/kedro-viz/assets/43755008/f836226c-8563-44d3-9588-ee3b6247c592)

**Comment by yetudada** [comment]
Social preview images for: 

- Kedro
- Kedro-Viz
- Awesome-Kedro
