### ISSUE TITLE
Rebrand: Create social media images, icons & banners  (Fediverse, Mastadon, Twitter, LinkedIn)

### ISSUE THREAD

**Issue by Mackay031** [kedro-org/kedro-viz#1339]
LinkedIn

- [ ] Update website preview when website is linked

Twitter

- [ ] Update website preview when website is linked

Mastadon
Usage: https://social.lfx.dev/@kedro

- [ ] Crate Icon
- [ ] Crate Banner

Fediverse
Usage:

- [ ] Crate Icon
- [ ] Crate Banner

**Comment by astrojuanlu** [comment]
At the moment we only have [Mastodon](https://social.lfx.dev/@kedro) and [YouTube](https://www.youtube.com/@kedro-data)

**Comment by astrojuanlu** [comment]
Dev.to:

![image](https://github.com/kedro-org/kedro-viz/assets/316517/4ba10634-19c3-452f-810f-a3cc2d48ee3c)

**Comment by astrojuanlu** [comment]
Closing for tracking purposes.

**Comment by astrojuanlu** [comment]
Better now:

![image](https://github.com/kedro-org/kedro-viz/assets/316517/0035228d-a0a9-40bc-85f6-6c50c5bdefd6)
