### ISSUE TITLE
Rebrand: Create LF AI & Data Landscape assets

### ISSUE THREAD

**Issue by Mackay031** [kedro-org/kedro-viz#1340]
How it's used: https://landscape.lfai.foundation/?selected=kedro
Where to update it: https://github.com/lfai/lfai-landscape/blob/main/cached_logos/kedro.svg
Requirements for the logo: https://github.com/lfai/lfai-landscape#logos

## Tasks

- [x] Create assets that adhere to guidelines 
- [x] Replace existing assets on LF GitHub

**Comment by yetudada** [comment]
I'm busy waiting for the Netlify preview: https://github.com/lfai/lfai-landscape/pull/567

I'm also updating the QuantumBlack icon too.
