### ISSUE TITLE
Update figma to reflect all the changes for Kedro UI rebranding

### ISSUE THREAD

**Issue by Huongg** [kedro-org/kedro-viz#1364]
## Description
Related to the changes from [the PR ](https://github.com/kedro-org/kedro-viz/pull/1359)to update Kedro UI colour branding for light and dark theme, there have been some changes while in development but it has updated yet on the Figma files

## Context
Why is this change important to you? 
To ensure that any future development or any new joiners to the team can have access to the most up to date design files

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
@stephkaiser can you please link the new Figma file here? I'll close this issue now, since you've completed this task.
