### ISSUE TITLE
Collaborative experiment tracking v2.0 - Auto-reload

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1369]
## Description
This version of experiment tracking focuses on enabling auto-reload for Kedro-viz, ensuring that it automatically updates whenever a new experiment is added to the session_store.

## Context
Currently, if new experiments are added to the session_store.db while the user is running Kedro-viz, the user can only view these experiments by terminating the current visualization and running kedro-viz again.

With the new implementation, auto-reload functionality will be enabled. Kedro-viz will continuously monitor the cloud storage for any new experiments added to any of the session_store.dbs. If it detects any new experiments, it will automatically load them in the same Kedro-viz session.

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
We'll reopen this ticket if we look at this again downstream.
