### ISSUE TITLE
Improving testing on Kedro-viz

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1372]
## Description

This is  spike ticket to identify missing tests (mostly intergration and e2e testing) and create a test plan to make testing better on Kedro-viz. 

## Output 

To create a series of tickets describing what tests need to be written. 

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
Let's ensure to reference the content in #805 when doing this spike.
