### ISSUE TITLE
Document the schema for the input JSON file

### ISSUE THREAD

**Issue by mostaphaRoudsari** [kedro-org/kedro-viz#1390]
## Description + Context

I'm interested to use the kedro-viz viewer to visualize simulation pipelines that are created in a different framework and not Kedro. I was able to hack an example together about two years ago based on the samples in the sample data here (https://github.com/kedro-org/kedro-viz/tree/main/src/utils/data) but I'm hoping for better documentation of the JSON schema that is consumed by kedro-viz.

![daylight-factor-viz-kedro-lr](https://github.com/kedro-org/kedro-viz/assets/2915573/7a958937-52f5-4b0b-9316-cd2914ccc02b)

Sorry if there is one and I missed it! I searched when I was trying to create the sample, and I also did a quick search right now but I couldn't find anything.

## Possible Implementation

There are several tools for this purpose and we use Pydantic for our work but any other tool or workflow that can generate a JSON Schema documentation will be very useful.

**Comment by tynandebold** [comment]
Hey @mostaphaRoudsari thank you for the question. I think we have something that will help you, which you can find here: https://demo.kedro.org/docs#/default/main_api_main_get.

We have Swagger autogenerating our REST API documentation, and I think that's what you're looking for.

<img width="1442" alt="image" src="https://github.com/kedro-org/kedro-viz/assets/16869061/13cd759a-95ab-4584-ae59-44160452e397">

Let me know if that helps and solves your query!

**Comment by mostaphaRoudsari** [comment]
Yes. That is what I was looking for. Thank you for the quick response.
