### ISSUE TITLE
Creating user flows for FE e2e testing

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1391]
## Description

Based on the spike ticket for front-end testing, we have concluded that although our unit tests are good, they are not comprehensive nor do they give us the assurance that the app will run smoothly. Hence, we will now also be doing end-to-end (e2e) testing using a framework (TBD - Cypress, or Playwright or ...) .

This ticket involves writing user flows for the front-end. It is not an engineering ticket, as developers working on the code may be biased towards testing. The product manager will be responsible for writing the user flows.

Some examples of user flows include:

- When a user clicks on a node, the metadata panel opens.
- When a user clicks on focus mode, the flowchart displays only the focused modular pipeline.
And so on.

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
My recommendation for a testing framework is Cypress. It should handle all our use cases.

**Comment by NeroOkwa** [comment]
Here are the user flows: [BOX](https://mckinsey.box.com/s/ms92s1o3kcuguvu78aogf8dl77e6qszi).

**Comment by tynandebold** [comment]
Looks great, Nero. Thank you very much for this. I've left a couple of comments. Overall is approved from my side.

I would say that I think we should link some of these flows together to create effectively a story that would track what a user does while interacting with Viz. As you've written it now, they're like sentences, and I think we should have whole paragraphs. Something like: load the page -> search in the sidebar -> click the found node on the flowchart -> see that node in the metadata panel -> open the code panel in the metadata panel.

**Comment by NeroOkwa** [comment]
Thanks @tynandebold. I have implemented all the comments and also added test for Plotly/Matplotlib, R2 score, and an error message for an empty flowchart.

Definitely! linked user stories will provide more insight on different user journeys within Kedro-Viz.
