### ISSUE TITLE
Setup e2e testing in FE 

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1392]
## Description

This ticket involves the below tasks 

- [ ] Finalise e2e testing tool.
- [ ] Set up the chosen testing framework on Kedro-viz and configure the initial test.
- [ ] Provide a brief tutorial to the team on writing e2e tests, including codeless tools if applicable, and communicate any team norms to follow for e2e testing.
- [ ] Update the information on the Contribution readme.

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
This ticket is blocked by #1391 and should be started after that ticket is completed and we have an agreed upon set of user flows to test.
