### ISSUE TITLE
Edit the banner image in Kedro docs

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-viz#1393]
There's too much whitespace in the docs with the new logo. We need to crop it out for the docs build.
From this

<img width="1174" alt="Screenshot 2023-06-08 at 13 27 39" src="https://github.com/kedro-org/kedro/assets/5180475/ebdb5f97-b814-4e08-ba47-7fb19464ced5">

To this
![kedro-docs](https://github.com/kedro-org/kedro/assets/5180475/e2087d8e-b859-40b6-bce6-724154ad1cae)

**Comment by tynandebold** [comment]
The asset for the image is here: https://raw.githubusercontent.com/kedro-org/kedro/main/static/img/kedro_banner.png

**Comment by yetudada** [comment]
I have an additional requirement for this. Can we additionally make the GitHub banner light/dark theme responsive? To do this we need: 
- A banner with white Kedro text for the logo
- To follow these instructions: https://dev.to/mateusabelli/make-images-responsive-to-lightdark-mode-on-github-3gbg
- And we'll still point our docs to the banner that @tynandebold uploaded

**Comment by Mackay031** [comment]
How about these?

![kedro_banner_dark png](https://github.com/kedro-org/kedro-viz/assets/102358798/b1a43cb3-9755-4ae3-8840-752f2ebdaf4e)
![kedro_banner_light png](https://github.com/kedro-org/kedro-viz/assets/102358798/b2c0fe5e-e4a6-4289-9970-8d35ec08f65a)
ps. they are on transparent backgrounds. I assume this is ok? I made images 340px in height, down from 600px.

**Comment by Mackay031** [comment]
Just something else I noticed in 'API Documentation section'.
<img width="479" alt="Screenshot 2023-06-13 at 23 15 49" src="https://github.com/kedro-org/kedro-viz/assets/102358798/059c16ce-8aac-4bd0-accf-31d2028b120f">
 Should be capital 'K' in Kedro for consistency

**Comment by astrojuanlu** [comment]
Those are Python package names (as in `import kedro_datasets`) so they're case sensitive and must be lowercase, maybe we should use a monospaced font to make it more clear?

**Comment by Mackay031** [comment]
Ok, got it. Yes, maybe a monospaced font would help differentiate and therefor, not look out of place :)
