### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-viz#1446]
Requires a new Kedro release that includes https://github.com/kedro-org/kedro/pull/2742 (already merged)

See also https://github.com/kedro-org/kedro-plugins/issues/265, https://github.com/kedro-org/kedro/issues/2270

**Comment by juanoi** [comment]
Hi guys, any idea when the new release will be made?

**Comment by tynandebold** [comment]
Hey @juanoi! Probably sometime in the next couple of weeks.

**Comment by tynandebold** [comment]
Track the progress of the Kedro framework work on this same topic here: https://github.com/kedro-org/kedro/pull/2851/

**Comment by noklam** [comment]
Saw the mentions in Kedro repo, it worth to mention that Kedro is now open-bound (we don't set upper bound now, so in theory Python 3.12 is out, anyone could install it immediately). We will still declare a official support of newer version, but it's up to the user.
