### ISSUE TITLE
Blank page when clicking modular pipeline in safari

### ISSUE THREAD

**Issue by jccalvojackson** [kedro-org/kedro-viz#1462]
## Description

If you go to the [demo](https://demo.kedro.org) using safari and start clicking modular pipeline (expand) and then collapse soon enough you’ll get a blank page. The error shown upon inspect element is

<img width="747" alt="Screenshot 2023-07-25 at 10 06 24" src="https://github.com/kedro-org/kedro-viz/assets/48832149/d23d99a4-2e49-4d9e-9ab2-da4614a985c1">

Is this expected? do I need to disable some security restrictions in safari?

This does not happen if I use chrome.

## Context
Using kedro viz with safari

## Steps to Reproduce

1. go to  [demo](https://demo.kedro.org) with a safari browser
2. Start clicking on modular pipelines to expand them and then click on the sidebar to collapse them.
3. After a few of the above iterations it will lead to a blank page. The number of tries varies.

## Expected Result
No blank page.

## Actual Result
Blank page

```
[Error] Unhandled Promise Rejection: Not implemented on this platform
	(anonymous function)
	rejectPromise
	reject
	(anonymous function) (content-script.js:80:512483)
	n (content-script.js:80:115)
	(anonymous function) (content-script.js:80:906)
	Global Code (content-script.js:80:915)
[Error] Not allowed to load local resource: blob://nullhttps//demo.kedro.org/6884266bbbc3163423d0.worker.js.map
[Error] Not allowed to request resource
[Error] Cannot load blob://nullhttps//demo.kedro.org/6884266bbbc3163423d0.worker.js.map due to access control checks.
[Error] TypeError: undefined is not an object (evaluating 'e.sourceNode') — draw.js:415
	cs (2.22c54680.chunk.js:2:4175868)
	(anonymous function) (2.22c54680.chunk.js:2:4177989)
	pa (2.22c54680.chunk.js:2:4141805)
	ms (2.22c54680.chunk.js:2:4179700)
	Il (2.22c54680.chunk.js:2:4196254)
	Il
	(anonymous function) (2.22c54680.chunk.js:2:4215575)
	Pl (2.22c54680.chunk.js:2:4192989)
	bl (2.22c54680.chunk.js:2:4189075)
	bl
	(anonymous function) (2.22c54680.chunk.js:2:4138294)
	(anonymous function) (2.22c54680.chunk.js:2:4215575)
	Xi (2.22c54680.chunk.js:2:4138240)
	Yi (2.22c54680.chunk.js:2:4138175)
	It (2.22c54680.chunk.js:2:4209386)
	Ze (2.22c54680.chunk.js:2:4116786)
	Ze
[Error] TypeError: undefined is not an object (evaluating 'e.sourceNode')
	Xi (2.22c54680.chunk.js:2:4138383)
	Yi (2.22c54680.chunk.js:2:4138175)
	It (2.22c54680.chunk.js:2:4209386)
	Ze (2.22c54680.chunk.js:2:4116786)
	Ze
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: Version 16.1 (18614.2.9.1.12)
* Operating system and version: Ventura 13.0

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by tynandebold** [comment]
Thanks for this, @jccalvojackson. 

I can confirm that I can reproduce this on Safari, but not consistently with the same set of user actions.

> Is this expected? do I need to disable some security restrictions in safari?

No, to both: it's not expected and you shouldn't need to disable anything in Safari.

We'll have a look.

**Comment by jccalvojackson** [comment]
thanks! in case is relevant, the same happens if using DuckDuckGo Version 1.47.1 (1.47.1)
