### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#1477]
## Description

Our [release process](https://github.com/kedro-org/kedro-viz/blob/main/CONTRIBUTING.md#release-process) is manual. It would be better and probably safer if it was automated.

This ticket should automate the Kedro-Viz release process.

## Context

The Kedro framework release process is automated. It uses [some](https://github.com/kedro-org/kedro/blob/main/tools/circleci/github_scripts/release.sh) [scripts](https://github.com/kedro-org/kedro/blob/main/tools/circleci/circle-release.sh) (maybe more than only these two) to do the job. Let's use this as a template.

## Possible Implementation

See the context section above. I'd suggest forking the repo and doing the experimentation and implementation there first, then bring the working prototype over to this repo.

## Possible Alternatives

Try and use GitHub actions instead of `.sh` files?

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by ankatiyar** [comment]
For reference: The release workflow on `kedro-plugins` is on Github Actions. https://github.com/kedro-org/kedro-plugins/blob/main/.github/workflows/check-release.yml
