### ISSUE TITLE
Update the table of Kedro-viz compatibility with Kedro

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro-viz#1478]
## Description
Short description of the problem here.
https://github.com/kedro-org/kedro-viz/pull/659

Kedro-viz dropped Python 3.6 support at 3.17.0, the last support version is 3.16.0. However, it is not updated properly until `4.2.0`. This confuse Pypi and pip when you try to install kedro and kedro-viz.

For this case, user is on Kedro 0.17.7 and Python 3.6. There are 2 conflicting dependecies.
1. The table suggest Kedro>=0.17.5 should use kedro-viz >=4.7
2. The last support version is actually 3.16 (for Python 3.6)

# Implementation
I actually don't know if it's possible to run viz with this dependency (waiting for user to report if it works with older viz). We should at least add a comment after the table "For Python 3.6 users, the last supported version of kedro-viz is 3.16)

**Comment by rashidakanchwala** [comment]
Closing this as this has been done
