### ISSUE TITLE
`outputs` is not correctly set when its name contains a full stop

### ISSUE THREAD

**Issue by PetitLepton** [kedro-org/kedro-viz#1522]
## Description
When the output of a node contains a full stop, for example `my.dataset`, the visualization breaks by having the wrong name for the data set, in the example `my`, and the data set is not linked to the node.

## Context
Creating a simple pipeline.

## Steps to Reproduce

Create a pipeline whose single node is
```python
from kedro.pipeline import Pipeline, pipeline, node


def create_pipeline(**kwargs) -> Pipeline:
    return Pipeline([node(lambda s: s, inputs="first", outputs="first.out")])
```
## Expected Result
One should have seen `first.out` as the output data set of the node.

## Actual Result

![Screenshot from 2023-09-07 13-26-09](https://github.com/kedro-org/kedro-viz/assets/9269985/fb4f8268-cba6-4576-ae84-33600e88b858)

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version: Ubutnu 22.04
* NodeJS version used (if relevant):
* Kedro version used (if relevant): 18.12
* Python version used (if relevant): 3.10.10

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by noklam** [comment]
@PetitLepton In Kedro, `.` is indicating namespace pipeline which is why it is disconnected in viz, because the input is not namespaced but the output is. (as you can see, viz think that there is a "First" namespace pipeline)) https://docs.kedro.org/en/stable/tutorial/add_another_pipeline.html

**Comment by tynandebold** [comment]
Closing this now. Thanks, @noklam.
