### ISSUE TITLE
Move to pyproject.toml

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1527]
## Description

Kedro-viz currently has `requirements.txt` file which the users use to install all the requirements. We want to now move to pyproject.toml which is a newer way of dependency management.

Pyproject.toml has some advance features that will also make our depandabot much more .... smarter? ;) 

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
@rashidakanchwala is this only for the `requirements.txt` file or do you imagine we can also move on from `setup.py` and `setup.cfg` to use only `pyproject.toml`?

**Comment by astrojuanlu** [comment]
If I may - yes `pyproject.toml` can cover `setup.py` + `setup.cfg` + `requirements.txt`. The only tool that doesn't support `pyproject.toml` is `flake8`, but you're storing its config in `package/.flake8` already anyway, so you should be good.

**Comment by astrojuanlu** [comment]
Unmerged PR https://github.com/kedro-org/kedro-viz/pull/1584

**Comment by astrojuanlu** [comment]
This was never fixed
