### ISSUE TITLE
Bump fastapi so that pydantic v2 is supported

### ISSUE THREAD

**Issue by IngerMathilde** [kedro-org/kedro-viz#1532]
## Description
Update fastapi so that pydantic v2 is supported.

## Context
Currently our new projects want to be able to use pydantic v2 for performance reason. However, this conflicts with kedro-viz, as they depend on fastapi <0.1 which depends on pydantic v1. The frustrating thing that this is not a problem for kedro runs, just for visualizing with pythonic kedro-viz. I suppose we could use the react standalone application, but this seems quite an overhead.

## Possible Implementation
A new version using the new fastapi which supports pydantic v2, (is annoying as you have to keep two versions alive, legacy and new application)

## Possible Alternatives
Make the python version standalone? So that it does not try to implement a session? No clue how it would work exactly. 

## Checklist
- Python

**Comment by IngerMathilde** [comment]
Ah thanks did not see that a pull request was active

**Comment by tynandebold** [comment]
Closing this in favor of [#1529](https://github.com/kedro-org/kedro-viz/pull/1529)
