### ISSUE TITLE
Shareable Viz usability testing

### ISSUE THREAD

**Issue by stephkaiser** [kedro-org/kedro-viz#1533]
This ticket is created to track the testing around Shareable Viz - We want to test the full user journey of shareable viz, including docs. 

Related to - https://github.com/kedro-org/kedro-viz/issues/1116

Full testing plan here - https://mckinsey.ent.box.com/notes/1299786997300 
[Prototype link](https://www.figma.com/proto/3kSpvIO1veLKfy9qHxuXwF/Kedro-WIP?type=design&node-id=527-17958&viewport=229%2C240%2C0.06&t=iMUHAc9CCJ0lXZju-1&scaling=scale-down&starting-point-node-id=527%3A17958&mode=design)

## Research Objective

We would like to test the usability and viability of our v1 concept for creating a hosted link to share Kedro-Viz with less-technical users. The goal of this research is to understand the overall user experience, usability of our solution and what is expected from the **technical user’s perspective**. The testing will be done virtually over Zoom. 

We want to speak to 5-8 internal/external technical users that use Kedro-Viz, across a variety of different roles and experience levels with using Kedro and Kedro-Viz.

### What decisions will this research enable? 
This testing will help us understand if there are any potential blockers to adopting shareable Viz, and validate if the first version of shareable Viz is a minimum viable feature. We would like to know what the ideal experience for hosting and sharing Kedro-Viz is and if there are any pain points experienced in our solution - in order to help us align on the best “bets” for us to take throughout the year to achieve our adoption goal.

### Methods
We aim to capture qualitative feedback through 1-on-1 usability tests with 5-8 users, either in-person or remotely on Zoom.

### Research Outcomes
- Synthesised insights with potential opportunities and recommendations to prioritise for future iterations of shareable Viz. 
- Quantitative results on whether our shareable Viz concept is usable - prototype success/error rates
- Qualitative results on whether our shareable Viz concept matches user expectations and satisfy user needs.

**Comment by NeroOkwa** [comment]
This has been completed by @stephkaiser. You can find the excellent synthesis: [HERE](https://miro.com/app/board/uXjVM8oNLys=/?messenger=slack&utm_source=slack&utm_medium=messenger&utm_campaign=notifications&utm_content=unfurled_chat_link&utm_term=messenger_analytics)
