### ISSUE TITLE
Missing Pipeline Name in kedro-viz `Run Command`

### ISSUE THREAD

**Issue by drlight0715** [kedro-org/kedro-viz#1548]
## Description
Pipeline names are not displayed in visuals created by kedro-viz.

## Context
I aim to display a pipeline name in `Run Command` section.

## Steps to Reproduce

1. Set up a kedro pipeline
2. Run `kedro viz`

## Expected Result
A pipeline name should be visible in `Run Command`.

## Actual Result
No pipeline name is displayed in `Run Command`.

![image](https://github.com/kedro-org/kedro-viz/assets/48976896/0a3ee8d5-8788-4c55-804e-b057eb4c9c3f)

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: Google Chrome
* Operating system and version: Mac OS Ventura 13.6
* NodeJS version used (if relevant):
* Kedro version used (if relevant):  0.18.13
* Python version used (if relevant): 3.9.13

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by rashidakanchwala** [comment]
I was able to recreate this bug at my end using the demo_project code. 

### Steps to Reproduce
- in demo_project/pipelines/modelling/pipeline.py add 'name' to the split_data function so it will be like below

```python
  split_stage_pipeline = pipeline(
        [
            node(
                func=split_data,
                inputs=["model_input_table", "params:split_options"],
                outputs=test_train_refs,
                name='split_data'
            )
        ]
    )
```

next if you run kedro_viz and click on the split_data function - you should see this. 

![Screenshot 2023-10-02 at 10 26 21](https://github.com/kedro-org/kedro-viz/assets/37628668/c4519127-6197-4bd2-905b-f7054d77805c)


### Expected Result - There should be no None. It should just say the below
` kedro run --to-nodes=None.split_data`
