### ISSUE TITLE
Copy to Clipboard component implementation

### ISSUE THREAD

**Issue by stephkaiser** [kedro-org/kedro-viz#1555]
An updated version of the copy to clipboard component was designed during Shareable Viz and we'd like to implement the new component globally across the kedro-viz tool.

Figma component link here - https://www.figma.com/file/3kSpvIO1veLKfy9qHxuXwF/Kedro-WIP?type=design&node-id=334%3A20297&mode=design&t=6Tdhct1LrhJX2mEB-1

**Comment by tynandebold** [comment]
@stephkaiser you should be able to preview what Vlad did by going here: https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/1565

That should eventually open a version of Viz with his changes.

**Comment by stephkaiser** [comment]
Thanks Tynan! it looks perfect, no comments
