### ISSUE TITLE
Fix issues with 1.7.1 kedro-datasets release

### ISSUE THREAD

**Issue by ravi-kumar-pilla** [kedro-org/kedro-viz#1558]
With Kedro Datasets 1.7.1 [release](https://github.com/kedro-org/kedro-plugins/releases/tag/kedro-datasets-1.7.1) , we need to update the dataset imports and fix pytests

We will be pinning down the dependency of kedro datasets to 1.7.0 as a quick fix

**Comment by astrojuanlu** [comment]
Hi @ravi-kumar-pilla , what broke? Do you have a URL of a failing build?

**Comment by ravi-kumar-pilla** [comment]
> Hi @ravi-kumar-pilla , what broke? Do you have a URL of a failing build?

Hi Juan, The circle ci builds are failing - https://app.circleci.com/pipelines/github/kedro-org/kedro-viz/10632/workflows/a8d8d61d-132a-4a48-8990-1ffa51bd422b/jobs/60837

**Comment by merelcht** [comment]
Yes that would fix it. I'm surprised that the tests started failing, because the aliases are still in place.. It might be because of hardcoded `DataSet` in string though..

**Comment by ankatiyar** [comment]
Yeah, you can still create datasets with `CSVDataSet(filepath)` but the type of the dataset created would be `CSVDataset` and it's the assertions against hardcoded strings in the tests that are failing ->
```
assert transcoded_data_node_metadata.transcoded_types == [
            "pandas.csv_dataset.CSVDataSet"
        ]
```

**Comment by ravi-kumar-pilla** [comment]
Thank you for the suggestions. As a quick fix, we decided to pin down kedro-datasets version to 1.7 in the requirements file. We will be adding [support for kedro datasets 1.7.1](https://github.com/kedro-org/kedro-viz/issues/1560) and above in the upcoming sprints. Thank you
