### ISSUE TITLE
Expand Plotly Visualisation’ button on the bottom of the metadata panel is not appearing

### ISSUE THREAD

**Issue by lejarx** [kedro-org/kedro-viz#1571]
## Description
Expand Plotly Visualisation’ button on the bottom of the metadata panel is not appearing when following through this documentation

https://docs.kedro.org/en/stable/visualisation/visualise_charts_with_plotly.html

## Context
Not critical, just not able to follow the tutorial properly
## Steps to Reproduce

https://docs.kedro.org/en/stable/visualisation/visualise_charts_with_plotly.html

## Expected Result
Being able to expand Plotly Visualisation’ button on the bottom of the metadata panel 

## Actual Result
Expand Plotly Visualisation’ button on the bottom of the metadata panel is not appearing when following through this documentation

## Your Environment

* Web browser system and version: Chrome/Edge/SideKick
* Operating system and version: Windows 10
* Kedro version used (if relevant): 0.18.13
* Python version used (if relevant): 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]

![image](https://github.com/kedro-org/kedro-viz/assets/6431985/8ee7aa3f-b0f5-4180-985d-f52877da72a8)

**Comment by jitu5** [comment]
@lejarx @tynandebold 
Plotly Visualisation button on the bottom of the metadata panel is appearing as expected when following through below documentation.
https://docs.kedro.org/en/stable/visualisation/visualise_charts_with_plotly.html

<img width="1798" alt="Screenshot 2023-10-25 at 11 47 10 a m" src="https://github.com/kedro-org/kedro-viz/assets/38945204/f25f0d98-22dc-4e86-a7fa-a07052404a5b">

**Comment by tynandebold** [comment]
@jitu5 did you also check the `Shuttle Passenger Capacity Plot Exp` node, as @lejarx showed in their screenshot?

**Comment by jitu5** [comment]
@tynandebold Yes
<img width="1800" alt="Screenshot 2023-10-25 at 12 26 01 p m" src="https://github.com/kedro-org/kedro-viz/assets/38945204/848616ac-3504-4ddf-b32f-4ac9263ee9af">
