### ISSUE TITLE
Shareable URL for GitHub Page

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro-viz#1574]
## Description

To support Kedro-viz on GithubPage

## Context

This requires least setup, the only requirement is a Github Page so you don't even need to setup a S3 account.

## Possible Implementation

1. A new kedro viz `kedro viz deploy` or `kedro viz build`, such CLI will build the static site combined with the necessary HTML assets and ship this into a standalone folder.
2. A new Github Action which install kedro-viz and run `kedro viz deploy`

The deploy CLI is the key, then S3Deployer and GithubPageDeployer (actually we don't need this because it should be just a Github Action) is simply calling this function and mapping the destination to a S3 bucket etc.

Most of the implementation are already there which requires 3 steps:
1. Build Kedro-viz
2. Copy the necessary HTML/CSS assets and bundle them into a folder
3. Upload the metadata

This issue is created for discussion about the technical design. I can also bundle everything in the Github Action itself, but it makes most sense to implement in `kedro-viz` and have a thin wrapper Github Action that orchestrate this.

## Relative information

See: https://noklam.github.io/kedro-viz-workflow/

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
Relates to #1541

**Comment by rashidakanchwala** [comment]
Closing this as it's done :)
