### ISSUE TITLE
Extend 'View Code' mechanism for data nodes

### ISSUE THREAD

**Issue by MehdiNV** [kedro-org/kedro-viz#1577]
## Description
There was a previous request to add a 'View Code' mechanism to Data Nodes - this would allow users to glimpse the make-up of a specified dataset (particularly useful for non-file based datasets, whereby they have no associated filepaths). 

During a design meeting, we decided to reduce the scope and allow users to only 'preview' a data node if it's a SQLQueryDataset.

Extension/s from this would be:
- View for 7 remaining dataset types, all of which pull their data from external sources instead of a file. 
- _GBQQueryDataSet, APIDataSet, SparkHiveDataSet, SnowparkTableDataSet, SparkJDBCDataSet, PickleDataSet_
- Move the 'Preview' area elsewhere (e.g. a separate window, bottom of the metadata panel, etc)
- _This is because we intend to make the 'Code Block' segment be editable in the future_

## Context
Related to [Issue](https://github.com/kedro-org/kedro-viz/issues/1521) - user mentioned that it'd be useful if they could see where a dataset was derived from, even if they can't view some of its data or SQL code associated (e.g. URL of an API dataset).

## Possible Implementation
See commit [c9862613501240b7a7f3712c131480dfd5c2b2da](https://github.com/kedro-org/kedro-viz/pull/1564/commits/c9862613501240b7a7f3712c131480dfd5c2b2da) in the initial, reduced-scope [PR](https://github.com/kedro-org/kedro-viz/pull/1564). These changes were removed after we reduced scope, but they can be used as a potential launchpad for a future, more improved implementation.

**Comment by astrojuanlu** [comment]
What was the resolution for this one?
