### ISSUE TITLE
watchgod package from requirements was renamed to watchfiles

### ISSUE THREAD

**Issue by FloridaDataGuy** [kedro-org/kedro-viz#1589]
## Description
**watchgod** package from requirements was renamed to **watchfiles**, consider upgrading.

## Context
Kedro-Viz requires `watchgod~=0.8.2`. This package was renamed to **watchfiles**.
In turn **watchgod** 0.8.2 requires `anyio>=3.0.0,<4`. 
This will stay forever because package **watchgod** is not updated anymore while package **watchfiles** is.
Package **anyio** released version 4+ and will keep updating. Some other packages already support **anyio** 4+.
More packages in the near future will support and require **anyio** 4+.

Currently this is not that big of an issue, but in the future this may be a deadlock for pip to resolve.

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Python version used (if relevant): 3.10.13

**Comment by tynandebold** [comment]
Thanks for this, @FloridaDataGuy. Would you be able to create a PR to solve this?

**Comment by FloridaDataGuy** [comment]
> Thanks for this, @FloridaDataGuy. Would you be able to create a PR to solve this?

Yes. I'll work on it.
