### ISSUE TITLE
Design review of front page of docs for Viz

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-viz#1592]
## Description
We've discussed some of this on Slack but I wanted to pull this together into one place for @stephkaiser 

Here is the first step towards a set of docs for Viz: https://docs.kedro.org/projects/kedro-viz/en/latest/

It's live but doesn't replace existing docs and isn't indexed, so it's relatively unseen except by us.

We would like some feedback please on:

(1) How to title the top of the table of contents:
    * should there be a graphic?
    * how do we capitalise "Kedro-Viz"?
   
(2) How to title the top of the main pane?
    * should we include "Kedro" and the yellow diamond?
    * How to capitalise Kedro-Viz (and do we include the yellow diamond or does that conflict with the brand?)

(3) What are your thoughts on the meganav ([as per review request](https://github.com/kedro-org/kedro/pull/3206), [deploy preview link](https://kedro--3168.org.readthedocs.build/en/3168/#))

**Comment by stephkaiser** [comment]
Hi Jo! thank you for creating this ticket for me 🙂

I've finally got some time to have a proper look - the way I see it, even though the docs are separated, we are still in the same product family (which is Kedro) and I think we should be consistent with that in our branding of the docs as well. 

With that in mind - Kedro, Kedro-Viz and Kedro-Datasets documentation in my opinion should have the same navigation (covered in the meganav work here https://github.com/kedro-org/kedro/issues/3024). It should have the kedro logo in the top left (the actual logo not text with a yellow diamond shape), and the user can navigate between the different docs via the main navigation. The left contents panel should be updated depending on which docs is selected in the nav. I also think we can remove the "stable" and "latest" labels next to the logo as we have the Read the Docs component on the bottom left. A very quick cut and paste mockup below using the existing meganav design:

![Mockup](https://github.com/kedro-org/kedro-viz/assets/31114028/e253b6ec-608d-4034-98a7-340fd3cad28b)
 

For capitalisation, I've been using "Kedro-Viz" but happy to hear other suggestions. Whichever one we go with, it should be consistent throughout the docs, including the main navigation. 

I think having a graphic of Kedro-Viz at the top is a great idea too, followed by the value prop underneath. 

Let me know what you think of the above, I think that should cover (1) and (2) - let me know if i've missed anything?

I'll put my comments for the design QA for (3) on the meganav ticket here - https://github.com/kedro-org/kedro/issues/3024

**Comment by stephkaiser** [comment]
@stichbury Thanks Jo, I've left design feedback on https://github.com/kedro-org/kedro/pull/3206
