### ISSUE TITLE
Error Handling for cyclic dependencies in the flowchart

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1593]
## Description
This ticket aims to implement error handling in Kedro-viz's flowchart when detecting cyclic dependencies within the DAG.

## Context
Since the Kedro-viz flowchart represents a DAG, it should not contain any cycles. However, in Kedro projects, we sometimes encounter cyclic dependencies that cannot be accurately represented in the flowchart. 
In the Kedro-viz backend, when such cases are encountered, we currently remove the edges. Please see edge cases section of this [ppt](https://github.com/kedro-org/kedro-viz/blob/main/package/kedro_viz/docs/assets/expand_collapse_modular_pipelines_presentation.pdf) to understand better.

Unfortunately, this approach can be confusing for users as it disconnects their flowchart. Numerous users have reported this issue on Slack and GitHub like #1105.

Given that cyclic dependencies in DAGs are problematic, it's essential to implement proper error handling on the front end (FE). This will help users understand why certain edges have disappeared, reducing confusion.

@stephkaiser has created a design ticket (ticket #1557) to develop general error handling components in Kedro-viz, and this ticket is linked to that.

## Possible Implementation

Currently, we already detect cycles in the DAG when creating the modular pipeline structure in the backend. When a cycle is detected, this information can be sent to the front end, along with the nodes involved in the cycle. On the front end, the flowchart will display as before, but with removed edges. However, there will now be a visual indication in the FE, alerting the user that a cycle was detected and that edges have been removed as a result.

![Screenshot 2023-10-20 at 11 59 11](https://github.com/kedro-org/kedro-viz/assets/37628668/3362e1d6-5545-438f-9275-93144c5c6125)

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by rashidakanchwala** [comment]
@tynandebold suggested using this -- http://qb-design-library.s3-website.eu-west-2.amazonaws.com/?path=/docs/components-toast--docs and putting it somewhere in the bottom of the page.

**Comment by tynandebold** [comment]
This should take its cue from #1557
