### ISSUE TITLE
Check and revise heap analytics tracking for all docs: viz, framework & datasets

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-viz#1595]
Probably one for @tynandebold 

I've been playing around to start pulling in heap data for our new docs subprojects but need adult supervision to make sure it's done correctly:

1. I've not changed the framework docs but please could check the tracking code is OK. I see the dev environment as the primary tag but I think the `env_override` is to switch production data on for builds that are deployed to `stable` for RTD. Could you confirm that though (just in case we aren't capturing the right data).

2. Datasets PR: https://github.com/kedro-org/kedro-plugins/pull/400 <-- Please confirm I've used the right tag and set up properly.

3. Viz PR: https://github.com/kedro-org/kedro-viz/pull/1594 <-- Likewise please check and confirm all is well.

**Comment by tynandebold** [comment]
I think we can close this as I've verified the docs data is coming through as expected to Heap for each project.
