### ISSUE TITLE
Update docs and readme for Kedro-Viz local development setup

### ISSUE THREAD

**Issue by vladimir-mck** [kedro-org/kedro-viz#1601]
## Description
During the creation of a new conda environment and local installation of Kedro-Viz, I encountered several errors that were resolved by installing additional packages. This information is not currently documented and should be added to the official documentation or readme for future reference.

## Context
This change is important because it addresses a gap in the documentation. By sharing this experience, we can help others who might encounter similar issues during setting up local environment. Providing this information can save time, leading to a smoother setup process. It benefits other users by offering a solution to potential hurdles they may face, enhancing their overall experience with Kedro-Viz.

 The following packages had to be installed: 
- kedro-datasets 
- matplotlib
- scikit-learn
- seaborn

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
Thanks for this. Can you please add which Python packages you had to install to get Viz working correctly?

**Comment by ravi-kumar-pilla** [comment]
Hi @vladimir-mck , Thanks for this. Is the command - `pip3 install -r package/test_requirements.txt -r demo-project/src/docker_requirements.txt` from [CONTRIBUTING](https://github.com/kedro-org/kedro-viz/blob/main/CONTRIBUTING.md#launch-a-development-server-with-a-real-kedro-project) guide not installing those ?

**Comment by vladimir-mck** [comment]
@ravi-kumar-pilla  ohh you are right. I see that they install everything needed. I missed that part.

**Comment by tynandebold** [comment]
Closing this as not needed then. Thanks, @ravi-kumar-pilla.
