### ISSUE TITLE
Enable search-as-you-type functionality in Read the Docs

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#1612]
## Description

See @astrojuanlu's comment here: https://github.com/kedro-org/kedro/issues/2798#issuecomment-1781302147

## Context

To use the RTD "search as you type" functionality, we need a tiny bit of frontend code:

- disable Sphinx search keyboard / shortcut.
- add JS code to trigger the event readthedocs-search-show when div[role=search] > form > input gets focus.

More context in this comment: https://github.com/readthedocs/addons/issues/165#issuecomment-1781287582

This is the problem that we're solving by working on this ticket: https://github.com/readthedocs/addons/issues/165

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by stichbury** [comment]
Would be good to know how much extra effort as search improvements are still a high priority for docs (given that we have abandoned Algolia search at present).

**Comment by astrojuanlu** [comment]
This got simpler https://github.com/readthedocs/addons/pull/181

**Comment by stichbury** [comment]
Would still be good to get this sized and in the queue @tynandebold and @vladimir-mck

**Comment by stichbury** [comment]
Spike on this in the coming sprint w/c 13th Nov to size it.

**Comment by rashidakanchwala** [comment]
Done this for both. Closing this ticket

**Comment by astrojuanlu** [comment]
There's a syntax error in the JavaScript @rashidakanchwala

**Comment by astrojuanlu** [comment]
Only in Viz though. datasets is fine.
