### ISSUE TITLE
Change `kedro viz` to `kedro viz run`, make `viz` a command group 

### ISSUE THREAD

**Issue by amandakys** [kedro-org/kedro-viz#1616]
## Description

To support #1636 `kedro viz deploy` command, `kedro viz` needs to become a command group. 

This work needs to be preceded by #1625 to highlight to users that in a future release, the `kedro viz` command will no longer work 

This should be supported by an informative error message

``` 
>> kedro viz 

Did you mean this? 
  kedro viz run 
    
Usage: kedro viz [OPTIONS] COMMAND [ARGS]
    
Options:
  -h, --help Show this message and exit 
  
Commands: 
  run         Launch local Kedro Viz instance         
  deploy      Deploy Kedro Viz to a hosted link with AWS 
  build       Create build directory of local Kedro Viz instance with static data 
```
*Note: the `deploy` and `build` help text can be added when those commands are implemented, rather than as part of this ticket 

## Acceptance Criteria 
- [ ] working `kedro viz run` command, that launched Kedro viz (same functionality as current `kedro viz`
- [ ] when users run `kedro viz` they receive useful help text prompting them to use `kedro viz run` instead

**Comment by datajoely** [comment]
is there a confusion with `kedro run` what about `kedro viz up` like `docker compose up`?
