### ISSUE TITLE
Revise `layout.html` for docs projects for Viz, Framework and Datasets

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-viz#1618]
This issue forms part of the ongoing work to enable a documentation subproject for Kedro-Viz. See https://github.com/kedro-org/kedro-viz/issues/1524 for more details (and the https://github.com/kedro-org/kedro/issues/2600).

@tynandebold Please could someone with front-end skills make some changes to the `layout.html` files that we'll be using for docs subprojects? They need to be adjusted to align with design feedback from @stephkaiser which is recorded in #1592 as follows:

## For Viz
You can commit to my PR: https://github.com/kedro-org/kedro-viz/pull/1617

<details><summary>Docs are currently building to look like this:</summary>
<img width="1381" alt="image" src="https://github.com/kedro-org/kedro-viz/assets/5180475/f92921fa-4f6d-409f-bcbe-f343c1f2e5a0">
</details>

[You can find the docs built here](https://docs.kedro.org/projects/kedro-viz/en/latest/)

**Changes needed**
* Revise top left to have the diamond + kedro logotype 
* Remove version (latest/stable) that follows the logo/type at the top left hand corner

<details><summary>This is a mock design:</summary>

![image](https://github.com/kedro-org/kedro-viz/assets/5180475/13de2882-6e9d-4e57-8ffb-5902c6e53b06)
</details>

---

## For Framework
Also needs someone with front-end skills please.

You can commit to my PR: https://github.com/kedro-org/kedro/pull/3206

<details><summary>Docs are currently building to look like this:</summary>

<img width="1158" alt="image" src="https://github.com/kedro-org/kedro-viz/assets/5180475/85b94350-ddef-456e-9d6e-263ec336bc2f">

</details>

[You can find a preview of the docs here](https://kedro--3206.org.readthedocs.build/en/3206/)

**Changes needed**
* No need to change the logo/type as this is fine for the framework (it's what we need for Viz too, see above)
* Remove version (latest/stable or build preview number) that follows the logo/type at the top left hand corner

## For Datasets
Also needs someone with front-end skills please.

You can commit to my PR: https://github.com/kedro-org/kedro-plugins/pull/400

<details><summary>Docs are currently building to look like this:</summary>

<img width="1148" alt="image" src="https://github.com/kedro-org/kedro-viz/assets/5180475/db0dfb95-5797-4742-a46f-0260fd4d1525">

</details>

[You can find a preview of the docs here](https://kedro--400.org.readthedocs.build/projects/kedro-datasets/en/400/)

**Changes needed**
* General sort-out of the presentation as it's a bit of a jumble right now
* Change the logo/type to match Viz and Framework as above
* Remove version (latest/stable or build preview number) that follows the logo/type at the top left hand corner (if it's displayed, I cannot completely see it).

## Context
Implements design feedback from #1592 

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
I'm closing this as completed. I've added the full [logo treatment](https://github.com/kedro-org/kedro-brand-identity/blob/main/horizontal/color/kedro-horizontal-color-on-light.svg) to all three docs projects, removed the version label, and updated the logo size in the shared CSS file.
