### ISSUE TITLE
Extend 'preview' mechanism to kedro-datasets

### ISSUE THREAD

**Issue by MehdiNV** [kedro-org/kedro-viz#1622]
## Description
Ticket [SQL](https://github.com/orgs/kedro-org/projects/1/views/4?pane=issue&itemId=38503256) is blocked as existing solutions aren't viable.

The most optimal solution would be modifying kedro-datasets to have a new supporting method for kedro-viz, which would shift responsibility from `viz` to `kedro-plugins` instead. Easier to test, less coupling between the two systems.

## Context
A change like this is accepted by multiple team members - it's a viable compromise, but still doable

## Possible Implementation
Adding the existing 'preview' method in kedro-datasets to ones like SQLQueryDataset.

**Comment by rashidakanchwala** [comment]
Refer to the spike work done here - #1623

**Comment by astrojuanlu** [comment]
One thing that is not clear to me - is the idea to extend the `_describe` method to allow this preview mechanism? Given that `_describe` already returns a dictionary, would be nice to reuse it (as suggested in #1714)

**Comment by SajidAlamQB** [comment]
I've been trying to understand this issue and have some questions:

Can we confirm the scope of this ticket, is there list of dataset types that need the preview functionality extended? 

Will the implementation follow similar structure done in https://github.com/kedro-org/kedro-plugins/pull/504?

**Comment by SajidAlamQB** [comment]
Extended preview to the following:

-  ParquetDataset
-  SQLTableDataset
-  pandas.JSONDataset
-  JSONDataset

in https://github.com/kedro-org/kedro-plugins/pull/595
