### ISSUE TITLE
Investigating 'preview' potential for other datasets (Spike)

### ISSUE THREAD

**Issue by MehdiNV** [kedro-org/kedro-viz#1623]
## Description
Currently only two datasets in `kedro-plugins/kedro-datasets` ([repo](https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets/kedro_datasets)) have a 'preview' method. This collates, say for CSV, the first 5 rows to display in Viz.

Investigation is to see if other datasets could have the same thing implemented for them; what should the 'preview data' look like? Will it necessarily be tabular? Is it even possible for xyz dataset? 

Idea is to have a answer, after spike investigation, of all the ways those datasets could have 'preview' implemented for them.

## Context
Our aim has been to extend the 'preview' method past just 2 datasets - doing this investigation now will save us a lot of time later when we finally get around to doing it. The answers / document from this issue can guide how that implementation proceeds.

## Possible Implementation
No implementation, just investigating each dataset and writing down what its preview format should be (e.g. for tabular datasets, it should be the first 5 rows).

**Comment by MehdiNV** [comment]
**Excel**
_Tabular data type; preview displays first 5 rows_

![Image](https://github.com/kedro-org/kedro-viz/assets/35583819/ee765b7c-a69b-4824-bd1d-ca16bc40b099)

**Comment by datajoely** [comment]
I think `GenericDataSet` and all Pandas dataset should be easy to preview as the output will always be a table.

If we did Pandas, Spark (and Polars for fun) that gets us most of the tables people write today.

As an added bonus is their a route for custom datasets to provide the required functionality with no extra work on the Viz side?

**Comment by astrojuanlu** [comment]
GeoJSON and GML could be represented as maps with a small embed of Leaflet.js, like http://geojson.io/

**Comment by rashidakanchwala** [comment]
This ticket is done. The implementation ticket for this is #1622
