### ISSUE TITLE
Upgrade to React18 

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1629]
## Description
Upgrade Kedro-viz to work with React 18. 

## Context
A reason to prioritise this is because Brix is on React 18 and it can no longer integrate Kedro-viz. 

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by MehdiNV** [comment]
Few resources found so far:

**Upgrade Guide:** https://react.dev/blog/2022/03/08/react-18-upgrade-guide
**Guidance / advice to use React's new `Root API`:** https://www.w3schools.com/react/react_upgrade.asp

**Comment by MehdiNV** [comment]
#### Notes
---

**Problematic dependencies**
- React-test-renderer
- React-json-viewer
- enzyme-adapter-react

**Next steps**
Migrate to React 18, and replace the 2 breaking tests related to enzyme-adapter-react

**Comment by astrojuanlu** [comment]
Is there a follow-up issue for `react-scripts`? https://github.com/kedro-org/kedro-viz/pull/1652#issuecomment-1845198257
