### ISSUE TITLE
SparkContext not reinitialized due to forked process start

### ISSUE THREAD

**Issue by lemonhead94** [kedro-org/kedro-viz#1656]
## Description
In the latest release the following was added:
[`data_access_manager.resolve_dataset_factory_patterns(catalog, pipelines)`](https://github.com/kedro-org/kedro-viz/blob/86243d0f299cc2e718aceaf830ba7c5dd5ef3b91/package/kedro_viz/server.py#L40)

This forces a check of exists for all datasets, which is good but caused the following issue:

With SparkDatasets only when starting it through Jupyter Notebooks.
The issue being that the Spark Context gets initialised in this scenario on the Kedro context loading (`%load_ext kedro.ipython`) on a process.
Now when `%run_viz` gets called you are using multiprocessing to spin up a new forked process for unix only, since that's default. On Windows and MacOS a completely new process is default.

```python
    viz_process = multiprocessing.Process(
        target=run_server,
        daemon=True,
        kwargs={"project_path": project_path, "host": host, "port": port},
    )
```
[Link](https://github.com/kedro-org/kedro-viz/blob/86243d0f299cc2e718aceaf830ba7c5dd5ef3b91/package/kedro_viz/launchers/jupyter.py#L110)

What ends up happening is that due to it being a forked process, Spark still thinks its already initialised but can't access it since its on a different process.

The solution is to add the following, as it will force a fresh process instead of a forked one.
```python
    multiprocessing.set_start_method("spawn")
    viz_process = multiprocessing.Process(
        target=run_server,
        daemon=True,
        kwargs={"project_path": project_path, "host": host, "port": port},
    )
```

## Context
Can we add this change or will it break some other functionality you guys are using forked processes for?

**Comment by ravi-kumar-pilla** [comment]
Hi @lemonhead94, Thank you for raising this. I am curious to know what was the dataset type on kedro viz metadata panel for this particular dataset before v6.7.0

For reference -

<img width="1026" alt="image" src="https://github.com/kedro-org/kedro-viz/assets/87735534/de966ab2-1317-425a-b2c8-082ced3c04ae">

Thank you !

**Comment by lemonhead94** [comment]
Hi there,

This is an internal wrapper around Kedro's `SparkDataset` which adds interactive AAD authentication and Service Principal injection.
The main crux being that it uses a singleton for Spark setup stuff, which is setup before Dataset creation.
However, I have already played around with it and tried overwriting inside the Dataset itself, but to no avail due to the before mentioned fork-process issue. It really is a pitty that this the default configuration for unix based systems.

**Comment by ravi-kumar-pilla** [comment]
Hi @lemonhead94 , 

Thank you for the additional information. Yes, I wanted to understand if this was working as expected before (i.e., kedro viz fetching the dataset type as SparkDataset). If it was fetching the correct dataset type, the issue might be just with the exception handling [here](https://github.com/kedro-org/kedro-viz/blob/86243d0f299cc2e718aceaf830ba7c5dd5ef3b91/package/kedro_viz/data_access/managers.py#L72). If not, we need to implement something which you suggested. 

I am also not sure why the team was using forked processes. Any additional info ? @rashidakanchwala @antonymilne

Thank you
