### ISSUE TITLE
Improve Kedro-viz experience on notebooks. 

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1668]
## Description

When using the %run_viz command for kedro-viz in Jupyter notebooks, it currently opens as an embedded iframe, which is not ideal. The goal of this ticket is to enhance the user experience by adopting a Databricks-like approach, where instead a link is displayed. Clicking this link will open Kedro-viz in a new browser tab.

<img width="911" alt="Screenshot 2023-12-04 at 12 54 38" src="https://github.com/kedro-org/kedro-viz/assets/37628668/12abef4d-3bc7-4c5b-a01d-ec2bd46636ed">

## Possible Implementation
Here's an example of how it works in Databricks https://docs.kedro.org/en/latest/deployment/databricks/databricks_visualisation.html

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by astrojuanlu** [comment]
For complex iframes, jupyterlab-contrib/rise allows the user to open the page on a new tab (when on Notebook) or seeing the page in a separate panel:

![jupyter-rise](https://github.com/kedro-org/kedro-viz/assets/316517/27b1d5d1-81f1-4b8d-9c08-36b35093480a)

For simpler interactions, it's possible to embed them in the notebook itself, similar to scikit-learn pipelines or ipyleaflet:

![Screenshot 2023-12-04 at 18-32-18 Untitled](https://github.com/kedro-org/kedro-viz/assets/316517/dba02a77-8fe4-4b4d-afd1-210537a35ff1)

Given that Viz can be used as a React component, maybe it's something worth looking into.

(Also for any experiments, make sure you're using Notebook>=7, which is based on JupyterLab 4)
