### ISSUE TITLE
Introducing ruff as a linter to replace pylint, flake8, isort and black.

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1670]
## Description
 
Kedro recently made the switch from pylint, flake8, isort, and black to ruff which is a lot faster 

Below PRs describe how it's done on Kedro Framework
[PR 2634](https://github.com/kedro-org/kedro/pull/2634)
[PR 3435](https://github.com/kedro-org/kedro/pull/3435)

This ticket is to the same on Kedro-viz backend

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by yury-fedotov** [comment]
@rashidakanchwala can I try doing this one, or it's in progress already // for core team only?
