### ISSUE TITLE
"Frozen" state of the landing page for kedro viz (for easier navigation)

### ISSUE THREAD

**Issue by ElenaMironovaQB** [kedro-org/kedro-viz#1673]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

a helpful feature would be to be able to fix the state of the landing page - e.g. we have huge pipelines, we've collapsed some things and hid some outputs - can this state be "frozen", so that every time you open kedro viz, you land at this "prepared" view? Right now we don't let colleagues from outside of our product team handle our kedro viz, cause they'd just get lost directly on the landing page

**Comment by NeroOkwa** [comment]
Thanks @ElenaMironovaQB for this.
## Context
Users who have large pipelines have collapsed some nodes/ filtered out some parameters or datasets. When they share this with other stakeholders, this configuration or 'prepared view' is lost, and the new user has to go through a checklist of steps in other to arrive at the chosen state. To currently solve this the team shares a short video walkthrough of their pipeline, but this loses the value and interactivity of Kedro-Viz.

Solving this means that users with large pipelines are able to prepare their pipelines (with configured settings) and share it with another stakeholder (e.g. business) and that stakeholder can see the same 'prepared view' state as the initial user. The benefit of seeing the same view is greater collaboration, debugging, on the project.

This would also complement #1116.

## Possible Implementation
Make Kedro-Viz flowchart stateful i.e. any change that is done yields a unique url (doesn't have to be human readable) with which a user can share to other stakeholders. This is currently implemented  in the experiment tracking view. 

## Acceptance Criteria
A user is able to easily share a 'prepared state' or landing page of their Kedro-Viz visualisation to another user by

- Configuring the required settings (collapsed nodes, filtered parameters, or datasets) on their pipeline flowchart view
- The state is saved (or unique url is created)
- Using the shareable Viz feature they share that visualisation with another stakeholder, who is able to see the exact same page as the initial user
- Together they can discuss and collaborate on the pipeline, making decisions on the next step of the project.

**Comment by astrojuanlu** [comment]
@ElenaMironovaQB Stateful URLs hopefully addresses this issue by now. There's no documentation for them though 🥲

For showing/hiding datasets you could use tags.

Does this solve your problem? If there are no further comments we will close this issue in a few days.

**Comment by ElenaMironovaQB** [comment]
Thanks a lot, team! We are yet to explore using stateful URLs in our product, but based on demos looks like they should solve it :) looking forward to the docs!

**Comment by astrojuanlu** [comment]
Thank you! Closing this for now, we'll deal with the docs separately. If there's any further requests let us know!
