### ISSUE TITLE
Shareable Viz with GCP

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-viz#1675]
## Description
This ticket is related to parent ticket https://github.com/kedro-org/kedro-viz/issues/1116.
This will enable users to host, publish and share their Kedro-Viz pipeline visualisation with a URL on  GCP object storage.

## Context
We previously enabled users to publish and share versions of their Kedro-Viz pipeline visualisation with a URL on AWS S3 in https://github.com/kedro-org/kedro-viz/issues/1116.

Enabling this feature will increase interoperability with the major cloud providers, providing Kedro-Viz access to non-technical stakeholders, and ultimately increasing adoption of Kedro-Viz. 

## Acceptance Criteria
A user is able to easily host and share a version of their Kedro-Viz pipeline visualisation with a URL via GCP by

- Configuring their storage account and region.
- Creating an access key.
- In the CLI, adding their environment variable with the access key.
- Running the kedro viz deploy command.

**Comment by jitu5** [comment]
Documentation on how we can approach hosting viz on GCP. 

**Connecting fsspec to GCP**

**Authorizing via Service Account Key**  

What users need to do - Create a project in GCP console

**On GCP Console**
1. Create Service Account:
	a. Go to "IAM & Admin" > "Service Accounts."
	b. Click "Create Service Account."
	c. Provide a name and optional description.
2. Grant Roles:
	a. Select the service account.
	b. Go to "Roles and Permissions."
	c. Assign "Storage Admin" or "Storage Object Admin" role for full access.
3. Create Key:
	a. Go to the "Keys" tab.
	b. Click "Add Key" and choose "JSON" format.
	c. Download and securely store the key file.

**On command line before running kedro viz deploy**
	Set `GOOGLE_APPLICATION_CREDENTIALS` to the downloaded key file's path.

**Run deploy command**
`kedro viz deploy --platform=gcp --bucket-name=shareableviz`

**Note:**
- Region (Location) is not required in GCP.


**Outstanding Design questions**
1. How to handle a condition where --region is not needed but for other provider it is mandatory  

**Outstanding Development issues**

1. Copied files are not retaining MIME types ( All file types are defaulted to application/octet-stream ).

**Useful Links** 

- https://cloud.google.com/storage/docs/hosting-static-website
- https://gcsfs.readthedocs.io/en/latest
