### ISSUE TITLE
Upgrade / Update uvicorn depdency pin from ~22 to support new versions 0.24.0

### ISSUE THREAD

**Issue by rxm7706** [kedro-org/kedro-viz#1682]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

https://github.com/kedro-org/kedro-viz/blob/main/package/requirements.txt
uvicorn[standard]~=0.22.0 - is about 18 months old, with version 0.24 being the most recent version (Nov 2023)

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.
Try uvicorn[standard]>=0.22.0 as the requirement.txt 

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by rashidakanchwala** [comment]
Closing this as this is merged
