### ISSUE TITLE
 Enable %run_viz magic line to use the arguments that Kedro-Viz supports on the command line

### ISSUE THREAD

**Issue by anapaularg15** [kedro-org/kedro-viz#1699]
Currently, Kedro Viz supports additional arguments on the command line (for example, --pipeline).

However, the %run_viz magic line doesn't allow to pass any argument, which limits the use of kedro viz in notebooks.

**Comment by astrojuanlu** [comment]
Hi @anapaularg15, thanks for filing this feature request! The team will look at it and prioritise it soon.

**Comment by rashidakanchwala** [comment]
Closing this issue as it's completed and released with Kedro-viz 8.0.0
