### ISSUE TITLE
Show information of dataset returned by `_describe` method?

### ISSUE THREAD

**Issue by BielStela** [kedro-org/kedro-viz#1714]
## Description
I'm tinkering with custom geolocated image dataset (aka rasters) and was wondering how one can display the data that is returned with the dataset `_describe` method. 

## Context
It would be awesome visualize custom dataset metadata through the pipeline.

## Possible Implementation
Use the `_describe` method to display additional info in the metadata tab 

## Possible Alternatives
¯\_(ツ)_/¯

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by rashidakanchwala** [comment]
Hi @BielStela,

We'll be focusing on ticket #1622 in the upcoming work for Kedro-viz. This ticket will enable you to implement a preview method within your CustomDataset. With this method, you'll be able to visualize your dataset using the metadata panel in Kedro-viz.

Initially, we plan to support the display of various data types, including images, Plotly figures, DataFrames, and JSON data. You mentioned having an image dataset, so would you expect it to be displayed in Kedro-viz metadata panel as a static PNG image? 

Please let me know if this aligns with your ask and if you have any specific preferences or additional features you'd like to see.

**Comment by BielStela** [comment]
Oh awesome! Thanks for the quick reply @rashidakanchwala :). In my case, I normally work with remote sensing datasets which are big images with a bunch of related metadata like resolution, coordinate reference system and so on. I'm more interested in seeing this kind of custom key:value data in the panel rather than a rendered picture, since the images can be quite large (at the order of 10s of Gb) which can be too expensive to display.

**Comment by astrojuanlu** [comment]
Is this compatible with the new Preview functionality? https://docs.kedro.org/projects/kedro-viz/en/latest/preview_custom_datasets.html#extend-preview-to-custom-datasets

**Comment by rashidakanchwala** [comment]
It should. 

Also @BielStela in the above was looking for `json preview` to display key-value of the larger datasets, which we have recently built and merged to main and should be a part of next release

**Comment by BielStela** [comment]
Hello, this is awesome! thanks a lot @astrojuanlu  and @rashidakanchwala !! I will wait until next release to check it out then. 100% json preview is what I think will be the best for our case of raster metadata

**Comment by rashidakanchwala** [comment]
@BielStela , Kedro-viz 9.0.0 is out, and we added support for JSONDatasets. To enable preview for your custom dataset you can follow the docs here - https://docs.kedro.org/projects/kedro-viz/en/stable/preview_custom_datasets.html

**Comment by BielStela** [comment]
Works like a charm (✿ŎꇴŎ) 

Thanks @astrojuanlu and @rashidakanchwala !
