### ISSUE TITLE
Bug/improvement for `kedro viz build`

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro-viz#1717]
## Description
Short description of the problem here.
Steps to reproduce:
1. `kedro new` - select kedro-viz  and example pipeline
2. `kedro viz build` - get error

```
                             VersionNotFoundError: Did not find any versions for                                                        
                             MatplotlibWriter(filepath=/Users/Nok_Lam_Chan/dev/kedro-viz-build-ghpage/data/08_reporting                 
                             /dummy_confusion_matrix.png, protocol=file, save_args={}, version=Version(load=None,                       
                             save='2024-01-23T16.05.59.458Z'))                                                                          
ERROR: Failed to build Kedro-Viz : Did not find any versions for MatplotlibWriter(filepath=/Users/Nok_Lam_Chan/dev/kedro-viz-build-ghpage/data/08_reporting/dummy_confusion_matrix.png, protocol=file, save_args={}, version=Version(load=None, save='2024-01-23T16.05.59.458Z')
```

This may not be obvious to an user what's going on. The key to resolve this is to run `kedro run` first because the data doesn't exist yet. 
This also create a secondary problem - your CI need to include a `kedro run` which is a bigger ask because your CI don't necessary have access to your data i.e. S3 etc if you are just running unit tests.

### Minor comments
> ✨ Success! Kedro-Viz build files have been successfully added to the build directory.
It would be great if the `build` is highlighted or showing the full directory

In additional, it would be nice if the target directory is customisable, I can think of use cases that people need to deploy in a special directory. they can always move files manually with commands like `mv` in the CI but it's just simpler to have it in the CLI.

-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version:
* NodeJS version used (if relevant):
* Kedro version used (if relevant):
* Python version used (if relevant):

## Checklist
- [ ] Include labels so that we can categorise your issue

**Comment by rashidakanchwala** [comment]
also love the idea of customisable file name when doing build.

**Comment by NeroOkwa** [comment]
@rashidakanchwala please provide more context how  the refactored dataset code solves this issue.

**Comment by SajidAlamQB** [comment]
This PR seems to solve this issue: https://github.com/kedro-org/kedro-viz/issues/1700

It would be good to know what exactly in the PR has fixed this.

**Comment by rashidakanchwala** [comment]
Before the refactor, we overroad the `load` method of kedro-dataset in ` data_loader.py` for preview purposes for both MatplotlibWriter and Plotly. This leading to considerable coupling and breaking kedro-viz specifically when 

- no kedro run has been executed previously, implying most datasets don't exist.
-  kedro-datasets were not installed. 

In the refactored version, we separated kedro-viz and kedro-datasets, transferring all relevant logic to kedro-datasets. Now, in the mentioned cases, kedro viz run functions properly, but the preview feature is unavailable instead of causing kedro-viz to break.

**Comment by ravi-kumar-pilla** [comment]
Hi @noklam , Thanks for raising this issue. I just tested the scenario mentioned and it is fixed by https://github.com/kedro-org/kedro-viz/pull/1698 . This will be merged in our next release.
