### ISSUE TITLE
Proposal: Migrate to Pydantic v2

### ISSUE THREAD

**Issue by MarkusSagen** [kedro-org/kedro-viz#1719]
## Description
Proposal to migrate to Pydantic version 2 for kedro-viz

## Context
For multiple project me and my team are using currently, we are using packages that already have dependency on Pydantic version 2. Since kedro-viz has a strict requirement on v1, we can't use it in our projects. As more projects are updating and require dependency resolution between dependencies, it will be harder to add kedro-viz to projects.

## Possible Implementation
There are currently two relatively simple options to migrate from Pydantic v1 to v2:

1. Change valildation decorators, methods, Types to conform to Pydantic v2. There is a script for this
2. Still use v1 methods but call them from v2 `from pydantic.v1 import BaseModel`

https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features

Out of the two options, I would think option 2. is the easier and would be easier to test

Would happily contribute to this and do the change if it is a good idea

## Checklist

- [X] Include labels so that we can categorise your feature request

**Comment by astrojuanlu** [comment]
Thanks @MarkusSagen for opening this issue! We are already tracking it in https://github.com/kedro-org/kedro-viz/issues/1603. Please add your 👍🏽 emoji reaction there for visibility.

I'm closing this as a duplicate.
