### ISSUE TITLE
Kedro-Viz needs, but does not "require," Kedro-Datasets

### ISSUE THREAD

**Issue by deepyaman** [kedro-org/kedro-viz#1725]
## Description
Kedro 0.19.2 dropped its dependency on Kedro-Datasets. Kedro-Viz requires Kedro-Datasets (should it? @noklam notes, "kedro-datasets shouldn't really be needed, but seems like kedro-viz assume either kedro-datasets or kedro.extras should exist"), which it was getting transitively from Kedro until 0.19.2.

## Context
[My project](https://github.com/deepyaman/jaffle-shop) doesn't use any core datasets. As a result, I wasn't requiring Kedro-Datasets. However, Kedro-Viz functionality broke when I upgraded to Kedro 0.19.2.

## Steps to Reproduce

1. Clone https://github.com/deepyaman/jaffle-shop
2. Switch to project root
3. `git checkout 9867a9de1447f00826366f6919d048756aa6c935` (or some other commit before I add the `kedro-datasets` dependency)
4. `pip install -r requirements.txt`
5. `kedro viz run`

## Expected Result
It works

## Actual Result
It doesn't

```
(kedro-jaffle-shop) deepyaman@Deepyamans-MacBook-Air jaffle-shop % kedro viz run
[01/30/24 18:04:11] WARNING  Failed to load kedro_viz.launchers.cli commands from EntryPoint(name='kedro-viz', value='kedro_viz.launchers.cli:viz_cli', group='kedro.global_commands'). Full        utils.py:376
                             exception: No module named 'kedro.extras'                                                                                                                                          
                    WARNING  Failed to load kedro_viz.launchers.cli commands from EntryPoint(name='kedro-viz', value='kedro_viz.launchers.cli:viz_cli', group='kedro.global_commands'). Full        utils.py:376
                             exception: No module named 'kedro.extras'                                                                                                                                          
Usage: kedro [OPTIONS] COMMAND [ARGS]...
Try 'kedro -h' for help.

Error: No such command 'viz'.
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version: OSX
* NodeJS version used (if relevant):
* Kedro version used (if relevant): 0.19.2
* Python version used (if relevant):

## Checklist
- [ ] Include labels so that we can categorise your issue

**Comment by rashidakanchwala** [comment]
Thanks Deepyaman, i tested this with this PR #1698 and confirm that this issue will be fixed once the refactor dataset works is merged.

**Comment by ravi-kumar-pilla** [comment]
Hi @deepyaman , Thanks for raising this issue. I just tested the scenario mentioned and it is fixed by https://github.com/kedro-org/kedro-viz/pull/1698 . This will be merged in our next release.
