### ISSUE TITLE
Symbol for permalink in docs subheaders 

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-viz#1734]
## Description
Subsections of the docs have permalinks and these are typically displayed as follows (from Framework docs):

<img width="953" alt="Screenshot 2024-02-01 at 16 00 44" src="https://github.com/kedro-org/kedro-viz/assets/5180475/c3e8654b-8e4f-41e9-8998-6f3fff598299">

However, while this _was_ the case for Viz, something has changed and now the symbol is missing again:
<img width="950" alt="Screenshot 2024-02-01 at 16 00 27" src="https://github.com/kedro-org/kedro-viz/assets/5180475/faa0f5e9-80e4-46ee-a4e6-f639a0ba797b">

Would it be possible to reinstate it?

**Comment by rashidakanchwala** [comment]
This seems to be fixed on it's own. I can see the symbol now. Can you confirm @astrojuanlu ?

**Comment by rashidakanchwala** [comment]
The team tested this with multiple browsers : safari, chrome and firefox and it looks like it's been fixed hence closing this issue.
