### ISSUE TITLE
Extending stateful URLS 

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1736]
## Description

This issue is to solve for this problem #1673 

The aims to enhance the stateful URLs to include additional functionalities such as 
- node type filtering, 
- tag filtering, and 
- expanding/collapsing all modular pipelines. 

We understand that this may result in longer URLs. Shortening our existing URL states is a priority, even if the resulting URLs are not human-readable.

Below is the current code 
```javascript 
export const params = {
  focused: 'focused_id',  (instead we use **fid**) 
  selected: 'selected_id', (instead we use **sid**) 
  selectedName: 'selected_name', (instead we use **sn**) 
  pipeline: 'pipeline_id', (instead we use **pid**) 
  run: 'run_ids', (instead we use **rid**) 
  view: 'view', (instead we use **v**) 
  comparisonMode: 'comparison', (instead we use **cmp**) 
};

```

Here are some suggestions for the new parameters. For Node Filtering by node types, or tags -- maybe we only mention what we want to hide in the params otherwise params will get very long. 
- To filter by types: type=parameters,dataset (this means only task nodes will be visible) 
- To filter by tags: tag=tagid1,tagid2,tagid3 (this means all nodes with thse tagsIds will be hidden) 
- To expand all: expAll=true/false 

- [ ] Include labels so that we can categorise your feature request

**Comment by rashidakanchwala** [comment]
@NeroOkwa @astrojuanlu

**Comment by stephkaiser** [comment]
suggestion to also include ability to save pretty name on/off
