### ISSUE TITLE
[wip] Kedro-Viz Command Line Constructor 

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-viz#1753]
## Description
The purpose of this feature is to provide a way for users to select a part of their pipeline, change the parameters, and generate a run command for the terminal. This would contribute towards solving the reporting use case of Kedro-Viz(#1279).

It was also highlighted in the  https://github.com/kedro-org/kedro-viz/issues/1750 research.

The user journey could be:
1. You have an editor of commands in the side panel.
2. You select/filter a region.
3. pop up comes with table of list of used parameters and their current values. 
4. These values are editable like in a spreadsheet.
5. When you make the changes and click apply, a new popup shows up with a constructed kedro run command.
6. You can copy this command and run in your terminal. 

## Context
Why is this change important to you? How would you use it? How can it benefit other users?
This will support the reporting use case but also increase collaboration between technical and non-technical stakeholders in a team. Users will be able to visualise outputs of a run, change those outputs and visualise the change, without having to leave the Kedro-VIz UI. 
As mentioned in #1279, this will make Kedro-Viz a single-entry point for visualising outputs from a run and will also support non-technical users who need the insights, resulting in increased usage of Kedro-Viz.

## Possible Implementation
1. This would be a pipeline selector for selection of nodes.
2. Backend would provide to the front end the list of current parameters and their values being used in that specific pipeline. 
3. Frontend should visualise and enable the edit of these parameters. 
4. Generate kedro run command with the changes. 

## Possible Alternatives
 A future iteration would be running the updated parameters from Kedro-Viz and seeing the immediate result. But this puts Kedro-Viz in the orchestrator group, which is not the current product vision.

**Comment by astrojuanlu** [comment]
Similar to the ideas we ended up describing in #1945 ?

**Comment by Huongg** [comment]
Close this issue for now, the child task is #1945
