### ISSUE TITLE
Make `kedro viz run --pipeline` consistent with `kedro run --pipeline`

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-viz#1754]
> I think `kedro viz run --pipeline` should be consistent with how `kedro run --pipeline` behaves. This behavior was surprising also for me.

_Originally posted by @astrojuanlu in https://github.com/kedro-org/kedro-viz/issues/1733#issuecomment-1936293108_

**Comment by astrojuanlu** [comment]
More context in the linked issue. Essentially, spaces are valid for pipeline names in Kedro Viz, but not for Kedro Framework. So `kedro run --pipeline="Reporting stage"` would not work, but `kedro viz run --pipeline="Reporting stage"` does.

I liberally opened this on Kedro Viz, seemingly implying that Viz should converge with Framework. But maybe it should be the other way around? (:

**Comment by rashidakanchwala** [comment]
@astrojuanlu - do we need to do work on Kedro-Viz, or will this be a Kedro framework ticket then?

**Comment by astrojuanlu** [comment]
It's for us to decide what to do cc @merelcht

**Comment by rashidakanchwala** [comment]
We discuss this ticket when @astrojuanlu has a chance to look at this more closely.

**Comment by astrojuanlu** [comment]
Can we do with this issue the same we did with https://github.com/kedro-org/kedro/issues/2259 ? Hence reframe it to "look for inconsistencies between Kedro and Kedro-Viz", prioritise it as low, and move it to the backlog.

**Comment by rashidakanchwala** [comment]
Closing this ticket in favour of this #2165

**Comment by astrojuanlu** [comment]
There was no inconsistency, `kedro run -p "Reporting stage"` just works 😄
