### ISSUE TITLE
[Experimentation] Make Kedro-Viz flowchart filterable

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-viz#1784]
## Description

Users want to filter and focus on a particular section  of the flowchart e.g. downstream assets and nodes and generate a unique run definition. This ticket investigates how to achieve this using [kedro pipeline slicing](https://docs.kedro.org/en/stable/nodes_and_pipelines/slice_a_pipeline.html).

As mentioned in #1744:
> As a user I want to filter Kedro-Viz to match the run definition of my pipeline only showing the nodes which will be executed as part of the run configuration

This was highlighted in the competitor benchmark #1750: The two key examples were `dbt` and `Dagster` which expanded the filter query of their lineage graphs using special operators such as `select` and `exclude` in the case of dbt.

### dbt:

dbt achieves this using special graph [operators](https://docs.getdbt.com/reference/node-selection/graph-operators) like "+mymodel+", which means running upstream & downstream of a node. 

### Dagster:

Dagster also achieves this using special [operators](https://docs.getdbt.com/reference/node-selection/graph-operators). This can be combined with other filters for a more personalised lineage graph focused on the upstream/downstream dependencies of a particular node or asset.

## Context

For example, in the Kedro-Viz below the node name is `create_derived_features`, you can filter the highlighted pipeline using [kedro pipeline slicing](https://docs.kedro.org/en/stable/nodes_and_pipelines/slice_a_pipeline.html)  and a union of pipeline.filter with 'to nodes' and 'from nodes'.  

![FilterNok](https://github.com/kedro-org/kedro-viz/assets/50266242/6533c9a5-47a2-445e-ba1b-76ac04c267f2)

This would provide greater flexibility to transform and investigate the flowchart.

## Acceptance Criteria
A user is able to easily filter their Kedro-Viz pipeline from the flowchart  by:

1. Selecting 'from_node'  and 'to_node'. 
2. The visualisation changes instantly and he sees the selected area.
3. As the filtering and hence visualisation changes, the URL should change #1736.

**Comment by noklam** [comment]
> For example, in the Kedro-Viz below the node name is create_derived_features, you can filter the highlighted pipeline using [kedro pipeline slicing](https://docs.kedro.org/en/stable/nodes_and_pipelines/slice_a_pipeline.html) and a union of pipeline.filter with 'to nodes' and 'from nodes'.

While I think this is useful, there are immediate questions:
- How do I run this in `kedro`? The answer is impossible, see [this blog](https://noklam.github.io/blog/posts/kedro-pipeline-slicing-pipeline/2024-03-06-Kedro-Pipeline-Slicing-Pipeline.html#advance-pipeline-slicing) I wrote last week. (It's not entirely impossible, but I think not possible to run this with `kedro run` is sufficient to conclude that this doesn't work)

I throw a question in #random in the Slack group, https://linen-slack.kedro.org/t/16648352/kedro-mini-kedro-challenge-let-say-the-node-name-is-create-d#5d37c750-5ca2-4388-b3ec-f11222f76b54, and it doesn't seem that people need this.

**Comment by Huongg** [comment]
We've completed some Spike work and held an ideation workshop. Based on these activities, we've decided to build the MVP1 for this feature so we'll be closing this ticket. For more context, you can refer to our [Miro Board](https://miro.com/app/board/uXjVK9wvRm0=/) and the [video recording](https://mckinsey.box.com/s/19eckdkk0rqbakrzkutulqxh85x4fr6k) to see our discussion and the milestones related to this ticket.

Next Steps: We're now working on MVP1, which includes:

* Design and build the building run command component in general (not slicing). #1945 
* Conduct a SPIKE: Implement the functionality to select and shift-hold to select 2 nodes from the chart (either from a node or input to a node or input). #1944
