### ISSUE TITLE
Migrate Kedro-Viz  from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-viz#1785]
## Description
We should migrate the Kedro-Viz workflow from CircleCI to GitHub Actions (GHA). 

Currently, `kedro`, `kedro-plugins` and `kedro-starters` are all on GHA. It was covered in [#2153](https://github.com/kedro-org/kedro/issues/2153), [#176](https://github.com/kedro-org/kedro-plugins/issues/176).

Kedro-Viz CircleCI [setup](https://github.com/kedro-org/kedro-viz/tree/main/.circleci).

## Context
This would simply the Kedro-Viz CI/CD and release process, and make it concurrent with Kedro. 

## Possible Implementation
The workflow would include the following steps:

- Move npm and pypi release process to GHA.
- Move tests to GHA.
- Nightly build.
- Remove the CircleCI setup.

**Comment by ravi-kumar-pilla** [comment]
Hi Team,

This is awesome ! Happy to see we are switching to GitHub Actions soon !! I would like to add few observations with our current CircleCI setup for the release -

1. We follow a release process as mentioned [here](https://github.com/kedro-org/kedro-viz/blob/main/CONTRIBUTING.md#release-process) which is nice.
2. Context: During Release, there is a github action for tagging the release and a CircleCI job for running tests (lint, unit, e2e) and publishing the package to npm, pypi.
3. We run all the above jobs in parallel which means even if the tests fail for some reason, we still tag our release and publish it to npm, pypi. I would like to propose a flow where we have a github action which runs all the required tests (lint, unit, e2e) -> tags the release -> releases it to pypi and npm in a sequence.

Happy to discuss further when this ticket is implemented.

Thank you

**Comment by ankatiyar** [comment]
@ravi-kumar-pilla I think that is doable, that's how we've implemented the release process on `kedro` and `kedro-plugins` 
https://github.com/kedro-org/kedro/wiki/The-CI-Setup:-GitHub-Actions#the-release-setup
