### ISSUE TITLE
Release notification doesn't parse markdown  ` backticks

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro-viz#1786]
Backticks should be parsed and turned into `<code>` blocks

![image](https://github.com/kedro-org/kedro-viz/assets/35801847/548b72a2-c2eb-4904-b7ae-9e7df329b0e6)

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-viz/pull/1826
