### ISSUE TITLE
`kedro viz build` is not running hooks

### ISSUE THREAD

**Issue by inigohidalgo** [kedro-org/kedro-viz#1802]
## Description
`kedro viz build` skips the hooks, whereas `kedro viz run` allows for choosing whether or not to run them. I would like to be able to do the same for `kedro viz build`.

https://linen-slack.kedro.org/t/16664076/in-kedro-viz-can-i-control-which-hooks-are-run-when-running-#0b14d294-110d-4755-91a9-ca80724414d1

@rashidakanchwala

**Comment by NeroOkwa** [comment]
Backlog grooming note:

The action is to make `kedro viz run` and `kedro viz build` compatible e.g. adding/removing hooks.
Related (to be addressed first before this) - #1808

**Comment by inigohidalgo** [comment]
From that other thread

> We want to enable this for all cli commands of kedro-viz including run , build and deploy

That would solve my need directly. If that issue is meant to track both `build` and `run` then my issue is redundant as that is exactly what I want, an include hooks parameter for Kedro viz build

**Comment by rashidakanchwala** [comment]
Yes, u should now be able to to do `kedro viz build --include-hooks`

**Comment by rashidakanchwala** [comment]
I will close this issue as it's fixed :)
