### ISSUE TITLE
Introducing `--include-hooks` parameter and deprecating `--ignore-plugins` in Kedro-Viz

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1808]
## Description

In Kedro-Viz, hooks automatically run, but you can choose to skip them by using `kedro viz run --ignore-plugins`. However, since most of Kedro-Viz's features don't need hook information to work, and many users don't know about the `--ignore-plugins` option, we should consider a new approach. This issue about making hook execution opt-in by default, which means hooks would be disabled unless you choose to enable them.

## Possible Implementation

This ticket propose the following changes:

- Disable Hooks by default: Hooks will no longer be executed automatically. This change aims to streamline the operation of Kedro-Viz, reducing unnecessary processing and speeding up the visualization rendering for users.

- Introduce `--include-hooks` parameter: For users who require hook execution to generate runtime data for dynamic pipelines or other specific use cases, we will introduce a new `--include-hooks` parameter. This parameter allows users to explicitly opt-in to execute their hooks as needed, offering flexibility without sacrificing the tool's efficiency for the majority.

- Deprecate `--ignore-plugins` parameter: In light of introducing the `--include-hooks` option, the existing `--ignore-plugin`s parameter will be phased out. 

We want to enable this for all cli commands of kedro-viz including `run` , `build` and `deploy` 

Before implementing these changes, it would be nice to understand the usage of `--ignore-plugins` parameter. @NeroOkwa 

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by NeroOkwa** [comment]
@rashidakanchwala according to our metrics, there are no users using `ignore-plugins`
