### ISSUE TITLE
Drop toposort and migrate to graphlib

### ISSUE THREAD

**Issue by ravi-kumar-pilla** [kedro-org/kedro-viz#1820]
## Description

This ticket aims at dropping toposort dependency in favor of built-in graphlib if possible. Following how Kedro team did this - https://github.com/kedro-org/kedro/pull/3728

## Context

We were depending on Kedro's environment for toposort dependency and since Kedro dropped this dependency, Viz started failing. This also raises an issue of having transitive dependencies. We can improve the code base to remove such transitive dependencies in future - #1821 

## Possible Implementation

We use `from toposort import CircularDependencyError, toposort_flatten` in our layers module. We need to find an alternate implementation to `toposort_flatten` within graphlib to resolve this issue

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-viz/pull/1942
