### ISSUE TITLE
Flowchart view inconsistency with tag filters

### ISSUE THREAD

**Issue by ravi-kumar-pilla** [kedro-org/kedro-viz#1822]
## Description

Incase of expandModularPipelines = false and the filtered nodes happened to be inside a modular pipeline, it should show the modular pipeline node (collapsed view) which seems to be missing on refresh. 

https://github.com/kedro-org/kedro-viz/pull/1799#issuecomment-2013933157

## Context

When I use tag filtering and if I do not have modular pipelines expanded, on page refresh I am missing few nodes which do have the tags. This causes an incorrect DAG rendering. This may be due to the modular pipelines not inheriting the tags from the children nodes. The changes needs to be propagated from the backend.

## Steps to Reproduce

Explained [here](https://github.com/kedro-org/kedro-viz/pull/1799#issuecomment-2013933157)

## Expected Result

When I use tag filtering and if I do not have modular pipelines expanded, on page refresh I should see the collapsed view of the modular pipeline as I see when I do not hit refresh

## Actual Result

When I use tag filtering and if I do not have modular pipelines expanded, on page refresh I am missing the entire modular pipeline which has nodes that have the tags.

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: Chrome
* Operating system and version: macOS
* NodeJS version used (if relevant):
* Kedro version used (if relevant):
* Python version used (if relevant):

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by rashidakanchwala** [comment]
@ravi-kumar-pilla to update this ticket with more information.
