### ISSUE TITLE
Adding toposort as kedro-viz dependency

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro-viz#1849]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."
When I install Kedro-viz with latest kedro, I get an immediate error.

> [04/08/24 11:31:36] WARNING  Failed to load kedro_viz.launchers.cli commands from                utils.py:378
>                              EntryPoint(name='kedro-viz',                                                    
>                              value='kedro_viz.launchers.cli:viz_cli',                                        
>                              group='kedro.global_commands'). Full exception: No module named                 
>                              'toposort'        

                 

https://github.com/kedro-org/kedro-viz/blob/2b0a06641094dd822459d15ad09ccb9bc404988a/package/kedro_viz/services/layers.py#L6

## Context
Why is this change important to you? How would you use it? How can it benefit other users?
This is a bug because the dependency is not mentioned.

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.
temporary fix: add toposort in kedro viz dependency.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.
Drop dependency completely as https://github.com/kedro-org/kedro/pull/3728 did

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by rashidakanchwala** [comment]
Closing this as toposort has already been added as a viz dependency and there exists a ticket to migrate to graphlib #1820
