### ISSUE TITLE
Collapsible non-modular pipelines

### ISSUE THREAD

**Issue by bpmeek** [kedro-org/kedro-viz#1873]
## Description
It always annoys me that I can't collapse and expand non-modular pipelines.

## Context
I usually like to add a static image view to the `README.md` of my Kedro projects to give the users some basic context of the flow of the project. The standard view showing all nodes and datasets is too much information especially in large, complex projects.

## Possible Implementation
Add functionality to collapse or expand non-modular pipelines.

## Possible Alternatives
A possible workaround is to wrap pipelines in a modular pipeline but this seems overly cumbersome and error prone.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by rashidakanchwala** [comment]
Hi there! The ability to collapse/expand modular pipelines stems from their parent/child nature. I'm uncertain how this functionality would apply to non-modular pipelines. Do you have any examples?

Recently, we implemented stateful URLs, enabling users to share/save URLs that preserve a filtered state of large pipelines by filtering through tags or node types. Would this feature address your needs?

**Comment by astrojuanlu** [comment]
> A possible workaround is to wrap pipelines in a modular pipeline but this seems overly cumbersome and error prone.

Hi @bpmeek, would you want to describe a bit more your struggles with nested pipelines through namespaces? (Refraining from calling them "modular pipelines" given that we're [sorting out our terminology](https://github.com/kedro-org/kedro/pull/3948))

Also, how do you imagine you could collapse pipelines?

**Comment by rashidakanchwala** [comment]
Closing this as for now. If you have any comments, let us know and we can reopen and look into it again.
