### ISSUE TITLE
Migrate demo.kedro.org from AWS to GitHub Pages

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1881]
## Description

We currently deploy our demo project on AWS by packaging the kedro-viz application into a Docker image, pushing it to Amazon ECR, and deploying it via Amazon Lightsail. We have AWS account dedicated to this and it's a bit difficult to manage. 

This ticket proposed to move our demo deployment process to GitHub Pages by leveraging the `kedro viz build` functionality and the `publish-kedro-viz` action and host it from there

cc - @idanov 
 
## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
How will experiment tracking be demoed on GitHub pages?
