### ISSUE TITLE
Kedro Viz & DeltaTableDataset: Unable to get file size. Object has no attribute '_protocol'

### ISSUE THREAD

**Issue by julio-cmdr** [kedro-org/kedro-viz#1893]
## Description
Hello!
I'm using a pandas.DeltaTableDataset and I'm getting the warning: `Unable to get file size for the dataset DeltaTableDataset(...): 'DeltaTableDataset' object has no attribute '_protocol'`.
I think this warning has been raised by kedro-viz.

After disabling auto-registered kedro-viz’ Hooks in settings.py, no further warnings are raised.

## Steps to Reproduce
1. Set a DeltaTableDataset in catalog.yml and use it as a node input.

## Your Environment

* Windows
* kedro-viz 9.0.0
* kedro 0.19.3
* kedro-datasets[pandas.DeltaTableDataset] 2.1.0
* Python 3.11

**Comment by astrojuanlu** [comment]
Hi @julio-cmdr, sorry for the slow reply. It's been a while, but do you think you could go back and give a full traceback of the error you get? Would help us understand how to fix it.

**Comment by astrojuanlu** [comment]
Warning comes from here

https://github.com/kedro-org/kedro-viz/blob/9996c9950f60810cdaeb7c439614597572354a71/package/kedro_viz/integrations/kedro/hooks.py#L151-L160

**Comment by SajidAlamQB** [comment]
Hi @julio-cmdr, I have not been able to re-create this error, would it be possible to get some more information.

**Comment by julio-cmdr** [comment]
Hi @SajidAlamQB.
A lot of datasets have an attribute called "_protocol". But DeltaTableDataset doesn't have it (check source code in [here](https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/kedro_datasets/pandas/deltatable_dataset.py)). I think this is the reason why this warning has been thrown

**Comment by ravi-kumar-pilla** [comment]
Hi @SajidAlamQB , I was responsible for using the private method to get the file size in the stats hook. I would request you to check if there are any alternatives in determining the file size and also refactoring the stats hook to avoid using private attributes. Thank you

**Comment by SajidAlamQB** [comment]
Thank you, I have a PR that will attempt to fix this, https://github.com/kedro-org/kedro-viz/pull/2174.

**Comment by astrojuanlu** [comment]
In line with what @ravi-kumar-pilla asked, is there a way we can make this a public, optional behavior of datasets?

For example, datasets now have a `preview` method. They could have a `get_info` method or similar.

Notice that in https://github.com/kedro-org/kedro-viz/issues/1714#issuecomment-2042964835 a user suggested using `_describe` for this. We ended up adding a `preview` method, but maybe we should try to unify all this "meta" information instead of adding more ad-hoc public methods.

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-viz/pull/2174
