### ISSUE TITLE
Improve Kedro-viz telemetry tracking in the codebase

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1900]
## Description

The Kedro-viz telemetry numbers seem very low. This ticket is to revisit telemetry and ensure that tracking is accurate and correct information is being recorded. 

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by astrojuanlu** [comment]
Addressed in #1995

**Comment by yetudada** [comment]
I have a query about this; I assumed there were two issues with tracking telemetry on Kedro-Viz: 

1. We’re not sure if telemetry is properly activated when users have opted in for tracking (the old way) 
2. There’s a mess with how components/features are named on Kedro-Viz, making it hard to tell what is and what is not being used once telemetry is active 

Did we ever understand 1.?

**Comment by rashidakanchwala** [comment]
1. For one; i did live data tracking on both Production and Development server and tested all the click events on Kedro-viz that we were tracking. We were tracking everything but the naming wasn't correct/clear so we fixed that in #1995

**Comment by rashidakanchwala** [comment]
I don't know if this issue is closed though; as we still need to create a proper heaps dashboard. A part of this issue is closed: improving tracking to the code.

**Comment by yetudada** [comment]
@rashidakanchwala Okay, that’s fair. Maybe what would be helpful is if you could complete the description for the GitHub issue and describe what needs to be done, because they can be sub-tickets of this one. 

Also, this means we should assume that the ratio of Framework to Kedro-Viz users is actually correct, based on what you found?

**Comment by rashidakanchwala** [comment]
Yes, I believe so. Besides, we check this ratio through CLI commands rather than UI interactions. Specifically, we track unique users who run `kedro run` and determine how many of them also run `kedro viz` or `kedro viz run` 

Agree, improve telemetry is more of an epic which we need to break down into multiple tickets. I will do that now.

**Comment by rashidakanchwala** [comment]
closing this as 99 tickets later we have a follow up ticket :) #1999
