### ISSUE TITLE
Breakdown flowchart models into separate files

### ISSUE THREAD

**Issue by ravi-kumar-pilla** [kedro-org/kedro-viz#1909]
## Description

The flowchart model file has 1066 lines of code and this needs to be breakdown for easy maintenance and readability

## Context

As above

## Possible Implementation

Create separate files each for a class within flowchart folder under models. 

```yaml
models
  flowchart
    graph_edge.py
    graph_node.py 
```

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by rashidakanchwala** [comment]
Great idea, should we break it into edges, nodes, and metadata?

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-viz/pull/2144
