### ISSUE TITLE
On kedro-viz UI startup error: instance.graphNew is not a function

### ISSUE THREAD

**Issue by jitu5** [kedro-org/kedro-viz#1913]
## Description
Error occures on running Kedro-viz UI locally 

_TypeError: instance.graphNew is not a function_
<img width="1799" alt="Screenshot 2024-05-20 at 4 06 13 p m" src="https://github.com/kedro-org/kedro-viz/assets/38945204/cb9d1551-c689-4713-a7fc-cfc97aee3a4c">

## Steps to Reproduce

1. Checkout kedro-viz locally
2. `npm install`
3. `make build`
4. `make run` and `npm start`
5. Till this point it works as expected 
6.  kill process `make run` and `npm start`
7.  Re run `make run`  and `npm start`

## Context
This could be related to Node 18 / react-scripts update.

## Expected Result
It should run successfully every time after `make run` & `npm start`

## Actual Result
After rerun of `make run`  it gives below error

```
graph.js:36 Uncaught (in promise) TypeError: instance.graphNew is not a function
    at layout (graph.js:36:1)
    at worker.js:58:1
    at graph.js:53:1
    at Object.dispatch (index.js:16:1)
    at Object.dispatch (<anonymous>:6:7384)
    at store.js:19:1
    at index.js:17:1
    at Object.dispatch (redux.js:297:1)
    at s (<anonymous>:3:5093)
    at index.js:20:1
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version:
* NodeJS version used (if relevant):
* Kedro version used (if relevant):
* Python version used (if relevant):

## Checklist
- [ ] Include labels so that we can categorise your issue

**Comment by rashidakanchwala** [comment]
I got this error as well. I thought it was something to do with my PR.
