### ISSUE TITLE
Enable user to disable preview for all from setting panel(UI) when running `kedro viz run`

### ISSUE THREAD

**Issue by jitu5** [kedro-org/kedro-viz#1921]
## Description
This feature will help users to control data preview for all the nodes from setting panel of Kedro-Viz when running `kedro viz run`.

## Context
After running Kedro-Viz locally by `kedro viz run` command, Dataset preview for all the nodes will be enabled by default but user will be about to enable/disable from Kedro-Viz setting panel.

## Possible Implementation
-Add toggle button option in setting panel
-Pass current toggle value to getNodeById API call

## Checklist

- [X] Include labels so that we can categorise your feature request

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-viz/pull/1977
