### ISSUE TITLE
Toggle off pretty names by default in updated settings panel

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-viz#1931]
## Description
[TBC]

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-viz/pull/1958
