### ISSUE TITLE
Update Kedro-viz architecture diagram

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1957]
## Description

The architecture diagrams for both the Kedro-viz frontend and backend are quite outdated and need updating. This time, instead of creating a static image with draw.io, let's use a MIRO board for the architecture. This will allow us to make updates more frequently and easily.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by astrojuanlu** [comment]
The architecture diagram and other info is linked from https://github.com/kedro-org/kedro-viz/wiki/Architecture

**Comment by Huongg** [comment]
Here is my last updated diagram on how the flowchart works from FE, and the python server from @rashidakanchwala. It also includes the chart for the layout calculation

https://miro.com/app/board/uXjVKBhcnQY=/?share_link_id=508990102999

**Comment by SajidAlamQB** [comment]
Completed:

https://github.com/kedro-org/kedro-viz/pull/2183

and

https://miro.com/app/board/uXjVKhNg1RE=/?moveToWidget=3458764606468376036&cot=10
