### ISSUE TITLE
Tags filter shows tags from other pipelines

### ISSUE THREAD

**Issue by gitgud5000** [kedro-org/kedro-viz#1962]
## Description
Kedro Viz is showing tags in the filter that are not present in the selected pipeline being displayed. It shows tags that are present in other pipelines. This list should be limited to the applicable tags of the selected pipeline only.

## Context
This bug affects the usability of the tag filtering feature in Kedro Viz. When working on a specific pipeline, seeing tags from other pipelines creates confusion and makes it harder to filter the nodes accurately.

## Steps to Reproduce

1. Open Kedro Viz.
2. Select a specific pipeline to view.
3. Open the tags filter dropdown.
4. Observe that tags from other pipelines are also displayed.

## Expected Result
The tags filter should only display tags that are present in the currently selected pipeline.

## Actual Result
The tags filter displays tags from all pipelines, not just the selected one.

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Operating system and version: Ubuntu 22.04
* Kedro version used (if relevant): 0.19.6
* Python version used (if relevant): 9.1.0

## Checklist
- [ ] Include labels so that we can categorise your issue

**Comment by rashidakanchwala** [comment]
We tried this on https://demo.kedro.org/ and were not able to replicate this issue. Could you provide additional details? Thanks.

**Comment by rashidakanchwala** [comment]
hi @gitgud5000, anything on above ?

**Comment by gitgud5000** [comment]
@rashidakanchwala When a dataset `Data_1` originates in, say, `Pipeline_A`, in a `node_x`, and either is tagged `"AAA".`

When `Data_1` is referenced in `Pipeline_B` as an input, the `"AAA"` tag, applying only to `Data_1`, shows up in the tag filters (panel to the left) of `Pipeline_B` visualization.

**Comment by rashidakanchwala** [comment]
Hi @gitgud5000,

We’re unable to replicate the issues you reported here and in #2156 on our end. If you’re part of the Kedro Slack organization, would you be open to a quick huddle or Zoom call? This would allow us to review the bugs on your screen and gain a clearer understanding of the issues.

Let us know if this works for you!

**Comment by rashidakanchwala** [comment]
Hi @gitgud5000,

We’re unable to replicate the issues you reported here and in #2156 on our end. If you’re part of the Kedro Slack organization, would you be open to a quick huddle or Zoom call? This would allow us to review the bugs on your screen and gain a clearer understanding of the issues.

Let us know if this works for you!
