### ISSUE TITLE
Document stateful URLs

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-viz#1979]
As per title :)

Adding this based on https://github.com/kedro-org/kedro-viz/issues/1673#issuecomment-2222467015 without thinking too much, but more generally should we have a _proper_ User Manual/User Guide of Kedro-Viz?

**Comment by rashidakanchwala** [comment]
this is done. https://docs.kedro.org/projects/kedro-viz/en/stable/share_kedro_viz.html#filtering-and-sharing-kedro-viz-pipelines
