### ISSUE TITLE
Unable to run Kedro in Azure with SQLiteSessionStore

### ISSUE THREAD

**Issue by Dekermanjian** [kedro-org/kedro-viz#1991]
## Description
Whenever I try to load the catalog either using a jupyter lab or IPython interface I get the following error:
Failed to instantiate session store of type 'kedro_viz.integrations.kedro.sqlite_store.SQLiteStore'

## Context
I am not able to set up a new project on the cloud (Azure compute instance)

## Steps to Reproduce
1). Create a new kedro project on the cloud
2). Run kedro ipython

## Expected Result
The catalog/context should load like it normally does in local development

## Actual Result
An error message is thrown about a locked SQLAlchemy database with the following error:
Failed to instantiate session store of type 'kedro_viz.integrations.kedro.sqlite_store.SQLiteStore'

```
Failed to instantiate session store of type 'kedro_viz.integrations.kedro.sqlite_store.SQLiteStore'
```

## Your Environment
Brand new conda env with fresh installation of kedro 

* Kedro version used (`pip show kedro` or `kedro -V`): 0.19.2
* Python version used (`python -V`): 3.10.13
* Operating system and version: Cloud compute running linux

**Comment by gyasibaaye** [comment]
Any updates on this issue? Commenting out the lines mentioned below does work, but that shouldn't be necessary to begin

> same here with version 0.19-3 (no pb with 0.18.14) on some cifs drives (linux), solved the problem by commenting in settings.py : from kedro_viz.integrations.kedro.sqlite_store import SQLiteStore # noqa: E402 SESSION_STORE_CLASS = SQLiteStore I guess that's not the right solution but so far....

**Comment by ravi-kumar-pilla** [comment]
Hi , 

Sorry for the delayed response. Thanks for raising the issue. There seems to be multiple processes trying to access SQLite database that is initialized in `settings.py` for Kedro-Viz Experiment Tracking and SQLite allows one writer at a time.

At this moment, I do not have a permanent fix but we will take this as priority in the next sprint. For now, the work-around would be to comment out `SESSION_STORE_CLASS = SQLiteStore` instantiation in `settings.py`, if you are not using Experiment Tracking on Kedro-Viz.

Thank you

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-viz/pull/2131
