### ISSUE TITLE
Refactor front-end component Command Copier 

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1994]
## Description

The UI component Command Copier is currently using Metadata Value, which is specific to the Metadata component. Ideally, a UI component should be reusable across multiple higher-level components and should remain a pure component. However, in this case, it is using a component from a higher-level component, which is not clean.

This ticket is to refactor the Command Copier component to ensure it is a pure component and not dependent on higher-level components like Metadata Value.

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by Huongg** [comment]
hey I'll take this one as I've already done some of the refactor it in my slicing/run-command work
