### ISSUE TITLE
Reload the page resets back the default pipeline

### ISSUE THREAD

**Issue by Huongg** [kedro-org/kedro-viz#1997]
## Description
When you're in any other pipeline view rather the default pipeline, if you load the URL again, it will reset to the default page

https://github.com/user-attachments/assets/18414bc9-3468-49b2-9a76-3da826943f04

## Context
I'm unable to share a specific pipeline view with anyone through the URL as it always takes me back to the default pipeline

## Expected Result
If the pipeline view should be the same as `pid` when reload the page and `pid` should not always set back to be the default one

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version:
* NodeJS version used (if relevant):
* Kedro version used (if relevant):
* Python version used (if relevant):

## Checklist
- [ ] Include labels so that we can categorise your issue

**Comment by rashidakanchwala** [comment]
Look at https://github.com/kedro-org/kedro-viz/issues/1879

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-viz/pull/2041
