### ISSUE TITLE
Reuse LSP server from Kedro Extension for "go To Definition" and "Go to reference" action from Webview.

### ISSUE THREAD

**Issue by jitu5** [kedro-org/kedro-viz#2024]
## Description
Currently, the "Go To Definition" and "Go to Reference" features are not fully integrated with the Kedro extension. To enhance the development experience and increase productivity, we propose reusing the Language Server Protocol (LSP) from the Kedro extension for these actions.

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
We aim to create specific VS Code commands that handle "Go To Definition" and "Go to Reference" actions. These commands will interface with the underlying LSP implementation in the Kedro extension.

- Command Creation:
  - Create two VS Code commands:
    - kedro: Go to definition
    - kedro: Go to reference
  - These commands will accept parameters (e.g., a string representing the target entity).

 - Command Workflow:
  - Request Flow: When a visual component is clicked, it will trigger the corresponding VS Code command.
    - Request Path: React (Frontend) -> VS Code Command -> LSP Client -> LSP
  - Response Flow: The LSP will process the request and return the appropriate response.
    - Response Path: LSP -> VS Code Client

This issue is linked to parent ticket https://github.com/kedro-org/kedro-viz/issues/1968

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by noklam** [comment]
Completed in https://github.com/kedro-org/vscode-kedro/issues/56
