### ISSUE TITLE
QA: slicing pipeline feature

### ISSUE THREAD

**Issue by Huongg** [kedro-org/kedro-viz#2026]
## Description
Since this is a brand new feature, it will require intensive QA from the team. 

Please follow these steps during QA:

- Feature Branch for Testing: https://github.com/kedro-org/kedro-viz/pull/2036

- Latest Design Reference: Refer to the latest design mockups available on [Figma](https://www.figma.com/design/3kSpvIO1veLKfy9qHxuXwF/Kedro-WIP?node-id=1469-56945&t=BnwugWfm9kt89HaP-0) for visual and functional guidance.

**Comment by astrojuanlu** [comment]
Closing!
