### ISSUE TITLE
Refactor `preview toggle ` feature 

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#2042]
## Description

This ticket is to refactor the `preview datasets toggle` setting feature to handle logic for previews from FE instead of making BE calls. 

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Expected Result
Tell us what should happen.

## Actual Result
Tell us what happens instead.

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version:
* NodeJS version used (if relevant):
* Kedro version used (if relevant):
* Python version used (if relevant):

## Checklist
- [ ] Include labels so that we can categorise your issue

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-viz/pull/2067
