### ISSUE TITLE
Test Kedro Viz in VSCode implementation with multiple Kedro project 

### ISSUE THREAD

**Issue by jitu5** [kedro-org/kedro-viz#2046]
## Description

Kedro Viz in VSCode implementation is almost done with some methods `load_and_populate_data` and  `get_json_data` from `kedro_viz.server` and `kedro_viz.api.rest.responses`  from Kedro-Viz python package. To make sure VSCode extension works with every Kedro project and if not we do proper error handling in Kedro extension. 

## Context
We are using `load_and_populate_data` and  `get_json_data` from `kedro_viz.server` and `kedro_viz.api.rest.responses`  from Kedro-Viz python package to get json data from current Kedro project.

Note:
- Testing with Kedro Viz lite version to avoid any dependency issue.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by rashidakanchwala** [comment]
@jitu5 , is this done ?
