### ISSUE TITLE
Kedro-Viz mistakenly uses existing service

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-viz#2052]
## Description
While reviewing https://github.com/kedro-org/kedro-viz/pull/1966, I found something funny: if there is an existing Kedro Viz server running, `kedro viz run` will open that one.

## Context
I was trying to evaluate the behavior of `kedro viz run --lite`, and the result was that I was getting redirected to the non-lite version.

## Steps to Reproduce

1. Launch `kedro viz run` in one terminal
2. Launch `kedro viz run` in another terminal

## Expected Result
Either
- the second `kedro viz run` complains that the port is in use, or
- the second `kedro viz run` gets launched in another port

## Actual Result
`kedro viz run` redirects me to the existing server.

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-viz/pull/2176
