### ISSUE TITLE
Disable Slicing Feature for VSCode Extension 

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#2068]
## Description

For now; we want to disable slicing feature when Kedro-viz is used as a react component especially when it is being embedded in VsCode. 

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by astrojuanlu** [comment]
Closed in #2072
