### ISSUE TITLE
Unclear dataset type

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-viz#2071]
## Description
If I have a `polars.CSVDataset` and a `pandas.CSVDataset`, both display just `CSVDataset` on the sidebar.

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce

1. `kedro new --name=kedro-preview --tools=viz,data --example=y`
2. Replace one of the datasets with `polars.CSVDataset` and install `kedro-datasets[polars]
3. `kedro viz run`

## Expected Result
I expected to see the full dataset qualifier.

## Actual Result
I see only the class name.

![image](https://github.com/user-attachments/assets/d73a32bd-0b73-448a-8ab0-53e5655850e6)

(no preview because it's not a pandas dataset)

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version:
* NodeJS version used (if relevant):
* Kedro version used (if relevant):
* Python version used (if relevant):

## Checklist
- [ ] Include labels so that we can categorise your issue

**Comment by rashidakanchwala** [comment]
this should be a quick fix.

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-viz/pull/2136
