### ISSUE TITLE
Document Kedro-Viz python version support policy

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#2086]
## Description

Kedro-viz will follow the Kedro Framework Python version policy, which means it will support all Python versions that are actively maintained by the CPython core team. Once a Python version reaches its end of life,  we will stop supporting it in kedro-viz without considering it a breaking change. This ensures that Kedro-viz will remain compatible with all Kedro projects, even for users on older supported Python versions.

**Comment by ravi-kumar-pilla** [comment]
Hi @rashidakanchwala , I think README.md should be a good place, similar to kedro - https://github.com/kedro-org/kedro?tab=readme-ov-file#python-version-support-policy

Do you mean to add it in docs other than README ?

**Comment by merelcht** [comment]
Just to clarify and have it documented somewhere: does this mean `kedro-datasets` will need to follow the more conservative policy again as well or can Viz now handle it if datasets drops support for a Python version?

**Comment by merelcht** [comment]
> Deprecation warnings will be issued in advance for any features or Python versions that are being removed.

How do you plan to do this? In a Slack announcement or inside the actual code? We never do this in Kedro Framework.

**Comment by rashidakanchwala** [comment]
Done here #2139
