### ISSUE TITLE
Telemetry:  investigate why demo.kedro.org is not flowing to Snowflake

### ISSUE THREAD

**Issue by Huongg** [kedro-org/kedro-viz#2158]
## Description
At the moment, we’re not seeing any data flowing from demo.kedro.org to Snowflake, even though it appears to pass through Heap. This issue is to investigate the cause of this issue.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by rashidakanchwala** [comment]
Weird, I can do this, when I use demo.kedro.org, and turn on live data feed.

**Comment by tynandebold** [comment]
Adding another data point: Heap does send events from the demo.kedro.org page.

<img width="948" alt="image" src="https://github.com/user-attachments/assets/13ec566a-7c4b-40c5-9a26-0bc6c8c94d42">

**Comment by Huongg** [comment]
hmm so it seems like it does send to heap, but somehow nothing shows in snowflake. As i just see the data from the last 2 months, and they are mainly just localHost or github page. Any idea why this would happened @rashidakanchwala @tynandebold  🤔 

<img width="655" alt="Screenshot 2024-10-29 at 09 47 53" src="https://github.com/user-attachments/assets/3aabe250-18ec-49f9-8205-0dab55e39fcd">

**Comment by rashidakanchwala** [comment]
hey I think this is just the data preview, and it doesn't show all the rows. Maybe you need to write filter query to see when landing page is 'demo.kedro.org'

**Comment by Huongg** [comment]
hey i think @astrojuanlu also confirmed that he couldn't see the demo page from the landing page when he did the query https://github.com/kedro-org/kedro-viz/issues/2140

> I'm not seeing https://demo.kedro.org/ in the top list of landing pages, which is interesting to say the least:
LANDING_PAGE,COUNT
127.0.0.1/,54765
localhost/,1822
127.0.0.1/experiment-tracking,357
anasaito-alpha-lineage-x6qqx4593p59q-4141.githubpreview.dev/,299
deepyaman.github.io/jaffle-shop/,162
172.19.113.195/,139
0.0.0.0/,108
133.127.13.9/,108
4141-cs-697995841852-default.cs-us-central1-pits.cloudshell.dev/,107
4141-cs-200f5089-bab4-4372-bef8-0b4fd0d92189.cs-us-east1-pkhd.cloudshell.dev/,65

**Comment by rashidakanchwala** [comment]
@Huongg , i think in that case we need to open an issue to investigate why isn't the heap data reflected in snowflake and close this one, or update it correctly. 

cc - @astrojuanlu

**Comment by Huongg** [comment]
yup i can update the description on this ticket if it's easier?

**Comment by astrojuanlu** [comment]
One surprising thing we're observing is that there's lots of `pageviews` associated with `demo.kedro.org` ✔️  but zero "interaction events" 🤔

**Comment by rashidakanchwala** [comment]
@Huongg , @astrojuanlu 

Could you confirm if the table missing demo.kedro.org details was `Viz_interactions_table`? I’ve identified the reason for the missing information: the event was set up to track clicks on elements with `data-heap-event`, but `demo.kedro.org` uses `data-test` attributes instead, as it’s the latest version of Kedro.

By default, Heap generates a **generic click event** for every click. In my opinion that 'Generic Click' Heap table is the best to follow, and we can use the `hierarchy` variable within it to identify which specific event was clicked.

let me know what you think?  Here's a screenshot of what `viz_interactions_table` tracks
<img width="938" alt="Screenshot 2024-11-04 at 14 49 31" src="https://github.com/user-attachments/assets/7f71471c-1314-47aa-8877-dafadad42ddb">

**Comment by Huongg** [comment]
hey great work @rashidakanchwala , i can confirm the table is called `VIZ_INTERACTION_EVENT_2` in snowflake. and I can now see your new sync table called `KEDRO_VIZ_USER_INTERACTIONS_GENERIC_CLICK_EVENT`, which is what we need ❤️

**Comment by rashidakanchwala** [comment]
For the GENERIC_CLICK_EVENTS table, we need to create two custom columns, either in Tableau or Snowflake, as follows:

Extract Data Heap Events:
```
REGEXP_EXTRACT([Heap Hierarchy], "\[data-heap-event=([^;]+)\]")
```
Extract Data Test Events:
```
REGEXP_EXTRACT([Heap Hierarchy], "\[data-test-event=([^;]+)\]")
```

The union of these columns will capture all relevant events, though the naming conventions may vary and require some cleanup. We can also consider @astrojuanlu 's approach by focusing specifically on newer Kedro-Viz versions, using only data-test events for consistency.

also cc : @lid-rs

**Comment by rashidakanchwala** [comment]
@lid-rs , @astrojuanlu  -- let me know if this is fine, and I can close the issue. I looked more into details - the above and the data is same as HEAP.

**Comment by astrojuanlu** [comment]
Amazing, thanks @rashidakanchwala!

Can we then unsync `VIZ_INTERACTION_EVENT_2` and focus on `KEDRO_VIZ_USER_INTERACTIONS_GENERIC_CLICK_EVENT`?

About creating custom columns, 

> Creating a dynamic column in Tableau is a good quick and dirty solution but eventually the Single Source of Truth should be a "gold" table in Snowflake, see https://lakshmanok.medium.com/what-goes-into-bronze-silver-and-gold-layers-of-a-medallion-data-architecture-4b6fdfb405fc
> 
> That's out of the scope for this ticket anyway.

_Originally posted by @astrojuanlu in https://github.com/kedro-org/kedro-viz/issues/2140#issuecomment-2444929537_

**Comment by rashidakanchwala** [comment]
I have done so. I reckon the tables will still exist in snowflake just not updated. This will create some noise, should we manually delete/archive/hide them or just ignore them? 

<img width="1158" alt="Screenshot 2024-11-05 at 09 30 06" src="https://github.com/user-attachments/assets/a1778291-dfe5-4c19-bc23-a936e14b1de1">

**Comment by astrojuanlu** [comment]
For now let's ignore them, I'd say.

This now seems to be working:

<img width="1094" alt="image" src="https://github.com/user-attachments/assets/ec3ee202-8cf2-49b9-b701-ab9b02f2a5dc">

Closing!
