### ISSUE TITLE
[KED-931] Option to include visualized pipelines in the generated document

### ISSUE THREAD

**Issue by lorenabalan** [kedro-org/kedro-viz#31]
Originally raised here: https://github.com/quantumblacklabs/kedro/issues/56 by @Minyus 
I've updated the title with our internal ticket number to keep track of this more easily. :)

## Description
An option to include the image of visualized pipelines in the Sphinx document generated by `kedro build-docs` command

## Context
kedro-viz offers `kedro viz` command that can generate interactive visualized pipelines. 

This visualization is very useful to explain to the stakeholders and it is even nicer to automate the manual operation to run `kedro viz` command, access the URL, take a screenshot, and paste it in the document.

```
![image](https://user-images.githubusercontent.com/33908456/61184262-542f8000-a67e-11e9-872e-3fa40e31b81c.png)
```

## Possible Implementation
Programmatically communicate with the kedro_viz.server.

## Possible Alternatives
Use a graph visualization tool such as `graphviz`.

**Comment by WaylonWalker** [comment]
It should be completely possible to statically render the pipeline visualization into its own page (i.e. /viz ) then it could be iframed into any page.

**Comment by nchelaru** [comment]
This is a great idea! Any updates on this?

**Comment by yetudada** [comment]
Hi @nchelaru! We're going to look at this story in the context of a larger refactor of Kedro-Viz to make it more modular. Modularity of the flowchart component will make this easier to achieve. @limdauto can explain more 😄

**Comment by ultraxav** [comment]
Hi everyone! I currently use Kedro + viz + mlflow

What I did, is I added pipeline.json to my catalog, nodes, pipeline then I run:

`kedro viz --save-file ./data/08_reporting/pipeline.json; kedro run --pipeline data_science` (as an example)

This way kedro loads it and then mlflow registers it as an artifact
