### ISSUE TITLE
[KED-3034] If a dataset is prefixed with the word 'params' it is treated as a parameter and only shows on the expanded view

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro-viz#621]
## Description
As users start to experiment with the new `tracking.JSONDataSet` they may name their catalog entries something like `params_random_forest` and Kedro Viz will currently mistakenly count them as a parameter type node when they are in fact a regular data node.

## Steps to Reproduce

1. Name a dataset something prefixed with 'params'
2. Visualise

## Expected Result
Should appear as a data node like the 'hyperparams_linear` node below

## Actual Result
![image](https://user-images.githubusercontent.com/35801847/140928526-70fa46f6-9ca9-440e-ac85-50d5760751d2.png)

Node only visible in the expanded parameter view - also impossible that a parameter should be an output to a node

**Comment by studioswong** [comment]
good one @datajoely , let's pop this into our backlog 👍
