### ISSUE TITLE
[KED-3033] Kedro Viz not working with curry or partial functions

### ISSUE THREAD

**Issue by bpassanezi** [kedro-org/kedro-viz#635]
## Description
Hello! I am having an error when clicking on a node in `kedro viz` that has a partial or curry function. Besides the error, the visual interface does not show the inputs or parameters.

```
AttributeError: 'functools.partial' object has no attribute '__closure__'
```
This is the error I get when using partial functions.

```
AttributeError: 'curry' object has no attribute '__closure__'
```
This is the error I get when using curry functions.

I have tried using `update_wrapper` and it is still raising the same error :/ .
## Context
I am trying to run `kedro viz` with a project that uses multiple partial functions,.

## Steps to Reproduce

1. Define partial function on node
2. Run kedro viz
3.  Click on function node
4. Watch logs

## Expected Result
Run as normal.

## Actual Result
The side bar with the parameters and input does not load.

```
-- If you received an error, place it here.
```
AttributeError: 'functools.partial' object has no attribute '__closure__'
```
-- Separate them if you have more than one.
```
AttributeError: 'curry' object has no attribute '__closure__'
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version: 

## Checklist
- [ ] Include labels so that we can categorise your issue

**Comment by limdauto** [comment]
@bpassanezi thank you for the report. We will look into it soon.
