### ISSUE TITLE
Allow saving pipeline to svg and png

### ISSUE THREAD

**Issue by danielgafni** [kedro-org/kedro-viz#638]
## Description
The `kedro viz export` command would allow visualizing the pipeline DAG from the command line.

Options:
 - `--pipeline` pipeline to export
 - `--format` [png, svg]
 - `--resolution` if png format is used
 - `--output` output path

## Context
This can be used in:
 - CI pipelines 
 - pre-commit hooks (always up to date project documentation)
And other automation. 

- [x] Include labels so that we can categorise your feature request

**Comment by yetudada** [comment]
Hi @danielgafni! Thanks for raising this feature. I wanted to find out what you would expect to happen when you've run this command. Is it that you're trying to "screenshot" a version of the pipeline?

**Comment by danielgafni** [comment]
Yeah, something like this. 

Could be useful for automatic documentation updates (for example, push the image to Confluence).

**Comment by tynandebold** [comment]
Hi @danielgafni. Thank you for raising this. We're going to close this issue for now and will certainly circle back in the future if additional demand for this arises.

In the meantime, please note that you can download the pipeline visualization from the Kedro-Viz interface (though that's a manual process, not programatic).

**Comment by AntonyMilneQB** [comment]
Given that we already have `pipeline` and `save-file` flags in `kedro viz`, I would suggest we implement this as:
* `kedro viz --save-file=file.json` 
* `kedro viz --save-file=file.png`
* `kedro viz --save-file=file.svg`

and work out the correct format from the file extension. If no extension is given the use json as we do currently.

I'm not sure how easily we will be able to directly access to export functionality from the backend side though. Currently it's all buried a bit in `exportGraph`.

**Comment by tynandebold** [comment]
More desire for this from users:

- https://quantumblack.slack.com/archives/C7JTFSFUY/p1646304453897049
- https://quantumblack.slack.com/archives/C7JTFSFUY/p1621959427119500

**Comment by Huongg** [comment]
After investigating the possibility of using Selenium to initiate Kedro-viz and subsequently selecting the export button, we have come to the realization that it would be highly complex from a technical standpoint. Additionally, we believe that the most suitable method for exporting the SVG or PNG would be through the user interface, as it involves taking a screenshot of the current visualization browser at the time. Therefore, we have decided to temporarily close this matter.

- Below are some of the steps on how to export the pipeline to svg or png via kedro viz UI


<img width="1777" alt="Screenshot 2023-05-11 at 13 14 04" src="https://github.com/kedro-org/kedro-viz/assets/32060364/e57bb7e1-42cd-4dd6-a05c-1ddfa25aaff8">



<img width="1787" alt="Screenshot 2023-05-11 at 13 14 44" src="https://github.com/kedro-org/kedro-viz/assets/32060364/5ccfb922-61ca-4efc-a804-26e1914f3826">
