### ISSUE TITLE
[KED-3036] Pretty name doesn't change function names

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro-viz#656]
## Description
If you disable pretty-naming functions are still TitleCased:

![image](https://user-images.githubusercontent.com/35801847/143617116-18bc2f77-11ed-4e2f-98cd-dfcc2a5df4bc.png)

## Expected Result
Function should be in `snake_case`

**Comment by limdauto** [comment]
This is now fixed. Thanks @rashidakanchwala
