### ISSUE TITLE
[KED-3037] Expand the number of Visualizations supported by Plotly

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro-viz#658]
## Description
> Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

Currently Viz only supports a small subset of Plotly.js plots, because there is a push to limit the bundle size. It would be useful to understand two things:

(1) How difficult it is to make the bundle size and optional dependency of Kedro Viz?
(2) Which plots do users want to use and can't?

## Possible Implementation
> (Optional) Suggest an idea for implementing the addition or change.

Perhaps there is a way of doing this in the same way we do `pip install "kedro[pandas]`" on the python side.

**Comment by yetudada** [comment]
Closing in favour of #782
