### ISSUE TITLE
[KED-3039] Kedro Viz cuts off exported png/svg when datasets are hidden

### ISSUE THREAD

**Issue by alexanderkeijser73** [kedro-org/kedro-viz#679]
## Description
I found that when I disable datasets in the "element types" menu, Kedro viz cuts off the left side of the diagram when exporting to png or svg. This causes some edges in the diagram to be be cut off as a result.

## Context
I was trying to export the kedro viz diagram for some of my pipelines for including them in my documentation. I would like to use the export function instead of a screenshot because this allows me to export as SVG.

## Steps to Reproduce

1. Visualise a kedro pipeline using `kedro viz`
2. Disable datasets in the "element types" menu in the bottom left corner of the kedro viz ui
3. Export the diagram to png or svg using the export button

## Expected Result
The exported diagram should be exported as svg or png, with all nodes and edges visible

## Actual Result
The exported diagram has some cut off edges, because the left side of the diagram is cut off

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: Google Chrome Version 91.0.4472.101 (Official Build) (x86_64)
* Operating system and version: macOS Catalina 10.15.7
* NodeJS version used (if relevant):
* Kedro version used (if relevant): 0.17.6
* Kedro-viz version: 4.2.0
* Python version used (if relevant): 3.7.4

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by tynandebold** [comment]
Hey @alexanderkeijser73 thanks so much for the feedback. 

We're having some trouble reproducing this to actually see some cut off edges when we export the visualization.

Would you mind please adding some of the screenshots to this issue so we can see exactly what you're seeing?

**Comment by alexanderkeijser73** [comment]
Hey @tynandebold, thanks for your response! I understand, the issue seems to be quite specific to the pipeline I made, so it might be hard to reproduce. I have a screenshot here 

This is the pipeline that's causing the problem

![image](https://user-images.githubusercontent.com/18571614/149366748-237ad55e-908b-4a6c-b2f6-35b0f8ad6e4d.png)

When I export it as PNG, it comes out like this

![image](https://user-images.githubusercontent.com/18571614/149366843-118b1ff5-9c08-411b-b60a-1a619975a209.png)

If this isn't enough, we can try figuring out a way for you to reproduce this 👍

**Comment by tynandebold** [comment]
Excellent, thanks for this, @alexanderkeijser73. 

It's a very, very tall pipeline isn't it. Let me see if I can get something working on my end that will mimic what you have and see what happens.

**Comment by rashidakanchwala** [comment]
@richardwestenra  -- FYI.

**Comment by richardwestenra** [comment]
@rashidakanchwala If I recall correctly, we had that issue in the past and it was fixed, so it's possible that the fix has been reverted or a new similar issue has crept in. I don't recall the exact fix but it might have involved updating the chart size before exporting in `src/components/export-modal/export-graph.js` - that's where I'd look first. Sorry I can't give more guidance, it's been a while. Good luck!

**Comment by tynandebold** [comment]
Hi again, @alexanderkeijser73! I think we've fixed the issue. We'll do a release soon and when we do I'll ping you to see if what we implemented solved the problem you were seeing.

**Comment by alexanderkeijser73** [comment]
Great, thanks for the effort guys! I'll be sure to test with my oversized pipeline 😁

**Comment by tynandebold** [comment]
Hey @alexanderkeijser73 we've release `4.3.1` which has a fix for this issue. Please try to export your pipeline using that version of Kedro-Viz and let us know how it goes :)
