### ISSUE TITLE
Cannot install Kedro-Viz on Windows

### ISSUE THREAD

**Issue by limdauto** [kedro-org/kedro-viz#710]
## Description

Some users has reported problems with installing Kedro-Viz on Windows. Example:

![image (8)](https://user-images.githubusercontent.com/2032984/150346748-d6eb51ec-b961-4e8a-9eee-050266843d66.png)

* Python 3.8.10
* Windows 10 x64 (Microsoft Windows [Version 10.0.18363.1977])
* kedro-viz==4.0.1

## Context

I **think** this only happens when running `kedro install` instead of a normal `pip install`

## Steps to Reproduce

I need to reproduce this first.

## Expected Result
Tell us what should happen.

## Actual Result
Tell us what happens instead.

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version:
* NodeJS version used (if relevant):
* Kedro version used (if relevant):
* Python version used (if relevant):

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by tynandebold** [comment]
@MerelTheisenQB @AntonyMilneQB is `kedro install` deprecated? If so, I think we can close this issue.

**Comment by MerelTheisenQB** [comment]
Yes this was removed in kedro `0.18.0` in favour of `pip install -r src/requirements.txt`

**Comment by tynandebold** [comment]
Closing this, since `kedro install` is now deprecated in favor of `pip install -r src/requirements.txt`.
