### ISSUE TITLE
kedro viz won't work from commandline

### ISSUE THREAD

**Issue by eepgwde** [kedro-org/kedro-viz#736]
## Description
I try to run kedro viz from the command at the root of a kedro project.

    kedro viz --no-browser

## Context

If viz doesn't work, I can't see my pipeline graphs

## Steps to Reproduce

This is a working kedro installation. I have used viz before from jupyter with %run_viz but that is not working.

## Expected Result

A web-server appears on 4142 something else occupies port 4141

## Actual Result

This error. 

```
  File "/home/share/conda/envs/vega/lib/python3.8/site-packages/kedro/framework/session/session.py", line 48, in get_current_session
    raise RuntimeError("There is no active Kedro session.")
RuntimeError: There is no active Kedro session.
Error: There is no active Kedro session.
```

I have attached the full log. 
[kedro-viz.log](https://github.com/kedro-org/kedro-viz/files/8040745/kedro-viz.log)

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version:

Linux ip-10-136-18-153.eu-west-1.compute.internal 4.14.256-197.484.amzn2.x86_64 #1 SMP Tue Nov 30 00:17:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* NodeJS version used (if relevant):
* Kedro version used (if relevant):

$ kedro --version
2022-02-10 11:53:26,653 - kedro.framework.cli.hooks.manager - INFO - Registered CLI hooks from 1 installed plugin(s): kedro-telemetry-0.1.2
Kedro-Telemetry is installed, but you have opted out of sharing usage analytics so none will be collected.
kedro, version 0.17.6

* Python version used (if relevant):
1020$ which python
/home/share/conda/envs/vega/bin/python
(vega) walter-eaves@ip-10-136-18-153:~/src/vkh-prj-qa0/vkh
1021$ python -V
Python 3.8.12

pip list --verbose | grep kedro
kedro                             0.17.6      /home/share/conda/envs/vega/lib/python3.8/site-packages pip
kedro-telemetry                   0.1.2       /home/share/conda/envs/vega/lib/python3.8/site-packages pip
kedro-viz                         4.3.1       /home/share/conda/envs/vega/lib/python3.8/site-packages pip

## Checklist
- [ ] visualisation

**Comment by limdauto** [comment]
Oh no I'm so sorry this is a regression. We fixed this before in `4.0.0` but recent release re-introduced it. This has to do with the fact that you use `get_current_session` in your `register_pipelines`. You have 2 choices:

* Downgrade to `kedro-viz==4.0.0`
* Maybe don't use `get_current_session` in `register_pipelines`

Thanks for detailed logs btw. It's very helpful. I will patch this though.
