### ISSUE TITLE
Valid YAML when serlialised to JSON can produce something unrenderable

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#749]
(transfer from Jira, created by @datajoely)

Apparently this is valid YAML:

```yml
hello: .Inf 
```
This is also a valid Python float:

![image-2022-01-27-09-35-27-344](https://user-images.githubusercontent.com/16869061/155152758-891d44bf-f970-4031-9fe0-3328c5ed43b8.png)

However it isn't valid JSON. You end up with a blank Kedro-Viz:

![image-2022-01-27-09-35-40-358](https://user-images.githubusercontent.com/16869061/155152776-baeaa48d-36a4-4de5-986b-45aeeceac0ef.png)

**Comment by GeorgySk** [comment]
Is this issue really resolved? I'm getting a `ValueError: Out of range float values are not JSON compliant ` when using `.inf` in the latest version. Is this an expected behavior? If it is then, probably, it should be mentioned in the docs.

**Comment by AntonyMilneQB** [comment]
I think what's happened here is that it's fixed in `main` but not yet released. I'm not sure what the plan is for doing a release - @tynandebold? If you need it urgently then it is possible to install the unreleased kedro-viz but it's a bit of a faff.

**Comment by tynandebold** [comment]
We'll do a release late this week or early next.

@GeorgySk let us know if you need this sooner.
