### ISSUE TITLE
[FE] Change `Types` on Metadata Side Panel

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#752]
(transfer from Jira, created by @yetudada)

- We still have a mismatch with how terms on Kedro-Viz vs Kedro are called and one of the ways it shows itself it on the Metadata Side Panel.
- When you open the metadata side panel and see the `Type` entry we refer to `data` instead of `dataset` and `task` instead of `node`.
- This issue focuses on updating those entries: change `type: task` to `type: node` for Kedro Node node and remove `type: data` for dataset node. `type: params` remains unchanged.

![Screenshot 2021-07-06 at 16 55 37](https://user-images.githubusercontent.com/16869061/155162592-88fc8664-d66f-403c-92a9-a84a76d3bc80.png)

**Comment by studioswong** [comment]
@yetudada Just to clarify, are we changing `type: data` to `type: dataset` instead of removing this type as mentioned in the description?
