### ISSUE TITLE
[BE] Fix bug experiment data not showing on Windows

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro-viz#763]
## Description
Internal user Sanjay, reported a bug on Windows where his experiment data is being tracked properly, can be shown in the pipeline view, but doesn't appear in the experiment tracking view. 

## Context
Can't view experiment data. 

## Steps to Reproduce

1. Setup experiment tracking session store + datasets
2. `kedro run`
3. `kedro viz`

## Expected Result
The logged experiment data should appear in the experiment tracking view.

## Actual Result
Only the data from the session store is shown with the names of the tracked datasets, but not the actual content. 
![image (12)](https://user-images.githubusercontent.com/49397448/156147732-3cd27460-4b18-423b-8ddd-401353924258.png)

```
2022-02-10 16:27:39,359 - kedro_viz.api.graphql - WARNING - `C:\Users\s_hariharan\...\evaluation.json` could not be found
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: N/A
* Operating system and version: Windows
* NodeJS version used (if relevant): N/A
* Kedro version used (if relevant): N/A
* Python version used (if relevant): N/A

## Notes
@studioswong and I already had a stab at finding out what the issue is. It looks like the issue is in https://github.com/kedro-org/kedro-viz/blob/main/package/kedro_viz/api/graphql.py#L212, specifically the logic to check if the file exists: https://github.com/kedro-org/kedro-viz/blob/main/package/kedro_viz/api/graphql.py#L244.

We haven't fully verified this, but my guess is that for some reason this check doesn't pass on Windows and therefore no data is returned. The data was logged properly and the REST API does return it.  

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by rashidakanchwala** [comment]
Hi @MerelTheisenQB  do you know if Sanjay or his team had their pipeline-viz working on Mac. Also, do we have a Windows laptop in Kedro-team to test this ?

**Comment by rashidakanchwala** [comment]
@AntonyMilneQB  -- hey, I got Kedro-viz to run on my personal Windows Machine and I can confirm that experiment tracking doesn't work on Windows. I haven't gone deep into the code -- but I have realised that on Windows nothing is committed to the session_store.db on a kedro run -- it's empty.

**Comment by AntonyMilneQB** [comment]
@rashidakanchwala interesting 🤔  Let's take a look next week indeed!

**Comment by AntonyMilneQB** [comment]
Same issue reported here: https://github.com/kedro-org/kedro/discussions/1359
