### ISSUE TITLE
[BE] Write an integration test for Session Store

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#766]
(transfer from Jira, created by @rashidakanchwala)

Setup a proper Kedro project during test and test the session against that project properly (session-store, and others)

Update - Now that we have demo-mock in our Kedro-viz repo. We mock some session_store data in that Kedro project and write some intergrations tests to check 

- we can write to .db using session_store
- we can read to db using session_store
- we can update db using session_store. 

Note: make sure we also add a test to test this in a Windows env.

**Comment by rashidakanchwala** [comment]
I think we can close this ticket for now because with the new database stuff coming we might not be working with sessions anymore

**Comment by tynandebold** [comment]
Agree. Closing it now.
