### ISSUE TITLE
[KED-2567] [FE] Empty nodes / pipeline warning message

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#777]
(transfer from Jira, created by @studioswong)

Selecting both modular pipelines and tags on the sidebar will often result in empty nodes on the pipeline flowchart. We would need a warning message to indicate this situation. 

Messaging that can serve as inspiration but is definitely not the final wording: "Hey, this selection has nothing, please unselect your filters/modular pipelines". 

Requirements:
 * Get wording from @stichbury
 * Get design love from Gabriel Comym

Comment from @limdauto:
Also have a reset button in the warning message / in the sidebar

To reproduce:

<img width="362" alt="image" src="https://user-images.githubusercontent.com/16869061/157079964-4faf4b64-8b99-4211-8a23-b96c4dec988c.png">

**Comment by tynandebold** [comment]
There is a warning message that's been designed and is in Zeplin.

**Comment by yetudada** [comment]
Wording:

- Headline: "Oops, there's nothing to see here"
- Body: "This selection has nothing. Please unselect your filters or modular pipeline selection to see pipeline elements."
