### ISSUE TITLE
Extended support for plotly diagrams + Improved scope documentation of kedro's plotly support

### ISSUE THREAD

**Issue by cverluiseQB** [kedro-org/kedro-viz#782]
Hey team, 

thanks for the great tool.

Cross posting https://github.com/kedro-org/kedro/issues/1337.

## Description

I am trying to:
1. save a sankey diagram in Kedro
1. visualise a sankey diagram in Kedro viz. 
[note: turns out that this is not possible]

## Context

- The best way to visualize the output of the pipeline is a Sankey diagram.
- Unfortunately, neither`Plotly.JSONDataset` nor `plotly.PlotlyDataSet` support this kind of diagram

**tl;dr**: Currently Kedro Viz is limited to the basic diagrams that plotly.js includes in its basic version. 

## Possible Implementation

Overall, **my request** is:
- extend kedro's support non basic `plotly.*Dataset` (e.g. `HTMLdataset`)
- extend kedro-viz support accordingly
Seems to me that supporting (plotly) html dataset would make kedro/kedro viz much more versatile for diagram vi

## Possible Alternatives
**In the meantimes**, that would be nice to make clear in Kedro's doc that the plotly support is still limited and clearly state what can and cannot be done.

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by AntonyMilneQB** [comment]
FYI @rashidakanchwala 🙂 

Thanks for raising the issue @cverluise-qb! Just to understand: when you say it's not possible, the `plotly.JSONDataSet` should already be able to save the sankey diagram to a .json file correctly (and also load it back in your pipeline if the catalog entry is a node input). The problem is just that it doesn't render on kedro-viz, right?

Very related: https://github.com/kedro-org/kedro-viz/issues/658

**Comment by cverluise-qb** [comment]
> the plotly.JSONDataSet should already be able to save the sankey diagram to a .json file correctly. (...)The problem is just that it doesn't render on kedro-viz, right?

Yes! that's it.

**Comment by datajoely** [comment]
So I've done a little bit of analysis to compare the file sizes of various etc:

As per the [plotly docs ](https://github.com/plotly/plotly.js/blob/master/dist/README.md) (if I'm interpreting this correctly:

- The full plotly.js  library is 8.3 MB 
- The plotly.js basic library is 2.7 MB

Cross referencing with some of the most common libraries in our world:

- `kedro-viz==4.3.1` is 4.6 MB
- `plotly==5.6.0` is 8.6 MB
- `mlflow==1.24.0` 16.1 MB
- `pandas==1.4.1` 4.9 MB
- `scipy==1.8.0` 38.3 MB
- `kedro==17.7` 80.4 MB
- `tensorflow==2.80` 438.0 MB

If the question is adding the extra 5.6 MB I'm not sure if that will cause many problems. I may have misunderstood how the JS part works as well.

**Comment by AntonyMilneQB** [comment]
I've tried this out properly now by running `make package` and the increase in package size is even smaller than what Joel suggests above. Each row here gives the sizes of the [files distributed on PyPI](https://pypi.org/project/kedro-viz/#files). The top row is what we currently have (though weirdly the .tar.gz file I get is way bigger than the one on PyPI??).

|                            | kedro_viz-4.3.1-py3.8.egg | kedro_viz-4.3.1-py3-none-any.whl | kedro-viz-4.3.1.tar.gz |
|----------------------------|---------------------------|----------------------------------|------------------------|
| `plotly.js-cartesian-dist` | 4.6MB                     | 4.5MB                            | 11MB                   |
| `plotly.js-dist`           | 7.5MB                     | 7.4MB                            | 14MB                   |
| `plotly.js-dist-min`       | 6.2MB                     | 6.1MB                            | 12MB                   |

So the increase in .whl file size is 2.9MB if we switch to using the full `plot.js-dist` and only 1.6MB if we use the minified version (would that work? I'm not sure). Either way this is nothing in terms of Python package sizes, as @datajoely says.

I'm not sure what the argument against using the full library was in the past. Would there be some hit on kedro-viz frontend performance? I don't know. If the only reason before was Python package size then that doesn't seem like a problem at all to me.

**Comment by datajoely** [comment]
@limdauto do you have a view here?

**Comment by yetudada** [comment]
I'd love a final confirmation on final package size and then I'll be happy to give a go-ahead for this one. I'll also ask, is there a way for users to have documentation on how to use the full plotly library if we didn't make this change?

**Comment by datajoely** [comment]
My intuition is that it's beyond the knowledge of a regular python user to know how to extend this JavaScript stuff  - combined with the [reduction of filesize in core](https://github.com/kedro-org/kedro/issues/1410) this would be really neat.
