### ISSUE TITLE
Show Matplotlib dataset pngs in the metadata panel

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro-viz#783]
## Description

`PlotlyDataSet` is super cool but not the only way that data scientist make plots. Kedro also supports `MatplotlibWriter` which saves matplotlib plots (or ones from any other library based on matplotlib like seaborn) to a png. It would be awesome if when I click on a matplotlib dataset in kedro-viz it opened up a thumbnail of the image on the metadata side panel, which I could then click to make full screen. Very similar to how plotly datasets are handled, only it's just a static png file rather than an interactive plot.

To me this sounds quite straightforward to implement and would be a really nice feature, but very interested to hear what others think. @rashidakanchwala?

### Slight complication
`MatplotlibWriter` is a bit weird in that it can write to _multiple_ png files. In this case the `filepath` given in the catalog entry will refer to a directory that contains all the png files. Ideally kedro-viz would also be able to handle this case, but I think we would get most of the value just from handling the simple case where `filepath` is a single png file. So I would forget about this for the MVP anyway.

### Possible concern
Would this affect performance in some way if I have a pipeline with lots of plots? I don't know whether kedro-viz would preload all of the png files or whether a png file would only be requested when the user clicks on the dataset and the metadata panel pops up?

**Comment by rashidakanchwala** [comment]
Hey, I think offering support for matplotlib would be a simple extension. We just save the data as pngs and load it on Kedro-viz. So yeah, if there are lot of users then we should consider it.

**Comment by tynandebold** [comment]
Two thoughts:
- Users still need some of way to see that they're using a Matplotlib dataset on their flowchart.
- We need to workout what is the ideal behavior when we click on that dataset.
