### ISSUE TITLE
Add in text for users to reboot their Kedro-Viz after using the `expandAllPipelines` flag

### ISSUE THREAD

**Issue by studioswong** [kedro-org/kedro-viz#792]
## Description

The current settings panel does not have a 'Apply' button where settings are applied immediately on toggling the settings. However, the setup of some feature flags is designed to be implement on load, such as the `sizeWarning` and the newly introduced `expandAllPipelines` flags, which causes general confusion as toggling the settings on the settings panel would not cause the settings to be immediately reflected until the next refresh of the page.

Generally it is confusing for the user to confirm on whether the settings have been applied without the 'Apply and Close' button. 

 This is to report the need to implement a 'Apply' button for the panel to solve the need to reload the app on updating feature flag settings ( the button is present in the design for the settings panel [here](https://app.zeplin.io/project/5d5ea7a05efca76a74f7d0ea/screen/60b8f3490ce06f677d0843dd), QB access only)

## Context
Without the button, updating the feature flag settings would not allow the relevant features to be reflected until the app reloads. 

## Expected Result
A 'Apply and Close' button should be present, where on pressing the button it allows the app to reload and apply the behaviour introduced by the feature flags. 

## Actual Result
Currently, toggling the feature flag would not cause immediate effect until the user refreshs the app. 

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by tynandebold** [comment]
`Pretty Name` does actually change the state of the app when toggling between off and on. I wonder if we can do the same thing for the new `expandAllPipelines` flag?

**Comment by studioswong** [comment]
Unfortunately this cannot be applied to the `expandAllPipelines` flag as the setup for expanding all pipelines is applied during state initialisation and not through actions ( which the toggle for `Pretty Name` is done through actions) - expanding all pipelines in app will be a different feature on its own 😄 ( this is also the same case for the large pipeline warning as well). 

There is also another quick solution, which is to add the wording `(applies on refresh of app)` in the description of both experiment features). 

That said, I do agree with design that having a 'Apply Changes' button for the settings panel provides more clarity and assurance of applying the settings, especially given the panel is a modal - I will have a quick chat with design and we can decide on a the best solution.

**Comment by studioswong** [comment]
update: as per discussion in our team sprint planning, we will go for the quick win solution of modifying the description, and later on to implement the `expandAllPipelines` as a in-app state to allow the users to toggle the expansion of all pipelines within the app ( not just only on first load.) - that will be filed under a separate issue.

**Comment by tynandebold** [comment]
Closed with completion of #875.
