### ISSUE TITLE
Extend support to Python 3.9+

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro-viz#793]
Kedro 0.18 will support Python 3.9 and 3.10. Once it's released, we should try to achieve the same for kedro-viz.

Probably this will be straightforward but might require a bit of fiddling with dependencies.

**Comment by AntonyMilneQB** [comment]
Also revert this commit on kedro-starters: https://github.com/kedro-org/kedro-starters/pull/69/commits/b504251d94bcf5c36acee5e62eec3e6bd258215d

**Comment by yetudada** [comment]
This ticket is complete 🚀
