### ISSUE TITLE
How to best display tags with modular pipelines

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#795]
## Description

Kedro-viz doesn't filter on tags for modular pipeline nodes. If you add a tag on the modular pipeline and then you filter by that tag on Kedro-viz, the modular pipeline doesn't show on the kedro viz flow chart. 

![kedro-viz-tag-issue](https://user-images.githubusercontent.com/37628668/160404571-dfa1178b-882d-433b-8348-04f0f15bd1bf.gif)

## Steps to Reproduce

1. User tags something, e.g. with `data-processing`
2. The modular pipeline has data-processing nodes
3. The user specifically selects the `data-processing` tag and deselects the other tags, if present
4. The modular pipeline node disappears
5. The other child nodes that are visible on the flowchart

## Expected Result
You should still be able to see the modular pipeline node if required and group those child nodes within it.

## Actual Result
Couldn't see the modular pipeline node and everything was expanded out.

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version:
* NodeJS version used (if relevant):
* Kedro version used (if relevant):
* Python version used (if relevant):

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by tynandebold** [comment]
We keep revisiting and rehashing this one. We need some design investigation and also a meeting around what should and shouldn't be done here.

**Comment by tynandebold** [comment]
We need to add tags to modular pipelines so they don't disappear from the flowchart when a user is toggling tags.

A quick-win solution: a modular pipeline will inherit all tags present on the child nodes. Let's try out this solution now and see how it feels in our hands and on the screen.

**Comment by rashidakanchwala** [comment]
Linking user pain-points around tag filtering -  https://github.com/kedro-org/kedro-viz/issues/987
