### ISSUE TITLE
Release v4.4.0

### ISSUE THREAD

**Issue by studioswong** [kedro-org/kedro-viz#796]
## Description
Prepare and release v4.4.0 that incorporates the latest set of changes in Kedro-Viz in preparation for Brix integration ( a major Kedro-Viz user)

## Implementation
- Conduct thorough final technical and design QA
- On having obtained a approved PR for this release, cut a release following our typical release process. 

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by yetudada** [comment]
This ticket is complete 🚀
