### ISSUE TITLE
Upgrade demo-project to kedro 0.18

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro-viz#806]
Following the release of kedro 0.18, we should migrate our demo-project to 0.18 using the [release migration guide](https://github.com/kedro-org/kedro/blob/main/RELEASE.md#migration-guide-from-kedro-017-to-018). Note that the project's 0.17.6 requirement is specified in a few places.

Search through the repository for "0.17." just to check if there's anything else that needs updating (maybe in READMEs?). At a glance there shouldn't be much to do here.

**Comment by datajoely** [comment]
Happy to accept any PRs to https://github.com/datajoely/modular-spaceflights/ :) But I'll do it myself at some point, think the only real change will be `settings.py`?
