### ISSUE TITLE
Upgrade strawberry-graphql version

### ISSUE THREAD

**Issue by JasonTam** [kedro-org/kedro-viz#810]
## Description
The current requirement `strawberry-graphql~=0.93.14` pins `graphql-core = "~3.1.0"`  (https://github.com/strawberry-graphql/strawberry/blob/b69473a082665b08a9be1e246f317ca9cb6ea964/pyproject.toml#L38) which conflicts with [gql](https://github.com/graphql-python/gql) 's requirement of `graphql-core>=3.2,<3.3` (https://github.com/graphql-python/gql/blob/master/setup.py#L6)

## Context
Any kedro project utilizing [gql](https://github.com/graphql-python/gql) will have a difficult time also using `kedro-viz`

## Possible Implementation
Is it possible to bump up `kedro-viz` 's requirement for `strawberry-graphql` ? Or make it more flexible?

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by AntonyMilneQB** [comment]
Hi @JasonTam, thanks very much for this. What you say sounds very reasonable, although I'm not sure exactly what a sensible requirement for `strawberry-graphql` would be.

The current version was pinned in https://github.com/kedro-org/kedro-viz/pull/680 as part of some sqlalchemy/mypy compatibility fix. Assuming that we can bump the requirement to the latest 0.104.3 release and keep things working, usually my strategy for a package with semver < 1 would be to do `strawberry-graphql~=0.104.3`. However, given the [extremely frequent releases](https://github.com/strawberry-graphql/strawberry/releases) (I guess they're done automatically using something like semantic release?), it feels like it will only be a couple of months before that results in some new incompatibility. So it's maybe risky, but I would be tempted to just for for `>=0.93.14,<1.0` so we don't have to keep on bumping the requirement. What do you think would be the right strategy here?

cc @limdauto - very interested in hearing what you think we with this requirement do here.

**Comment by JasonTam** [comment]
My inclination is also to use `>=0.93.14,<1.0` or similar and let the environment solver figure things out. But I'll be honest, I haven't spent time looking at the related deps.

**Comment by AntonyMilneQB** [comment]
In fact, now I'm wondering why we don't just use dependabot for Python dependencies like we do for the JS ones. @limdauto?

**Comment by limdauto** [comment]
@AntonyMilneQB IIRC most of the problems with strawberry have seen are mypy-related, so I think it's safe to relax the dependency and maybe be a bit less strict about mypy next time it blows up for strawberry.

Re dependabots, it's similar to the CI config situation ... I just never got to it :( I'm sorry.

**Comment by AntonyMilneQB** [comment]
Thanks very much for the comments @limdauto! No need to apologise at all - it's hard to get round to doing all this stuff I know, and these things about CI config and dependencies are way lower priority than actually developing kedro-viz. 🙂 It's just very useful to know there wasn't a particular reason to avoid using dependabot.
