### ISSUE TITLE
%run_viz line magic requires session.close first

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro-viz#811]
## Description
Running `%run_viz` from within a `kedro ipython` or jupyter instance will raise an exception "Cannot activate the session as another active session already exists". 

After some sleuthing and testing I decided that this bug has existed since kedro-viz 4.0.0 (26 Oct 2021) and was caused by PR #603, which was itself trying to fix some error with no active session. [`_activate_session` is called](https://github.com/kedro-org/kedro/blob/main/kedro/framework/session/session.py#L286) only when using the kedro session as a context manager (which is why this wasn't a problem in older kedro-viz versions) and [raises the error](https://github.com/kedro-org/kedro/blob/main/kedro/framework/session/session.py#L39).

## Workaround
Call `session.close()` in your ipython instance before doing `%run_viz`.

## Possible solutions
If we get rid of the `_active_session` stuff like @idanov suggests then this would be fixed straight away by a change on the kedro framework side. If we don't then we can probably fix on the viz side somehow (go back to not using the context manager I guess).

## Should we remove `%run_viz` altogether?
I was already questioning in https://github.com/kedro-org/kedro/pull/1355 whether anyone used `%run_viz`. The fact that it's had this major bug for nearly 6 months and no one said anything is quite a strong piece of evidence... If we do want to keep it then we should at some point also consider the (very small) bug that I mentioned there though:
> Removed `idle_timeout` argument for `kedro jupyter notebook/lab`. This was a tricky one to decide on because it was [originally introduced for a good reason](https://github.com/quantumblacklabs/private-kedro/pull/418): to fix a bug in which the [`%run_viz` line magic creates a process that blocks port 4141 even after Jupyter is killed](https://jira.quantumblack.com/browse/KED-1355). However, (a) the fix does not seem to work for me [i.e. `%run_viz` still blocks port 4141 even with the fix], (b) this fix can't ever work on managed jupyter instances so is incompatible with our goal of "one consistent workflow", (c) does anyone use `%run_viz` anyway? So overall I decided to remove the fix and then later let's work out whether it's really an issue and if so come up with a different fix (probably on the viz side, a `%kill_viz` command or something).

**Comment by rashidakanchwala** [comment]
This issue is also mentioned here #737

**Comment by AntonyMilneQB** [comment]
The original bug is fixed in Kedro 0.18.1. The other bugs and question of whether to keep `%run_viz` at all are still open though. I've started a new issue for that: https://github.com/kedro-org/kedro-viz/issues/855
