### ISSUE TITLE
A way for users to see that their settings have been applied to the settings modals

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#816]
We don't use toasters or any type of notifications to give users feedback when they perform an action. We should come up with a global notification system when changes are applied.

This system would trigger when one of these happens:
- Changes in the settings panel
- Renaming experiment runs
- Adding notes to an experiment run
- ...

**Comment by tynandebold** [comment]
Additional thought: there should also be a `failed` button state here, too, not just a `success`. E.g. this would come into play when someone tries to update a run name but the server dies and we can't save the data.

**Comment by yetudada** [comment]
This ticket is complete! Thank you 😊
