### ISSUE TITLE
Databricks and kedro-viz

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro-viz#831]
Just writing up where we stand on databricks + kedro-viz. This is partly for the sake of documentation and partly to identify next steps/bugs that need fixing, which will be turned into their own issues in due course.

### Best way to get kedro-viz working
This cunning method piggybacks off shiny and reaches us from databricks via @datajoely - thanks to all involved there!
1. Make sure kedro-viz and kedro are both installed in the same scope (notebook vs. cluster). i.e. if you `%pip install kedro` from inside your notebook then you should also `%pip install kedro-viz` from inside your notebook. If your cluster comes with kedro installed on it as a library already then you should also [add kedro-viz as a cluster library](https://docs.microsoft.com/en-us/azure/databricks/libraries/cluster-libraries)
2. Execute `kedro viz --no-browser --host=0.0.0.0` to launch kedro viz on port 4141 (or some other port if you like, via `--port`). You can do this with `%sh kedro ...` from inside a notebook
3. Run the following cell and click "Shiny app URL" to open a browser window
```
%r
library(shiny)
runExample("01_hello")
```
4. The URL will look something like `https://something.azuredatabricks.net/blah/random/stuff/xxxx/`, where `xxxx` is the port that shiny is using. Change this to `4141` and kedro viz should appear

### Can you use `%run_viz`?
Basically no. You can try to do, but you'll likely need to first:
1. Run `session.close` as in https://github.com/kedro-org/kedro-viz/issues/811. This is the ultimate cause of the mysterious timeout errors we've seen, just the real error message gets swallowed up somewhere
2. If you get some message about `ContextualVersionConflict`, it's due to a conflict between pip-tools and pip. You can either `pip install -U pip` or `pip uninstall pip-tools` (won't work if it's a cluster library). 

After that you'll get a "working" instance of `%run_viz`, but all it will output at the end is `<IPython.core.display.HTML object>`. This renders nicely in Jupyter notebooks but not in databricks.

### Things to fix
- [ ] Doing the above actually gives me a blank kedro-viz screen on the pandas-iris starter, although going to `api/main` shows the data is there. **UPDATE**: this seemed to also be the case on Sagemaker. And in fact it looked like the right data _wasn't_ in fact there if you clicked on nodes and datasets.
- [x] https://github.com/kedro-org/kedro/issues/1487 `ContextualVersionConflict` shouldn't mean that you can't run any kedro commands at all. I've seen this with other plugins also. We should fix this on framework side with better error handling in our entry point loading code
- [ ] Figure out if we can render `%run_viz` in a databricks notebook (if we actually care about doing so at all compared to just dropping it and going down the shiny route)

### Gotchas
* Don't use `%sh pip`; just use `%pip` (which I think is the same as `pip` without the `%`)
* Whenever you execute a pip command, the state of the notebook is reset, so you'll need to do Python imports again, `cd` to the right directory, etc. Hence it's best to do any `pip` work at the beginning of your notebook.
* kedro-viz and kedro need to be installed in the same scope for the plugin entry points to work correctly. Otherwise `kedro viz` won't be able to find the `viz` command (though weirdly the line magic seems to be registered correctly)
* The cause of the `ContextualVersionConflict` is because databricks seems to be using a notebook-scoped version of pip for entry points, which is different (older) from the cluster-scoped one. I don't know why this is or where that installation of pip comes from. This is maybe related to the above confusion about plugin entry points
* All this is based on databricks through Azure analytics labs; I'm not sure how much of it applies to other platforms

### Handy references
[Azure databricks documentation on libraries](https://docs.microsoft.com/en-us/azure/databricks/libraries/), especially the [page on notebook-scoped Python libraries](https://docs.microsoft.com/en-us/azure/databricks/libraries/notebooks-python-libraries)

**Comment by noklam** [comment]
I think `ContextualVersionConflict` is quite an important thing to fix, once you started installing plugins with Kedro, this error comes up quite often and it shouldn't block the entire `kedro` CLI like Antony said.

**Comment by tynandebold** [comment]
@rashidakanchwala to create additional tickets and then will close this issue.

**Comment by rashidakanchwala** [comment]
Hi, for this ticket following issues were highlighted 

- ContextualConflict error which is now an issue on Kedro and i think already fixed
- Adding Kedro-viz to cluster library on Databricks on platform mck (this is WIP and we will be notified once this is done by the plat team) 
- Fixing active_session issue on Kedro-viz (there's a ticket for this) 
- Document running viz on Databricks using shiny route (this has been done) 

So we can close this ticket.
