### ISSUE TITLE
Bump Kedro requirements on PyPI version to allow Python 3.9 and 3.10

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro-viz#835]
## Description
>Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

To my knowledge Kedro Viz is compatible with Python 3.9 and 3.10 and was pinned below because Kedro 0.17.x didn't support these, but 0.18.x does. 

![image](https://user-images.githubusercontent.com/35801847/165553459-a9c49100-713e-4977-91f5-a055262df8bd.png)

Can we please bump this on PyPI?

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by datajoely** [comment]
For anyone finding this you can run `pip install kedro-viz --ignore-requires-python` before it gets fixed

**Comment by tynandebold** [comment]
This was done in #815, though it hasn't been released yet. Will close this issue once it is.

**Comment by AntonyMilneQB** [comment]
This is released in kedro-viz 4.5.0 🎉
