### ISSUE TITLE
Intermediate Dataset is shown disconnected to folded modular pipeline

### ISSUE THREAD

**Issue by dmb23** [kedro-org/kedro-viz#839]
## Description
I declare a Dataset `intermediate_dataset` as output of a modular pipeline, but this dataset is used also as input to another node inside the same pipeline. When I display this setup with Kedro Viz and fold the pipeline, then `intermediate_dataset` is not connected to the pipeline (but to any other pipelines / nodes that use it as input further down the DAG)

## Context
A more realistic example is that I have a training pipeline in which I output a `trained_model` but also calculate validation metrics after training, so the `trained_model` is also input to another node in the same pipeline.

## Steps to Reproduce

1. kedro new --starter spaceflights
2. edit `src/project_name/pipelines/data_processing/pipeline.py`
3. change line 31 to `outputs=["model_input_table", "preprocessed_shuttles"],`
4. open `kedro viz`, fold the data processing pipeline

## Expected Result
`preprocessed_shuttles` is shown as an output of the pipeline `data processing`

## Actual Result
`preprocessed_shuttles` is not connected to the `data processing` pipeline

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Kedro==0.18.0
* kedro-viz==4.4.0
* Python==3.8.13

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by rashidakanchwala** [comment]
I think this is the same problem highlighted here #1105

**Comment by tynandebold** [comment]
Yeah I think you're right.

**Comment by tynandebold** [comment]
Relates to #1123

**Comment by tynandebold** [comment]
Closing in favor of #1105.
