### ISSUE TITLE
Multiple pipelines do not hide namespaced elements correctly

### ISSUE THREAD

**Issue by antheas** [kedro-org/kedro-viz#858]
## Description
Consider a project with multiple pipelines in pipeline registry and modular pipelines in those.

When there is a namespaced element that only appears in one of the pipelines, that element is not correctly hidden in the other ones (appears as a blank space).

![image](https://user-images.githubusercontent.com/5252246/169601592-6fbeb8e3-06c0-4b86-8992-3c2590af47f0.png)

## Context
It's a simple visual bug that clutters the UI.

## Steps to Reproduce
To reproduce, create a kedro project with the following pipeline registry:
``` python
"""Project pipelines."""
from typing import Dict

from kedro.pipeline import Pipeline, pipeline, node


def register_pipelines() -> Dict[str, Pipeline]:
    """Register the project's pipelines.

    Returns:
        A mapping from a pipeline name to a ``Pipeline`` object.
    """
    return {"__default__": pipeline([
        node(func=lambda a: False, inputs='tst.a', outputs='d')
    ]), "pipe2": pipeline([
        node(func=lambda a: False, inputs='tst.b', outputs='tst.c')
    ]), }

```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: Latest Vivaldi/Chrome
* Operating system and version: Linux
* NodeJS version used (if relevant): NA
* Kedro version used (if relevant): 0.18.1
* Python version used (if relevant): 3.8.10

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by tynandebold** [comment]
Thanks for this, @antheas. We'll have a look soon!
