### ISSUE TITLE
Pretty-print names do not work in namespaced transcoded datasets 

### ISSUE THREAD

**Issue by antheas** [kedro-org/kedro-viz#859]
## Description
When there is a dataset that uses transcoding (etc. `abc@a`), its name does not get pretty printed properly.

Both datasets below are namespaced. `tst.a@a`, `tst.b`. `tst.a` doesn't remove the namespace.
![image](https://user-images.githubusercontent.com/5252246/169603920-d24edb9a-126f-4d26-9d2c-56867501a109.png)

## Context
Simple UI bug.

## Steps to Reproduce
Create a kedro project with the following registry:

``` python
"""Project pipelines."""
from typing import Dict

from kedro.pipeline import Pipeline, pipeline, node


def register_pipelines() -> Dict[str, Pipeline]:
    """Register the project's pipelines.

    Returns:
        A mapping from a pipeline name to a ``Pipeline`` object.
    """
    return {"__default__": pipeline([
        node(func=lambda a: False, inputs='tst.a@a', outputs='tst.b')
    ])}
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: Latest Vivaldi/Chrome
* Operating system and version: Ubuntu 22.04
* Kedro version used (if relevant): 0.18.1
* Python version used (if relevant): 3.8.10

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by AntonyMilneQB** [comment]
Thanks for the bug report @antheas.

I am curious, because personally I've always disliked the feature and never understood the point of it, especially given how many problems it seems to cause... Do you like having pretty names on? Do you think it improves the appearance of kedro-viz or is there some other reason it's good to use?

**Comment by antheas** [comment]
Now that my project is getting big not anymore.

What's even worse, however, is having half of the nodes with a different name. It's one of the reasons I stopped using it.

Maybe for small projects it's worthwhile. There should probably be a way to showcase the namespace as well.

**Comment by tynandebold** [comment]
Hey @antheas we've just merged a fix for this and it'll be out in the next release. Thanks again for bringing this to our attention!
