### ISSUE TITLE
Implement 'Apply and close' design

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#860]
This ticket is to implement the deliverable from #816.

ACs:
- Ensure that the animation and design can handle both a `success` and `failed` state.
- Update the experiment-tracking modal to use the `Apply and close` design and animation.
  - This action could fail if something happens with the server, so here we'll need both success and failed states
- Update the settings modal to use the `Apply and close` design and animation.
  - This action only touches internal logic, so we don't need to worry about a failed state here.

Design and animation to be provided here by @GabrielComymQB or @Mackay031.

**Comment by GabrielComymQB** [comment]
You can check the Apply and Close modal pattern in our new Kedro Master Figma file we're putting together. There's the component for you to reference, a pattern description and a link to the prototype.

https://www.figma.com/file/WpVbkLm5x5zUr8AesxVQwH/Kedro-Master?node-id=14%3A244

![Image](https://user-images.githubusercontent.com/55446576/170301133-c651cf16-d461-4fe9-909f-b4a246946d55.jpg)

**Comment by tynandebold** [comment]
> Regarding considering "failed states" we need to understand what are the possible failures that can happen.
> 
> Can you please expand on that? After understanding it we can add the "failed" steps to the same pattern.
> 
> Thanks

Of course. Here it is:

The experiment-tracking data is brought to the frontend via a server. Data is also saved to that same server when a user updates a run name or adds a note to a run. It's conceivable that server connection could die out, and when the user tries to save their new run data, nothing would happen.

We actually already cater for this use case. See here: 

<img width="939" alt="image" src="https://user-images.githubusercontent.com/16869061/170483450-ef95ae60-0ba2-400f-9f96-4dd81babf09f.png">

So that's the failure that can happen, and as far as I can reason, it's the only one.
