### ISSUE TITLE
[Refactor] Changing the repository layer from in-memory to sqlite

### ISSUE THREAD

**Issue by limdauto** [kedro-org/kedro-viz#872]
## Description

Currently, the repository layer functions as an in-memory database to retrieve data for the API layer between different requests. It has always been a goal to swap the in-memory implementation with a database-backed implementation so the data modelling is more robust. For example, we can avoid a class of bugs like [this one](https://github.com/kedro-org/kedro-viz/issues/858) if we can employed relational data modelling so we can tag each piece of data with the correct constraint, e.g. having a foreign key from modular pipeline to registered pipeline, as opposed to keeping track of the relationship with in-memory data structures.

**Comment by AntonyMilneQB** [comment]
@limdauto comment from #964:
> @AntonyMilneQB if you are fishing for next project, I'd recommend drilling on this one:
> 
> > If you add a new tracked dataset and do a kedro run then the new dataset won't show up in experiment tracking unless --autoreload is set, because populate_data won't be called again
> 
> This is related to this issue that I opened a few weeks ago: https://github.com/kedro-org/kedro-viz/issues/872 -- the ideal flow in my head is:
> 
> * `populate_data` will populate a sqlite db through the repositories in the data access layer on first run. Think of the sqlite as a backend for the data access manager. Currently it's an in-memory backend.
> * Then we listen to changes on the Kedro project and add new entry to this database without having to re-run the whole populate_data like --autoreload is currently doing.
> * The API layer can keep polling this DB and return new data to the client via subscription.
>

**Comment by tynandebold** [comment]
Closing this as not planned right now.
