### ISSUE TITLE
Improve layout algorithm to minimize cross-over edges

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#873]
(transfer from Jira, created by @rashidakanchwala)

After the introduction of expand/collapse modular pipeline (Kedro >=4.0) . The number of cross-over edges has increased. This ticket is to improve the layout algorithm to minimises the number of cross-over edges. 

This ticket is a follow up to KED-3000.

**Comment by rashidakanchwala** [comment]
Nobody has ever complained about this issue. So we can close it.

**Comment by tynandebold** [comment]
Agree. Closing and will revisit if needed.
