### ISSUE TITLE
Zoom is reset each time a node or dataset is selected

### ISSUE THREAD

**Issue by kadeshoe5** [kedro-org/kedro-viz#882]
## Description
Kedro-viz resets the current zoom window size and position to the default values whenever a node or dataset is selected in the visualization. 
## Context
It makes it difficult to navigate larger pipelines when I am zoomed in on a specific area and have to constantly re-zoom in when I change which node to inspect

## Steps to Reproduce

1. Run Kedro-Viz
2. Zoom to a node
3. Select node

## Expected Result
Kedro should not zoom out if all dependancies are within the current zoom window. Or there should be a setting that disables this behavior.

## Your Environment
* Web browser system and version: Chrome Version 101.0.4951.64 
* Operating system and version: Mac OSX Monterey 12.4
* Kedro version used (if relevant): 18.0

**Comment by AntonyMilneQB** [comment]
I've noticed this before and agree it's annoying. Personally I don't see why opening the metadata panel should change the zoom on the flowchart at all, even if all the node's dependencies aren't on screen. I'm not even sure what sort of pipelines the current approach would benefit 🤔  So unless I'm missing something, +1 from me for just removing the zoom-reset-on-click behaviour altogether.

**Comment by tynandebold** [comment]
Hey @kadeshoe5 we just merged a PR that will fix this. I'll let you know when the next release is out and hopefully you can give it a try!

Thank you for raising the issue.
