### ISSUE TITLE
A way for users to see that they've bookmarked runs

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#886]
Design assets are ready and will be added below by @GabrielComymQB.

**Comment by GabrielComymQB** [comment]
Bookmark notification **on viewport**   ✅

The first and simpler variation is ready to go.
Flat images + interaction prototype example.

https://www.figma.com/file/K8WJMMTkvFHn6OZYg7Ypfz/Kedro-Design-Master?node-id=4303%3A4632

![Image](https://user-images.githubusercontent.com/55446576/172681465-3c3112d0-7f0a-4265-9156-004e5d423679.jpg)

**Comment by GabrielComymQB** [comment]
Bookmark notification on viewport   ✅
https://www.figma.com/file/K8WJMMTkvFHn6OZYg7Ypfz/Kedro-Design-Master?node-id=4303%3A4632

Bookmark notification - out of viewport   ✅
https://www.figma.com/file/K8WJMMTkvFHn6OZYg7Ypfz/Kedro-Design-Master?node-id=4328%3A5499
