### ISSUE TITLE
Consolidate design debt assets for development

### ISSUE THREAD

**Issue by GabrielComymQB** [kedro-org/kedro-viz#891]
Consolidate design debt assets for development.

Preparing assets, references, descriptions, acceptance criteria, etc for development.

https://www.figma.com/file/fXkT5m5qtXBi1nMK4GR6at/Kedro-Viz-Design-Debt?node-id=0%3A1

![Image](https://user-images.githubusercontent.com/55446576/172578106-977beb0d-c131-4497-90c7-47cef6f0d289.jpg)

**Comment by GabrielComymQB** [comment]
Hi team, we've just finished creating all the individual Frames for all the issues.

https://www.figma.com/file/fXkT5m5qtXBi1nMK4GR6at/Kedro-Viz-Design-Debt?node-id=0%3A1


![Image](https://user-images.githubusercontent.com/55446576/173109229-9044d1c0-bdcd-4da6-8063-6507d2ce35dc.jpg)

**Comment by tynandebold** [comment]
Fantastic. Thank you for this. I think I have approximately half as GitHub issues. I'll get the rest in next week!

**Comment by tynandebold** [comment]
Closing this issue as completed. We now have a solid working process, going from Figma to GitHub to release.
