### ISSUE TITLE
No tooltips on comparison mode icons

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#893]
## Description

When comparing multiple runs side by side, the ‘baseline’ and ‘remove run’ icons do not show any tooltips. User has to guess what it is.

![Screenshot 2022-05-24 at 13 54 1](https://user-images.githubusercontent.com/16869061/172605567-35a4dd52-2db4-4cf9-9bb0-8862667b8978.png)

![Screenshot 2022-06-08 at 11 51 1](https://user-images.githubusercontent.com/16869061/172605585-6dffde84-b108-4407-b440-10174c1a1739.png)

![Screen Recording 2022-06-08 at 11 51 1](https://user-images.githubusercontent.com/16869061/172609850-d3fb8a23-706a-4d4e-8e70-e130a069c7b3.gif)

## Acceptance criteria

The circular ‘baseline’ and ‘remove run’ icons do not show any tooltips in the same style we use in all other icons across the product.

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by Mackay031** [comment]
Hi, is this what you are looking for? https://zpl.io/2G3Gvz3

**Comment by Huongg** [comment]
Hey @Mackay031  i dont think its the one I'm looking for. I meant the tooltip for baseline button as i mocked up a new posiition below. Does it look right?

![Image](https://user-images.githubusercontent.com/32060364/173805026-596dc9a4-5216-4cbb-9980-7ebe483cb13e.png)

**Comment by Mackay031** [comment]
Oops, this one https://zpl.io/bzzqeY3

**Comment by Mackay031** [comment]
It can be below though. Perhaps this is better to line up with the menu that appears when you interact with the 'more' button. @GabrielComymQB thoughts?

**Comment by tynandebold** [comment]
@Huongg if you use the `IconButton` component I think you'll get a tooltip for free, though it might be a slight pain to style the positioning of the icon.

The tooltip would then match the style of elsewhere on the app, like this: 

<img width="260" alt="image" src="https://user-images.githubusercontent.com/16869061/173807584-465a6ba0-a43f-4247-80ae-9fe08697ea76.png">

If the design calls for it to be positioned differently there might be a way to do that as well.

**Comment by Mackay031** [comment]
Just thinking out loud and happy to discuss but I don't think the tooltip should cover the icons to the side of it. The above works for vertically aligned icons. With horizontal icons, they should always be visible hence using above or below.

**Comment by Huongg** [comment]
hey yeah @tynandebold i used the `labelText` from the `IconButton`, the styling is a bit odd in the attachment as its just a quick change to show Mackay what I meant 

If we go with @Mackay031 suggestion to display above or below for horizontal icons, I think we should introduce a new prop called `position`, eg "left, right, bottom, top" so we don't have to apply different styling everytime? Or is it something already done?

**Comment by tynandebold** [comment]
Agreed. I don't think there's a `position` prop at the moment. Would be great to add one to make this more flexible.

**Comment by Huongg** [comment]
cool lets do it then 👍
