### ISSUE TITLE
Improve layers labels and “watermark” highlights

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#901]
## Description

When layers are active and the user hovers over the flowchart, the active layers are not lit in the way it should be. The original explorations from two years ago show that the “active layer” (the one on hover) should be highlighted in two ways: the written label that follows the edge of the canvas and also the subtle “watermark” background which highlights the boundaries of the layer.
 
Note: the background highlight does work correctly if you're on the light theme.

## Acceptance criteria

- The “active layer” label that follows the edge of the canvas should be lit in higher contrast. I’m not sure how we’re treating this colour variable at the moment (if it’s a solid coulour or a transparent white). If it is a transparent white. Let’s go .55 alpha for the inactive layers and .85 alpha for the active one.
- The subtle “watermark” background which highlights the boundaries of the layer should have increased contras as shown in the reference link bellow.

Reference links: 

https://zpl.io/blEY77P

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by Huongg** [comment]
hey @GabrielComymQB after talking to Tynan and Cvetanka, we can confirm that 1 solid colour is our suggestion.  Can you let me know the watermark background colour for both dark theme and light theme please

**Comment by GabrielComymQB** [comment]
By the way, I've added the same references to a [dedicated Frame in our Figma board here](https://www.figma.com/file/K8WJMMTkvFHn6OZYg7Ypfz/Kedro-Design-Master?node-id=4531%3A9570)
