### ISSUE TITLE
New platform-dependent `%launch_viz` line magic

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro-viz#910]
Ideal outcome:
* make new `%launch_viz` line magic in kedro-viz, so that in any notebook with kedro IPython extension loaded, `%launch_viz` will be available
* `%launch_viz` starts a kedro-viz server and supplies a URL which the user can click on to open kedro-viz in another browser window

Required steps:
- [ ] Make sure the current code is still the best way to launch the server from inside the line magic 
- [ ] _Potentially difficult._ Work out the correct URL to access the kedro-viz instance on various platforms (databricks, sagemaker, etc.).
- [ ] _Potentially difficult._ Work out how to programmatically obtain this URL
- [ ] Work out how to automatically figure out which platform the notebook is running on
- [ ] Output the correct URL or some useful message which might help a user find their kedro-viz instance if we can't figure out the URL ourselves

To consider:
* how/which arguments can the user pass? Ideally all the same flags as used when you do `kedro viz` would be available the same way
* how to kill the server? See note in https://github.com/kedro-org/kedro/pull/1355 for current bug with `%run_viz` where this doesn't happen

**Comment by tynandebold** [comment]
Which platforms do we prioritize at the beginning? Databricks, Sagemaker, and Platform McK seem like the three obvious choices.

**Comment by AntonyMilneQB** [comment]
That sounds like the right choice to me also, though Platform McKinsey uses databricks so I would hope that if it works on there it would work on databricks in general.

I'm currently quite optimistic that if we can get the jupyter-server-proxy working then this will just work straight away on all these platforms 🤞

**Comment by AntonyMilneQB** [comment]
Let's assume there will be two different ways that `%launch_viz` would work:
1. Databricks: use the above. So far tested on Azure; still need to test on AWS and GCP.
2. Jupyter servers: use [jupyter-server-proxy](https://github.com/kedro-org/kedro-viz/pull/941/commits/8d3ba797705a133d4ccf91b0a6d28b10f425c679). So far tested locally; still need to test on Sagemaker.

Next steps:
1. above next steps for databricks method
2. make similar `%launch_viz` that starts process and links to it (find out if there's a programmatic way to get the URL through jupyter-server-proxy)
3. something that detects your platform and switches between the above two methods; starts the process and outputs something useful ("Kedro-Viz started on port X") even if it can't work out what the platform is
4. get `%launch_viz` to take arguments for `--pipeline` etc.
5. make the launcher button - only works for jupyter-server-proxy (probably can't take arguments; would only be `kedro viz --autoreload`; need to think about how to get project path there)
6. work out whether we need a way to kill the kedro-viz process

**Comment by AntonyMilneQB** [comment]
Some more notes following work on #1012.
* this way of handling project path by importing `default_project_name` seems to work well. The old `user_ns` method did not as it relied on pushing the variable to the user namespace, which `%reload_kedro` no longer does
* we should add arguments (`pipeline` etc.) to `%run_viz` like in https://github.com/kedro-org/kedro/issues/1748

**Comment by AntonyMilneQB** [comment]
## How to efficiently develop with Kedro-Viz on Databricks

After much trial and error, I have come up with a much more streamlined way to iterate on code being developed for Databricks. This should help to make the development loop much faster since there's no need to restart the cluster or manually handle repos this way 🎉 

1. Make a branch for your work
2. Run `make build`, `git add -f package/kedro_viz/html` and push to GitHub. This is temporarily needed while developing on your branch so that you can `pip install` from GitHub but should _not_ remain there when you merge to `main`
3. On Databricks, make sure that `kedro-viz` and `kedro` are _not_ installed as cluster libraries.
4. In your Databricks notebook, run (fill out `NAME-OF-BRANCH`):
```
%pip uninstall -y kedro-viz
%pip install git+https://github.com/kedro-org/kedro-viz.git@NAME-OF-BRANCH#subdirectory=package
```

5. To make a test project if one doesn't already exist:
```
%sh test -d iris || yes "" | kedro new -s pandas-iris
```
6. Then load up the Kedro IPython extension, make sure you're pointing to the right project path and do as you please:
```
%load_ext kedro.extras.extensions.ipython 
%reload_kedro iris
%run_viz
```
7. Whenever you make changes to your branch, all you need to do is push to GitHub and then re-run your notebook. This will `pip install` the latest changes to the branch directly from GitHub. No need to restart the cluster or clone repos any more.
8. Make sure you remove the `package/kedro_viz/html` folder before merging to `main`.

> **Note**. It seems like using the Databricks repos feature would be a smoother development process, but it's not. Every time you make a change to your branch you would need to pull the repo and reinstall on cluster, which means restarting the cluster every time (=slow). So don't try doing it that way...

**Comment by tynandebold** [comment]
We'll need to explore if `%run_viz` works on Sagemarker notebooks. For now though, we can close this.
