### ISSUE TITLE
"Created By" is empty in experiment-tracking view 

### ISSUE THREAD

**Issue by tgoelles** [kedro-org/kedro-viz#911]
## Description
"Created By" in the  does not show anything in experiment-tracking view is empty. It es even empty in the https://demo.kedro.org
Maybe the information is not stored correctly be kedro

## Context
I would like to know who did what experiment

## Steps to Reproduce

kedro run a project with experiment tracking set up. Then kedro viz and go to experiment-tracking view.

## Expected Result
See the user who run the experiment. Either the UNIX username or the name set up in a settings file  or  from an environment variable.

## Actual Result
Only a "-" in the Created by. 

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

kedro, version 0.18.1
kedro-Viz (4.6.0)

running inside a docker container:
Linux e92699714b92 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64 GNU/Linux

**Comment by tynandebold** [comment]
Thanks for this, @tgoelles. It is empty and shouldn't be.

@rashidakanchwala @MerelTheisenQB @AntonyMilneQB I see the author is [always set](https://github.com/kedro-org/kedro-viz/blob/main/package/kedro_viz/api/graphql.py#L75) to an empty string and doesn't look to be part of the `run_blob` argument in the `format_run` [function](https://github.com/kedro-org/kedro-viz/blob/main/package/kedro_viz/api/graphql.py#L53).

Are we not saving the author/user on the Core side?

**Comment by tgoelles** [comment]
The git username would also be a possibility

**Comment by MerelTheisenQB** [comment]
No we're not saving the author/user on the core side and for this first version of experiment tracking it was decided to just leave it like that and see if users actually need that field.

**Comment by tynandebold** [comment]
Got it, thank you. Now that a user is requesting the field would it be something easy to add?

**Comment by MerelTheisenQB** [comment]
We'll need to determine what exactly we mean by "author" or "user". Is it the github username or the user logged in to the machine executing the command? And what if it's executed in a process where the user would be "root"?

**Comment by tynandebold** [comment]
@tgoelles curious what you think to the question's above?

**Comment by tgoelles** [comment]
I guess the most flexible way would be to define it in the settings.py. There I could define it as for example the git username or an environment variable whatever I want.
so KEDRO_USER in settings.py would be my preferred way.
it could default to  $USER but could overwritten with whatever a user wants.

**Comment by AntonyMilneQB** [comment]
Wait, we actually have exactly `getpass.getuser()` in our code already!! @MerelTheisenQB 
https://github.com/kedro-org/kedro/blob/6768d7f3a300dd60d15ec136b311c4c3c3a8e2f8/kedro/framework/session/session.py#L166

It was added in this PR: https://github.com/kedro-org/kedro/pull/1366. Did we mean to add it to kedro-viz too and just didn't complete the task? I'm not sure, but given it's already there I think this should be pretty trivial to add now.

**Comment by tynandebold** [comment]
+1 from me for adding it to Viz if it's already in core!

**Comment by MerelTheisenQB** [comment]
Lol I completely forgot we'd already completed that task 🤦‍♀️ In that case I totally agree we should just add it on the viz side.

**Comment by tynandebold** [comment]
I added this issue to your inbox, so maybe it can be picked up next week during spring planning if you have bandwidth. I could even try to do it myself with a little guidance.

**Comment by tynandebold** [comment]
@tgoelles we've fixed the issue. It'll be out in the next release, which will be sometime at the end of next week.

Again, thanks so much for reporting this bug!
