### ISSUE TITLE
Missing unbookmarked to bookmarked hover state

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#928]
## Description

When exploring any unbookmarked card in the runs list, there’s no differentiation between the states of the bookmark icon. The issue is with the mouse on or out of the icon the state is the same.

![Screen Recording 2022-06-10 at 14 21 1](https://user-images.githubusercontent.com/16869061/174596750-688f2687-af07-4b21-bb32-db96d9368dbd.gif)

![Screenshot 2022-06-08 at 14 54 1](https://user-images.githubusercontent.com/16869061/174596829-75278503-9950-4aa5-b02d-1dfc714d8eae.png)

## Acceptance criteria

- There should be two distinct states for the bookmark icon here as seen on the bookmarking pattern reference on our Figma master file. Icon turns from outlined to active solid colour announcing the action you’re about to perform.

Reference link: 

https://www.figma.com/file/K8WJMMTkvFHn6OZYg7Ypfz/Kedro-Design-Master?node-id=4303%3A4632
https://www.figma.com/file/K8WJMMTkvFHn6OZYg7Ypfz/Kedro-Design-Master?node-id=4207%3A28446

<img width="408" alt="image" src="https://user-images.githubusercontent.com/16869061/174596934-20811262-9b0b-4c4b-9999-71e8a1c77605.png">

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by GabrielComymQB** [comment]
Please check the updated reference link

https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=106%3A3069
