### ISSUE TITLE
Micro-animation of Runs details (right hand side)

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#932]
## Description

All the copy and content of the Run details on the on the rights hand side of screen appear to be very stiff and jumpy - Labels, expandable groups, columns and rows.

 
![Screenshot 2022-05-23 at 14 02 1](https://user-images.githubusercontent.com/16869061/174599600-c45d0e78-f8de-4ce7-9a6e-c1c03eed5bc1.png)

## Acceptance criteria

- All the copy and content of the Run details should animate as per the Principle prototype when the “compare” toggle is activated and when any layout changes happen on the right hand side of screen. Labels, copy, rows, columns should appear/disappear with ease. Slick. Please see reference link to the prototype.

Reference link: https://mckinsey.box.com/s/w3clia4k5njijhjkl60tall8qnpgabwi

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by Huongg** [comment]
hey @tynandebold @GabrielComymQB I've tried to summarise all the behaviour for this page. Can you confirm they're correct? Also, I have some questions (**in bold**) along with this too. Let me know if you think it's easier to go through them on call?


### Comparison mode on:
- First title slight fade-in from the right-hand side and title on the left slightly fades out

![image](https://user-images.githubusercontent.com/32060364/178712333-429b4745-a8ff-4e09-ab7b-e013df056cfb.png)
![image](https://user-images.githubusercontent.com/32060364/178712391-4e6382de-2a40-4c6f-a725-c0495aa5ec5e.png)

- At the same time, both sides resize


### Chose more than 1 run to compare
- A set of buttons appears first on the baseline run
![image](https://user-images.githubusercontent.com/32060364/178712475-f812f0ad-ef66-4d11-927d-42ba55c6af85.png)

- Then the second run slightly fades in
![image](https://user-images.githubusercontent.com/32060364/178712518-f73a828d-61bb-4401-9dd5-b367ea558ba0.png)


**There was some movement in the metrics panel but I'm not sure what the exact behaviour is?**


### Toggle differences

**In the prototype, when toggle differences, the metrics seem to be changed too, but on my local host, it only hides or shows the arrow. Do we need to implement this separately?**
 
![ezgif com-gif-maker (7)](https://user-images.githubusercontent.com/32060364/178712121-588f8934-a8d9-4a6e-9b72-f48192dacf4c.gif)



### Turn the comparison mode off
**What's the correct behaviour for this? Just the opposite of turning the comparison mode on?**

**Comment by Huongg** [comment]
and of course do let me know if I miss anything here 😄

**Comment by GabrielComymQB** [comment]
Hi @Huongg I can see any of the videos you posted. These are plain images to me.

![Screenshot 2022-07-13 at 13 48 11](https://user-images.githubusercontent.com/55446576/178737136-70f2f9f7-796e-4ee8-b4c0-4d5d904a31a9.jpg)

Also, describing moving images with words is very complicated.

I'd love to see it happening in place and whatever work in progress you have to be on Gitpod so I can give proper feedback.

And after that, I guess having a call would be much easier too.

**Comment by tynandebold** [comment]
> #### Toggle differences
> In the prototype, when toggle differences, the metrics seem to be changed too, but on my local host, it only hides or shows the arrow. Do we need to implement this separately?

No need to worry about toggle differences. That isn't something we have and isn't something that needs to be done in this ticket.

> #### Turn the comparison mode off
> What's the correct behaviour for this? Just the opposite of turning the comparison mode on?

Yeah, good question. I'm not sure. @Mackay031 didn't show that in the prototype, so it's unclear. Maybe Gabriel knows?

**Comment by GabrielComymQB** [comment]
Hi @Huongg 

Here's a description of what we need to focus:


Single view is on.  User is about to toggle Comparison mode on.

![Screenshot 2022-07-13 at 14 47 56](https://user-images.githubusercontent.com/55446576/178749330-fc5ef000-5775-4c6c-9372-ad833a143388.jpg)


After toggling Comparison Mode on a few macro animations happen in conjunction.

  **1 - Run lists card.**

- The run name, hash and timestamp content of the card slides right and the “tick selected” mark appears with ease. 

![Screenshot 2022-07-13 at 14 48 44](https://user-images.githubusercontent.com/55446576/178749515-6731c00e-a03c-47cf-8d0f-c3ee111bb94c.jpg)



**2 - The run information (Right side of the screen)**

**2.1 Labels and collapsable subgroups column:** 

- Run title (“my favourite sprint” here), fades out to the left from 100% to 0% opacity with ease in alignment with all the other stacked elements and labels that form that very first column of content. 

![Screenshot 2022-07-13 at 14 59 17](https://user-images.githubusercontent.com/55446576/178751835-1789e71c-d60e-4e4b-a1c2-dee1fbdd36bb.jpg)

- After this initial motion is complete, you are only left with the column of plain labels. 

![Screenshot 2022-07-13 at 15 00 17](https://user-images.githubusercontent.com/55446576/178752072-bef35286-cff5-4d44-aaf8-5be27594f48a.jpg)



**2.2 Values column:**  

- All “values column” (starting from “Luke Skywalker” moves from its original position sliding left with ease and accommodating a new “cosy” position - which later will leave more space for the new columns to sit side-by-side.

![Screenshot 2022-07-13 at 15 00 51](https://user-images.githubusercontent.com/55446576/178752201-e139e0e8-91f0-440b-86c8-e15be84a715b.jpg)


- Together with this right to left movement, the Run Title ( (“my favourite sprint” here) slides AND fades in opacity at the very top - becoming the title of that whole column.

![Screenshot 2022-07-13 at 15 01 20](https://user-images.githubusercontent.com/55446576/178752274-ab7d1eee-e99d-4d25-ae72-c94d6c796795.jpg)


Adding new run columns: 


- As users decide to add more runs to be compared side by side, the animation of the new column coming in should always follow the same:

  **Fade in:** 
  
  Slide right to left and fades in from 0% to 100% transparency (exactly the same style we created for the recent icons work coming in and out from the utility bar)  

**Fade out:** 

Slide left to right and fades in from 100% to 0% transparency (exactly the same style we created for the recent icons work coming in and out from the utility bar) 

**Note**: When two or more runs are selected in Comparison Mode you then now have individual selections and controls sitting at the very top of each column

![Screenshot 2022-07-13 at 15 05 05](https://user-images.githubusercontent.com/55446576/178753108-4aa12cf7-837b-4e06-b2e8-ac88b4796db1.jpg)

![Screenshot 2022-07-13 at 15 05 15](https://user-images.githubusercontent.com/55446576/178753153-7af63f8a-44ee-45ba-aac1-cc9e08a5b4bc.jpg)

**Note**: Please ignore for now the part in the prototype when we toggle the “Difference” icon in the utility bar. We are not making use of that icon or interaction just yet.

**Comment by Mackay031** [comment]
Here is a little prototype of how the runs (columns on RHS) animate when run no.2 (the middle) is deselected. 

https://mckinsey.box.com/s/p1bv8poecwusy64n2jes49w0bm4prhji

**Comment by Mackay031** [comment]
Hi, I have a couple of questions:

- If the header and contents come in together at exact same time, only if they have already pre loaded? See here how last one is staggered https://mckinsey.box.com/s/dull93mrr2lhjkgy0xyujos5ldk1fjd6. I see some inconsistencies there.
- When you remove middle run, there is again inconsistencies in how they animate. In [this](https://mckinsey.box.com/s/qwmt6rslltd0d1q35vl4e4i2p9exva3x) version, the header and contents move across at different times (see from 6s). It seems like middle run header and contents fade out at different times. However, in [this](https://mckinsey.box.com/s/1h4hclfcv029m68p1xwaiiqkym4fw9n9) version, they move across together. Although it cuts across and doesn't animate (as in above prototype), it is much better and less confusing for the user. 

Are we saying these cannot be solved in the Front end alone?

Hope this makes sense. We can jump on a call if not.

**Comment by Huongg** [comment]
hey @Mackay031 thanks for the feedback, just to clarify, which version is the latest one you checked? Is this one the latest one you checked? `https://mckinsey.box.com/s/1h4hclfcv029m68p1xwaiiqkym4fw9n9`

**Comment by Mackay031** [comment]
Hi, yes< i took those screengrabs today from the Gitpod link. It timed out and so went back here to get back in if that makes sense :)
<img width="1477" alt="Screenshot 2022-08-09 at 17 22 59" src="https://user-images.githubusercontent.com/102358798/183705827-9df72ef2-fd3d-411c-8d16-ee042be2798d.png">
.
