### ISSUE TITLE
Design exploration and final assets for linking plots to experiments

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-viz#938]
## Description 

This task follows #1626 and includes the design exploration to understand how we can add ability for our users to track their plots as part of their experiments and visualise them on Kedro-Viz experiment tracking.

## Outcome 

The initial phase will produce low-fidelity journeys of this experience to test with the engineering team. Testing with users will follow this phase in a separate ticket.

**Comment by GabrielComymQB** [comment]
Link to the original ticket
https://github.com/kedro-org/kedro/issues/1626

**Comment by GabrielComymQB** [comment]
Explorations for review:

https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design-IN?node-id=17%3A318

**Comment by tynandebold** [comment]
Looks great so far!

**Comment by GabrielComymQB** [comment]
Updated link for our Monday review:

https://www.figma.com/file/K8WJMMTkvFHn6OZYg7Ypfz/Kedro-Design-Master?node-id=4601%3A9594

**Comment by yetudada** [comment]
This design covers: 

- A way for users to see thumbnails of plots (PNGs and interactive images) created by the `MatplotlibWriter` and `PlotlyDataSet` datasets next to each experiment that they've run
- A way for users to expand the thumbnails to see full details of the plot
- A way for users to compare the plots to each other

We additionally need to see: 
 
- Support for `PlotlyDataSet` interactive plots
- A way to group all images in one area per experiment so that plots are not positioned randomly throughout the experiment; we have chosen plots to appear in one group at the top of experiments 

For now, we're leaving out a way for users to hide plots, in case they have many.

**Comment by GabrielComymQB** [comment]
Finding and exploring plots - single view

https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=217%3A7286

**Comment by GabrielComymQB** [comment]
Finding and exploring plots - comparison view
https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=230%3A7796

**Comment by GabrielComymQB** [comment]
Expanded graphs, page variations (1,2 and 3 runs)
https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=232%3A12150

**Comment by tynandebold** [comment]
I've left a couple small comments in the Figma files, though they're just for clarification. It's certainly ready for development, so it's approved from my side.
