### ISSUE TITLE
Consolidate typography styles

### ISSUE THREAD

**Issue by comym** [kedro-org/kedro-viz#950]
We're revisiting all typography variables currently used on Viz and consolidating them all into new styles as part of our design system.

After having it done on the design side, the idea is to team up with engineering and see how we can simplify/unify/clean up the multiple colour variables we have accumulated over the years.

![Image](https://user-images.githubusercontent.com/55446576/177139949-79e98647-d016-4e65-85f7-6b15ecf9f505.jpg)

**Comment by GabrielComymQB** [comment]
Exported
https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=338%3A13159

**Comment by tynandebold** [comment]
I just went through what you've put together and it looks very comprehensive. I couldn't find any additional font sizes or styles, so this should be able to be moved to `Done`.

I'm curious where that `38px` font size is used? That's the only one I'm unsure of.
