### ISSUE TITLE
Implement visualizing plots in experiment tracking

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#953]
## Description

This ticket focuses on the implementation of the design work created in #938.

The backend will need to recognize the versioned plots (Matplotlib and Plotly Datasets) and the frontend will need to display them, with the behavior outlined in the Figma files:

1. [Finding and exploring plots - single view](https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=217%3A7286)
2. [Finding and exploring plots - comparison view](https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=230%3A7796)
3. [Expanded graphs, page variations (1,2 and 3 runs)](https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=232%3A12150)

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
### Plan of action

- In `graphql.py`, line 235: look for matplotlib and ploty with version==true
  - there are two plotly datasets that we need to check for here. look in the shortTypeMapping config var
- graphql.py, line 249: needs to become something more generic and what's passed to the FE is either JSON or PNG/JPG. base64 the matplotlib img
  - we want to keep the same data structure as well (key/value pairs). the key would be the filename, and there's only one value, which is the JSON for Plotly or the base64 image for matplotlib
- on the frontend, according to the dataset type, show the appropriate plot or data
- update `shortTypeMapping` and add the two missing dataset, e.g "kedro.extras.datasets.tracking.metrics_dataset.MetricsDataSet"
- break up the tracking datasets into sections: plots, metrics, JSON data. More info below...

#### Plots at the top

We also want to plots to appear at the top of the tracking area. They should go into their own accordion as well, as shown here in the design:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/16869061/177190647-79d7a27c-1aad-4d0c-9c31-e63e5a127337.png">

We'll have three groups: Plots, Metrics, and JSON. Our `runTrackingData` query will now return the following:

```graphql
type GroupedDataset {
  groupedDatasetType: String 
  dataset: TrackingDataset[]
}
```

`TrackingDataset` then becomes:

```graphql
type TrackingDataset {
  datasetName: String
  data: JSONObject
}
```

**Comment by AntonyMilneQB** [comment]
Don't we still want `datasetType` in `TrackingDataset` so that we can switch between rendering differently matplotlib png vs. plotly json data?

**Comment by tynandebold** [comment]
@AntonyMilneQB yes. Update. Thank you.
