### ISSUE TITLE
Clean up metadata side panel for datasets

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro-viz#962]
There's several small niggles I've always had with the metadata panel for datasets.
![image](https://user-images.githubusercontent.com/49395058/177531859-8bd6b682-0961-47c7-a855-133b18e90415.png)

1. Why do we show `Type: dataset` at all (also applies to nodes)? It's obvious from the icon and information provided that's what it is.
2. Dataset Type is always too long to fit in, when really all that people care about is the last part after the final `.`. Can we make it so that we only show that part but then on mouseover it shows the whole path? (The full path currently shows on mouseover)
3. Similarly (though more debatable) for File Path.
4. Why do we need `Pipeline` field? Is it just the same as the registered pipeline selected?

**Comment by tynandebold** [comment]
Responding to your points:

1. I actually find it helpful. Also, the icon doesn't always match, unless this is a bug:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/16869061/177544464-ac3bf63b-9071-4c8c-9652-6ce99a3fb3fd.png">

2. Yes, we can do that. This is a great idea.
3. This is a good idea, too. What's the equivalent to the "final `.`" in this case though? The final `/`? That might not be enough.
4. Yes, this value always matches the registered pipeline selected in the dropdown. Not very useful.

**Comment by AntonyMilneQB** [comment]
Dataset icon and `Type` field: fair point - you're right that there are multiple possible icons for a kedro dataset, that's not a bug. Let's not do this then.

Shortening the path: Yeah, this is trickier because you might have some other sort of filepath like on windows or something on the cloud. It's probably easiest to extract the relevant "last part" on the backend side since it might need fsspec to handle the general case correctly. This would then mean sending both the "last part" and the full path to the frontend in two different fields. I'm also not sure whether this is such a good idea because the earlier part of a filepath might be useful to discriminate between two different files with same filename but in different directories. So possibly we shouldn't make this shortening right away - just the dataset type shortening.

One thing I forgot to mention before that would be nice to fix though is the trailing `/` on the file path. I'm not sure why that appears on kedro viz for lots (all?) datasets.

**Comment by tynandebold** [comment]
Noted. So two actions to take:

1. `Dataset Type`: show only the part after the final `.` but allow the whole path to be visible when hovering over the text.
2. Remove the trailing slash from the `File Path` text field.

That should be a quick PR.

**Comment by AntonyMilneQB** [comment]
Yes, and also remove the `Pipeline` field unless there's some reason for it to remain?

**Comment by tynandebold** [comment]
I don't think there is. Let's remove it. I appended it above.

**Comment by tynandebold** [comment]
We'll need to handle the case where users create their own custom datasets. What do we do in that case? Should we even shorten it, or leave as is?

**Comment by AntonyMilneQB** [comment]
I think it's fine to shorten in exactly the same way as a built in dataset type (so long as the full path is available on mouseover still). No need to put in custom logic to detect whether it's the dataset type belongs to kedro or not.

**Comment by tynandebold** [comment]
I don't think that would be solved here, since that's a function of the **_Pretty name_** feature. When that's off, you get `prm_shuttle_company_reviews` instead of `Prm Shuttle Company Reviews`.

This relates to #859 as well.
