### ISSUE TITLE
Consolidate icon states and styles

### ISSUE THREAD

**Issue by comym** [kedro-org/kedro-viz#966]
We're revisiting all icon states and styles currently used on Viz and consolidating them all into new styles as part of our design system.

The Design OUT Figma file will be updated showing all correct variants and styles

Icons should have 4 states:
Disabled, Default, Active, Hover

![Image](https://user-images.githubusercontent.com/55446576/178275114-81f6247e-d3dd-4958-b5e6-1f0ebd5fc8ea.jpg)

**Comment by GabrielComymQB** [comment]
Main bar icons published
https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=406%3A13287

**Comment by GabrielComymQB** [comment]
Utility bar icons published 
https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=406%3A12891



![Image](https://user-images.githubusercontent.com/55446576/179007580-d3d0c144-59be-4828-bb02-9a8b018899f8.jpg)

**Comment by GabrielComymQB** [comment]
General content icons published

https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=416%3A22017
