### ISSUE TITLE
Colors/Typography cleanup and update

### ISSUE THREAD

**Issue by cvetankanechevska** [kedro-org/kedro-viz#971]
## **Summarised key points for how to approach restructuring colors/typography on FE:**

1. Use only HEX values (RGB, 'inherit', mixed colors needs to be replaced).
2. To have only one file where all colors will be defined and reuse it from there thought the whole app, so if some color will be modified in the feature that should be done only in this place and automatically replaced in all components that is used. 

      - If this file will become huge and difficult to read, we can split it into more files, for example like @GabrielComymQB has group them on Figma (https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=84%3A2866).
      - To specify what colors will be defined globally and in which situation we will have locally defined colors for some specific component (if that color is used only there).
      - How and where should we define dark/light themes (globally or separate in each component)

3. Better color naming:

   By @GabrielComymQB: See that apparently at the moment we use stuff like: `--color-bg-3` we need to name the variables to be as specific as possible, like:
               - colour name
               - where it is applied
               - some sort of state definition (on, off, active, inactive)

4. To have only one file for typography (clearly assigned only to typography).
5. To have only one file for fills (this can be for backgrounds, buttons, icons, any other UI element).

## **With this we want to achieve:**
- Clear code style on FE
- Easy maintainable design
- To have something like a custom made Kedro theme

**Comment by tynandebold** [comment]
This is a great start. I'll respond to your points one by one:

1. Yes, totally agree.
2. We should be able to get away with having all colors in only one file. I don't think it will get too hard to read or be too large.  We should try and define all colors globally, even if we have one color that's only used in one place. In the future, it might end up in more than that single point. For dark and light themes, I think we can define those globally as well.
3. I don't agree with this, at least not the "where it is applied" part. I don't think the color names should be as specific as possible. I think they should be as **_generic_** as possible. For example, there will certainly be a case where we'll have one color used in multiple places and in multiple components. How could a specific color name containing a reference to where it's applied work in this case? I'm in favor of the other parts though: color name + state definition (if needed).
4. Yes, agreed here as well.
5. Why would we need this? It isn't clear to me why these colors wouldn't live in the main, globally defined color variables file.

**Comment by tynandebold** [comment]
We can close this now that #997 is complete.
