### ISSUE TITLE
Migrate Flowchart Metadata side panel to Figma

### ISSUE THREAD

**Issue by comym** [kedro-org/kedro-viz#975]
We're bringing the Metadata side panel component from old Sketch files to our current Figma design system.

![Image](https://user-images.githubusercontent.com/55446576/179478571-461936ce-ec05-4549-b0ab-64ef1965950a.jpg)

**Comment by comym** [comment]
Published metadata side panel in various variations.

https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=539%3A28859

![Image](https://user-images.githubusercontent.com/55446576/180827312-a83f7425-4354-4ac2-b921-d3ab3abcbbd6.jpg)


Also included the code block for nodes.

https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=539%3A28858


![Image](https://user-images.githubusercontent.com/55446576/180827378-554db47f-d5d0-42a7-a3fa-cf730482dc9d.jpg)


@Mackay031 @tynandebold could you please have a look at it? Thanks

**Comment by tynandebold** [comment]
Looks great. I left a couple of small comments in Figma. Approved from my side 👍

**Comment by comym** [comment]
Thanks!

I've just republished it including the X icons we're missing and also replied to your comment about the Plotly button.

https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=539%3A28859

![Image](https://user-images.githubusercontent.com/55446576/180964597-5392a802-e8f9-4aee-96f3-4cad8e36e0ab.jpg)
