### ISSUE TITLE
Consolidate Edit Run Modal component on Figma

### ISSUE THREAD

**Issue by comym** [kedro-org/kedro-viz#976]
At the moment we're only documenting the Edit Run pattern on Figma, however we still don't have this built as a component for future use in our Figma file.

We'll need to consolidate this as a proper component on Figma.

![Image](https://user-images.githubusercontent.com/55446576/179479216-e939529b-f0a6-4db5-8111-1b3800f9b984.jpg)

**Comment by tynandebold** [comment]
Fantastic! Looks great to me, and I think the linking between the two is a great approach. Nice one.
