### ISSUE TITLE
Creating Style Variables for the new colour palette on Figma

### ISSUE THREAD

**Issue by comym** [kedro-org/kedro-viz#989]
After our second discussion on the simplification of colours, (https://github.com/kedro-org/kedro-viz/issues/986) we are creating this new dedicated ticket related to the creation of new style variables on FIgma

- We have to have every single colour value for all the colours published as specific variables
- We'll publish it to the Kedro Design OUT file and from there we'll start the remapping of all these new colours to the current.

**Comment by comym** [comment]
Published to the Design OUT:
https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=613%3A29458

All the colour variables are now condensed as colour variables in Figma:

![Image](https://user-images.githubusercontent.com/55446576/181738154-687c8128-439c-4961-ac44-4260cd5cdde0.jpg)

**Comment by comym** [comment]
@tynandebold and @Mackay031 

Can you please have a look at that?
The next steps will be to do the remapping of the new palette to all our current colours 

many thanks

**Comment by tynandebold** [comment]
It looks fantastic. Great choice with `ocean` as well. Approved from me 👍
