### ISSUE TITLE
Create reference documentation for the use of transparency on elements

### ISSUE THREAD

**Issue by comym** [kedro-org/kedro-viz#992]
We need to document the use of transparency and its global logic - especially now that we'll detach the colours from the use of transparency.

Let's publish some examples and set values to them.

![Image](https://user-images.githubusercontent.com/55446576/181597742-6a85613e-4d3c-494c-a929-a09e01ec6b09.jpg)

**Comment by comym** [comment]
Transparency use published
https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=659%3A23031

![Image](https://user-images.githubusercontent.com/55446576/182663998-9143d429-eed9-4646-9fe2-9a7a01c3ca95.jpg)

**Comment by tynandebold** [comment]
I'm slightly confused by the 55% `default` state @comym. Does that mean all of our default colors should be at 55% transparency? Or do you mean that **_when_** we use transparency, the default will be 55%?

**Comment by comym** [comment]
Good question.

I guess that's a common confusion made by the way we label stuff. Maybe it's not the right way of calling things. 

Firstly the intention is to separate colour values completely from transparency. So in this case we can say that colours will always be 100%, alpha 1.0. There will never be transparent **colours**.

However, we can apply transparency to **elements**. Any elements on the interface. This could be an icon, a panel, a button, or even a line of text.

Let's say, a button can come forward and back. Active or disabled.

![Image](https://user-images.githubusercontent.com/55446576/183050201-7f255f52-a2e5-4baf-b490-cb0c29f2799c.jpg)

And in the same manner, any other element could come active or inactive, go forward or back.

![Image](https://user-images.githubusercontent.com/55446576/183050537-3cf63371-bd57-4f28-98bf-22873a31d341.jpg)

The confusion might be that in this example, we are only showing the use of transparency on an icon element. Icons have a particular need. They can not be 100% because if you are already at 100% you can't go further and make the element come forward in a hover state for instance.

What we might be missing is giving a few more examples of how transparency can affect different elements. Not only showing the use of transparency on icons (which is very particular) but other elements of the interface too.

@Mackay031 and @tynandebold any thoughts? I agree we can definitely improve it.

**Comment by tynandebold** [comment]
This was a good explanation, thank you. I think it's good to go. If we run into any oddities or ways to be more specific about it when we put it into practice, we'll handle it then.

**Comment by tynandebold** [comment]
This was a good explanation, thank you. I think it's good to go. If we run into any oddities or ways to be more specific about it when we put it into practice, we'll handle it then.
