### ISSUE TITLE
Implement color cleanup and refactor of components

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#997]
This task breaks out the color portion (numbers 1-3, pasted below) from #971.

**Acceptance criteria:**

- Use only one variables file for colors
  - Adding the new colors and color names
-  Refactor the components to use the new colors and color naming
_______________

1. Use only HEX values (RGB, 'inherit', mixed colors needs to be replaced).
2. To have only one file where all colors will be defined and reuse it from there thought the whole app, so if some color will be modified in the feature that should be done only in this place and automatically replaced in all components that is used. 
3. Better color naming.

**Comment by comym** [comment]
Hi @cvetankanechevska 
I've just published the updated "Missing colours" board to the Design OUT Figma file
https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=1028%3A33124

Any questions just ask, thanks
