### ISSUE TITLE
Remove pandas and plotly dependency

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro-viz#999]
> **Note**. Probably it's only worth doing this once the scheme for making plots to compare metrics has become clear, just in case that ends up requiring plotly and/or pandas on the backend.

Currently kedro-viz has these requirements which ideally shouldn't be necessary:
```
plotly>=4.0
pandas>=0.24
```

These are only used in `flowchart.DataNodeMetadata.create_metrics_plot` for generating the metrics plot in the metadata panel. The reason they shouldn't be required is that they are used for very simple data wrangling, which we should be able to handle without much obfuscation by using purely Python dictionary ➡️ reshape as necessary :arrow_right: pure json (_should not even need any particular plotly syntax_) :arrow_right: make plot on frontend.

> **Warning**. Make sure that kedro-viz still works on projects without any plotly/metrics datasets without these dependencies (both flowchart and experiment tracking screens). The imports should not break.

**Comment by tynandebold** [comment]
More context: if we implement #907 then Pandas may become a dependency we need to keep around.

**Comment by AntonyMilneQB** [comment]
@tynandebold Just to emphasise the _may_ on the above point - this depends very much on where the preview implementation ends up (kedro-datasets side vs. kedro-viz side). If we do end up needing `pandas` for this on kedro-viz then it should probably be an optional dependency like `pip install kedro-viz[pandas]` anyway. So whatever happens I think we should go ahead and remove the pandas dependency for now anyway.

**Comment by tynandebold** [comment]
Makes sense. Should we remove Pandas as well as Plotly now then? Or wait until we implement comparing metrics, as you said here?

> **Note**. Probably it's only worth doing this once the scheme for making plots to compare metrics has become clear, just in case that ends up requiring plotly and/or pandas on the backend.

**Comment by AntonyMilneQB** [comment]
On second thoughts I don't think we need to wait for that actually, because we can always add the plotly/pandas dependency back in if we do require it. And I think we should work hard to try to avoid requiring it (should be possible).

What this does depend on though is what we do with https://github.com/kedro-org/kedro-viz/issues/1000:
* if we remove this plot then we can remove the dependencies right away
* if we want to keep it just in the short term then probably just leave as is but maybe fix the bugs in it
* if we want to keep it longer term then we should fix the bugs and rewrite so it doesn't use these dependencies and then remove them

Overall I'm inclined to go for the 1st option.

**Comment by rashidakanchwala** [comment]
Yes, I think we can remove the dependencies if we show the plot in d3 as discussed here #1000 

We might need to add it back when we work on dataset preview but if we are going to save all the rows in a DB  then we might not even need it. So it makes sense to remove it for now.
